#define SAMPLE_sfx_1_00_twirl_aifc 0x2e0 // build/us_pc/sound/samples/sfx_1/00_twirl.aifc
#define SAMPLE_sfx_1_01_brushing_aifc 0x9d0 // build/us_pc/sound/samples/sfx_1/01_brushing.aifc
#define SAMPLE_sfx_1_02_hand_touch_aifc 0x32a0 // build/us_pc/sound/samples/sfx_1/02_hand_touch.aifc
#define SAMPLE_sfx_1_03_yoshi_aifc 0x35d0 // build/us_pc/sound/samples/sfx_1/03_yoshi.aifc
#define SAMPLE_sfx_1_04_plop_aifc 0x47a0 // build/us_pc/sound/samples/sfx_1/04_plop.aifc
#define SAMPLE_sfx_1_05_heavy_landing_aifc 0x5930 // build/us_pc/sound/samples/sfx_1/05_heavy_landing.aifc
#define SAMPLE_sfx_terrain_00_step_default_aifc 0x7480 // build/us_pc/sound/samples/sfx_terrain/00_step_default.aifc
#define SAMPLE_sfx_terrain_01_step_grass_aifc 0x74e0 // build/us_pc/sound/samples/sfx_terrain/01_step_grass.aifc
#define SAMPLE_sfx_terrain_02_step_stone_aifc 0x7790 // build/us_pc/sound/samples/sfx_terrain/02_step_stone.aifc
#define SAMPLE_sfx_terrain_03_step_spooky_aifc 0x79d0 // build/us_pc/sound/samples/sfx_terrain/03_step_spooky.aifc
#define SAMPLE_sfx_terrain_04_step_snow_aifc 0x8060 // build/us_pc/sound/samples/sfx_terrain/04_step_snow.aifc
#define SAMPLE_sfx_terrain_05_step_ice_aifc 0x86e0 // build/us_pc/sound/samples/sfx_terrain/05_step_ice.aifc
#define SAMPLE_sfx_terrain_06_step_metal_aifc 0x8840 // build/us_pc/sound/samples/sfx_terrain/06_step_metal.aifc
#define SAMPLE_sfx_terrain_07_step_sand_aifc 0xa220 // build/us_pc/sound/samples/sfx_terrain/07_step_sand.aifc
#define SAMPLE_sfx_water_00_plunge_aifc 0xae50 // build/us_pc/sound/samples/sfx_water/00_plunge.aifc
#define SAMPLE_sfx_water_01_splash_aifc 0xe5e0 // build/us_pc/sound/samples/sfx_water/01_splash.aifc
#define SAMPLE_sfx_water_02_swim_aifc 0xfad0 // build/us_pc/sound/samples/sfx_water/02_swim.aifc
#define SAMPLE_sfx_4_00_aifc 0x11660 // build/us_pc/sound/samples/sfx_4/00.aifc
#define SAMPLE_sfx_4_01_aifc 0x132f0 // build/us_pc/sound/samples/sfx_4/01.aifc
#define SAMPLE_sfx_4_02_aifc 0x144c0 // build/us_pc/sound/samples/sfx_4/02.aifc
#define SAMPLE_sfx_4_03_aifc 0x15580 // build/us_pc/sound/samples/sfx_4/03.aifc
#define SAMPLE_sfx_4_04_aifc 0x16a50 // build/us_pc/sound/samples/sfx_4/04.aifc
#define SAMPLE_sfx_4_05_aifc 0x17500 // build/us_pc/sound/samples/sfx_4/05.aifc
#define SAMPLE_sfx_4_06_aifc 0x18010 // build/us_pc/sound/samples/sfx_4/06.aifc
#define SAMPLE_sfx_4_07_aifc 0x18a60 // build/us_pc/sound/samples/sfx_4/07.aifc
#define SAMPLE_sfx_4_08_aifc 0x198c0 // build/us_pc/sound/samples/sfx_4/08.aifc
#define SAMPLE_sfx_4_09_aifc 0x1c140 // build/us_pc/sound/samples/sfx_4/09.aifc
#define SAMPLE_sfx_5_00_aifc 0x1c910 // build/us_pc/sound/samples/sfx_5/00.aifc
#define SAMPLE_sfx_5_01_aifc 0x1def0 // build/us_pc/sound/samples/sfx_5/01.aifc
#define SAMPLE_sfx_5_02_aifc 0x1ef20 // build/us_pc/sound/samples/sfx_5/02.aifc
#define SAMPLE_sfx_5_03_aifc 0x21ba0 // build/us_pc/sound/samples/sfx_5/03.aifc
#define SAMPLE_sfx_5_04_aifc 0x23360 // build/us_pc/sound/samples/sfx_5/04.aifc
#define SAMPLE_sfx_5_05_aifc 0x24560 // build/us_pc/sound/samples/sfx_5/05.aifc
#define SAMPLE_sfx_5_06_aifc 0x27d00 // build/us_pc/sound/samples/sfx_5/06.aifc
#define SAMPLE_sfx_5_07_aifc 0x284b0 // build/us_pc/sound/samples/sfx_5/07.aifc
#define SAMPLE_sfx_5_08_aifc 0x2a820 // build/us_pc/sound/samples/sfx_5/08.aifc
#define SAMPLE_sfx_5_09_aifc 0x2b2a0 // build/us_pc/sound/samples/sfx_5/09.aifc
#define SAMPLE_sfx_5_0A_aifc 0x2b9b0 // build/us_pc/sound/samples/sfx_5/0A.aifc
#define SAMPLE_sfx_5_0B_aifc 0x2bf80 // build/us_pc/sound/samples/sfx_5/0B.aifc
#define SAMPLE_sfx_5_0C_aifc 0x2eb90 // build/us_pc/sound/samples/sfx_5/0C.aifc
#define SAMPLE_sfx_5_0D_aifc 0x344a0 // build/us_pc/sound/samples/sfx_5/0D.aifc
#define SAMPLE_sfx_5_0E_aifc 0x3c2f0 // build/us_pc/sound/samples/sfx_5/0E.aifc
#define SAMPLE_sfx_5_0F_aifc 0x3d360 // build/us_pc/sound/samples/sfx_5/0F.aifc
#define SAMPLE_sfx_5_10_aifc 0x3f810 // build/us_pc/sound/samples/sfx_5/10.aifc
#define SAMPLE_sfx_5_11_aifc 0x3fc50 // build/us_pc/sound/samples/sfx_5/11.aifc
#define SAMPLE_sfx_5_12_aifc 0x43340 // build/us_pc/sound/samples/sfx_5/12.aifc
#define SAMPLE_sfx_5_13_aifc 0x43fd0 // build/us_pc/sound/samples/sfx_5/13.aifc
#define SAMPLE_sfx_5_14_aifc 0x478a0 // build/us_pc/sound/samples/sfx_5/14.aifc
#define SAMPLE_sfx_5_15_aifc 0x4a1b0 // build/us_pc/sound/samples/sfx_5/15.aifc
#define SAMPLE_sfx_5_16_aifc 0x4a980 // build/us_pc/sound/samples/sfx_5/16.aifc
#define SAMPLE_sfx_5_17_aifc 0x4b330 // build/us_pc/sound/samples/sfx_5/17.aifc
#define SAMPLE_sfx_5_18_aifc 0x4c290 // build/us_pc/sound/samples/sfx_5/18.aifc
#define SAMPLE_sfx_5_19_aifc 0x4cab0 // build/us_pc/sound/samples/sfx_5/19.aifc
#define SAMPLE_sfx_5_1A_aifc 0x4cde0 // build/us_pc/sound/samples/sfx_5/1A.aifc
#define SAMPLE_sfx_5_1B_aifc 0x4f610 // build/us_pc/sound/samples/sfx_5/1B.aifc
#define SAMPLE_sfx_5_1C_aifc 0x50fc0 // build/us_pc/sound/samples/sfx_5/1C.aifc
#define SAMPLE_sfx_6_00_aifc 0x52040 // build/us_pc/sound/samples/sfx_6/00.aifc
#define SAMPLE_sfx_6_01_aifc 0x528d0 // build/us_pc/sound/samples/sfx_6/01.aifc
#define SAMPLE_sfx_6_02_aifc 0x53590 // build/us_pc/sound/samples/sfx_6/02.aifc
#define SAMPLE_sfx_6_03_aifc 0x558a0 // build/us_pc/sound/samples/sfx_6/03.aifc
#define SAMPLE_sfx_6_04_aifc 0x59650 // build/us_pc/sound/samples/sfx_6/04.aifc
#define SAMPLE_sfx_6_05_aifc 0x5a140 // build/us_pc/sound/samples/sfx_6/05.aifc
#define SAMPLE_sfx_6_06_aifc 0x5bb00 // build/us_pc/sound/samples/sfx_6/06.aifc
#define SAMPLE_sfx_6_07_aifc 0x5c1c0 // build/us_pc/sound/samples/sfx_6/07.aifc
#define SAMPLE_sfx_6_08_aifc 0x5c6f0 // build/us_pc/sound/samples/sfx_6/08.aifc
#define SAMPLE_sfx_6_09_aifc 0x5e380 // build/us_pc/sound/samples/sfx_6/09.aifc
#define SAMPLE_sfx_6_0A_aifc 0x5eca0 // build/us_pc/sound/samples/sfx_6/0A.aifc
#define SAMPLE_sfx_6_0B_aifc 0x5f620 // build/us_pc/sound/samples/sfx_6/0B.aifc
#define SAMPLE_sfx_6_0C_aifc 0x5feb0 // build/us_pc/sound/samples/sfx_6/0C.aifc
#define SAMPLE_sfx_6_0D_aifc 0x61360 // build/us_pc/sound/samples/sfx_6/0D.aifc
#define SAMPLE_sfx_7_00_aifc 0x63be0 // build/us_pc/sound/samples/sfx_7/00.aifc
#define SAMPLE_sfx_7_01_aifc 0x640a0 // build/us_pc/sound/samples/sfx_7/01.aifc
#define SAMPLE_sfx_7_02_aifc 0x64ef0 // build/us_pc/sound/samples/sfx_7/02.aifc
#define SAMPLE_sfx_7_03_aifc 0x653b0 // build/us_pc/sound/samples/sfx_7/03.aifc
#define SAMPLE_sfx_7_04_aifc 0x67d10 // build/us_pc/sound/samples/sfx_7/04.aifc
#define SAMPLE_sfx_7_05_aifc 0x6a750 // build/us_pc/sound/samples/sfx_7/05.aifc
#define SAMPLE_sfx_7_06_aifc 0x6b760 // build/us_pc/sound/samples/sfx_7/06.aifc
#define SAMPLE_sfx_7_07_aifc 0x6ca30 // build/us_pc/sound/samples/sfx_7/07.aifc
#define SAMPLE_sfx_7_08_aifc 0x6de10 // build/us_pc/sound/samples/sfx_7/08.aifc
#define SAMPLE_sfx_7_09_aifc 0x6e380 // build/us_pc/sound/samples/sfx_7/09.aifc
#define SAMPLE_sfx_7_0A_aifc 0x6f2d0 // build/us_pc/sound/samples/sfx_7/0A.aifc
#define SAMPLE_sfx_7_0B_aifc 0x70b20 // build/us_pc/sound/samples/sfx_7/0B.aifc
#define SAMPLE_sfx_7_0C_aifc 0x720c0 // build/us_pc/sound/samples/sfx_7/0C.aifc
#define SAMPLE_sfx_7_0D_chain_chomp_bark_aifc 0x743b0 // build/us_pc/sound/samples/sfx_7/0D_chain_chomp_bark.aifc
#define SAMPLE_sfx_mario_00_mario_jump_hoo_aifc 0x74ad0 // build/us_pc/sound/samples/sfx_mario/00_mario_jump_hoo.aifc
#define SAMPLE_sfx_mario_01_mario_jump_wah_aifc 0x75230 // build/us_pc/sound/samples/sfx_mario/01_mario_jump_wah.aifc
#define SAMPLE_sfx_mario_02_mario_yah_aifc 0x75a40 // build/us_pc/sound/samples/sfx_mario/02_mario_yah.aifc
#define SAMPLE_sfx_mario_03_mario_haha_aifc 0x764d0 // build/us_pc/sound/samples/sfx_mario/03_mario_haha.aifc
#define SAMPLE_sfx_mario_04_mario_yahoo_aifc 0x77fd0 // build/us_pc/sound/samples/sfx_mario/04_mario_yahoo.aifc
#define SAMPLE_sfx_mario_05_mario_uh_aifc 0x7a120 // build/us_pc/sound/samples/sfx_mario/05_mario_uh.aifc
#define SAMPLE_sfx_mario_06_mario_hrmm_aifc 0x7ac20 // build/us_pc/sound/samples/sfx_mario/06_mario_hrmm.aifc
#define SAMPLE_sfx_mario_07_mario_wah2_aifc 0x7bda0 // build/us_pc/sound/samples/sfx_mario/07_mario_wah2.aifc
#define SAMPLE_sfx_mario_08_mario_whoa_aifc 0x7c830 // build/us_pc/sound/samples/sfx_mario/08_mario_whoa.aifc
#define SAMPLE_sfx_mario_09_mario_eeuh_aifc 0x7e8c0 // build/us_pc/sound/samples/sfx_mario/09_mario_eeuh.aifc
#define SAMPLE_sfx_mario_0A_mario_attacked_aifc 0x801f0 // build/us_pc/sound/samples/sfx_mario/0A_mario_attacked.aifc
#define SAMPLE_sfx_mario_0B_mario_ooof_aifc 0x81800 // build/us_pc/sound/samples/sfx_mario/0B_mario_ooof.aifc
#define SAMPLE_sfx_mario_0C_mario_here_we_go_aifc 0x82db0 // build/us_pc/sound/samples/sfx_mario/0C_mario_here_we_go.aifc
#define SAMPLE_sfx_mario_0D_mario_yawning_aifc 0x85fc0 // build/us_pc/sound/samples/sfx_mario/0D_mario_yawning.aifc
#define SAMPLE_sfx_mario_0E_mario_snoring1_aifc 0x898c0 // build/us_pc/sound/samples/sfx_mario/0E_mario_snoring1.aifc
#define SAMPLE_sfx_mario_0F_mario_snoring2_aifc 0x8b9a0 // build/us_pc/sound/samples/sfx_mario/0F_mario_snoring2.aifc
#define SAMPLE_sfx_mario_10_mario_doh_aifc 0x8c560 // build/us_pc/sound/samples/sfx_mario/10_mario_doh.aifc
#define SAMPLE_sfx_mario_11_mario_game_over_aifc 0x8d980 // build/us_pc/sound/samples/sfx_mario/11_mario_game_over.aifc
#define SAMPLE_sfx_mario_12_mario_hello_aifc 0x8f2b0 // build/us_pc/sound/samples/sfx_mario/12_mario_hello.aifc
#define SAMPLE_sfx_mario_13_mario_press_start_to_play_aifc 0x90dd0 // build/us_pc/sound/samples/sfx_mario/13_mario_press_start_to_play.aifc
#define SAMPLE_sfx_mario_14_mario_twirl_bounce_aifc 0x943a0 // build/us_pc/sound/samples/sfx_mario/14_mario_twirl_bounce.aifc
#define SAMPLE_sfx_mario_15_mario_snoring3_aifc 0x954e0 // build/us_pc/sound/samples/sfx_mario/15_mario_snoring3.aifc
#define SAMPLE_sfx_mario_16_mario_so_longa_bowser_aifc 0xad4a0 // build/us_pc/sound/samples/sfx_mario/16_mario_so_longa_bowser.aifc
#define SAMPLE_sfx_mario_17_mario_ima_tired_aifc 0xb0950 // build/us_pc/sound/samples/sfx_mario/17_mario_ima_tired.aifc
#define SAMPLE_sfx_mario_18_mario_waha_aifc 0xb35e0 // build/us_pc/sound/samples/sfx_mario/18_mario_waha.aifc
#define SAMPLE_sfx_mario_19_mario_yippee_aifc 0xb5bc0 // build/us_pc/sound/samples/sfx_mario/19_mario_yippee.aifc
#define SAMPLE_sfx_mario_1A_mario_lets_a_go_aifc 0xb7f00 // build/us_pc/sound/samples/sfx_mario/1A_mario_lets_a_go.aifc
#define SAMPLE_sfx_9_00_aifc 0xb9f90 // build/us_pc/sound/samples/sfx_9/00.aifc
#define SAMPLE_sfx_9_01_aifc 0xbb710 // build/us_pc/sound/samples/sfx_9/01.aifc
#define SAMPLE_sfx_9_02_aifc 0xbc2d0 // build/us_pc/sound/samples/sfx_9/02.aifc
#define SAMPLE_sfx_9_03_aifc 0xbee00 // build/us_pc/sound/samples/sfx_9/03.aifc
#define SAMPLE_sfx_9_04_camera_buzz_aifc 0xc0f10 // build/us_pc/sound/samples/sfx_9/04_camera_buzz.aifc
#define SAMPLE_sfx_9_05_camera_shutter_aifc 0xc1d90 // build/us_pc/sound/samples/sfx_9/05_camera_shutter.aifc
#define SAMPLE_sfx_9_06_aifc 0xc2420 // build/us_pc/sound/samples/sfx_9/06.aifc
#define SAMPLE_sfx_mario_peach_00_mario_waaaooow_aifc 0xc4ae0 // build/us_pc/sound/samples/sfx_mario_peach/00_mario_waaaooow.aifc
#define SAMPLE_sfx_mario_peach_01_mario_hoohoo_aifc 0xcaba0 // build/us_pc/sound/samples/sfx_mario_peach/01_mario_hoohoo.aifc
#define SAMPLE_sfx_mario_peach_02_mario_panting_aifc 0xcc180 // build/us_pc/sound/samples/sfx_mario_peach/02_mario_panting.aifc
#define SAMPLE_sfx_mario_peach_03_mario_dying_aifc 0xcd600 // build/us_pc/sound/samples/sfx_mario_peach/03_mario_dying.aifc
#define SAMPLE_sfx_mario_peach_04_mario_on_fire_aifc 0xd13b0 // build/us_pc/sound/samples/sfx_mario_peach/04_mario_on_fire.aifc
#define SAMPLE_sfx_mario_peach_05_mario_uh2_aifc 0xd5a90 // build/us_pc/sound/samples/sfx_mario_peach/05_mario_uh2.aifc
#define SAMPLE_sfx_mario_peach_06_mario_coughing_aifc 0xd6380 // build/us_pc/sound/samples/sfx_mario_peach/06_mario_coughing.aifc
#define SAMPLE_sfx_mario_peach_07_mario_its_a_me_mario_aifc 0xd6d80 // build/us_pc/sound/samples/sfx_mario_peach/07_mario_its_a_me_mario.aifc
#define SAMPLE_sfx_mario_peach_08_mario_punch_yah_aifc 0xdb000 // build/us_pc/sound/samples/sfx_mario_peach/08_mario_punch_yah.aifc
#define SAMPLE_sfx_mario_peach_09_mario_punch_hoo_aifc 0xdb8a0 // build/us_pc/sound/samples/sfx_mario_peach/09_mario_punch_hoo.aifc
#define SAMPLE_sfx_mario_peach_0A_mario_mama_mia_aifc 0xdcf00 // build/us_pc/sound/samples/sfx_mario_peach/0A_mario_mama_mia.aifc
#define SAMPLE_sfx_mario_peach_0B_mario_okey_dokey_aifc 0xdef40 // build/us_pc/sound/samples/sfx_mario_peach/0B_mario_okey_dokey.aifc
#define SAMPLE_sfx_mario_peach_0C_mario_drowning_aifc 0xe0f70 // build/us_pc/sound/samples/sfx_mario_peach/0C_mario_drowning.aifc
#define SAMPLE_sfx_mario_peach_0D_mario_thank_you_playing_my_game_aifc 0xe3ea0 // build/us_pc/sound/samples/sfx_mario_peach/0D_mario_thank_you_playing_my_game.aifc
#define SAMPLE_sfx_mario_peach_0E_peach_dear_mario_aifc 0xe9310 // build/us_pc/sound/samples/sfx_mario_peach/0E_peach_dear_mario.aifc
#define SAMPLE_sfx_mario_peach_0F_peach_mario_aifc 0xfe840 // build/us_pc/sound/samples/sfx_mario_peach/0F_peach_mario.aifc
#define SAMPLE_sfx_mario_peach_10_peach_power_of_the_stars_aifc 0x1004f0 // build/us_pc/sound/samples/sfx_mario_peach/10_peach_power_of_the_stars.aifc
#define SAMPLE_sfx_mario_peach_11_peach_thanks_to_you_aifc 0x107a60 // build/us_pc/sound/samples/sfx_mario_peach/11_peach_thanks_to_you.aifc
#define SAMPLE_sfx_mario_peach_12_peach_thank_you_mario_aifc 0x10b6f0 // build/us_pc/sound/samples/sfx_mario_peach/12_peach_thank_you_mario.aifc
#define SAMPLE_sfx_mario_peach_13_peach_something_special_aifc 0x10ee70 // build/us_pc/sound/samples/sfx_mario_peach/13_peach_something_special.aifc
#define SAMPLE_sfx_mario_peach_14_peach_bake_a_cake_aifc 0x114cc0 // build/us_pc/sound/samples/sfx_mario_peach/14_peach_bake_a_cake.aifc
#define SAMPLE_sfx_mario_peach_15_peach_for_mario_aifc 0x11e750 // build/us_pc/sound/samples/sfx_mario_peach/15_peach_for_mario.aifc
#define SAMPLE_sfx_mario_peach_16_peach_mario2_aifc 0x120b80 // build/us_pc/sound/samples/sfx_mario_peach/16_peach_mario2.aifc
#define SAMPLE_instruments_00_aifc 0x122740 // build/us_pc/sound/samples/instruments/00.aifc
#define SAMPLE_instruments_01_banjo_1_aifc 0x125580 // build/us_pc/sound/samples/instruments/01_banjo_1.aifc
#define SAMPLE_instruments_02_aifc 0x127e20 // build/us_pc/sound/samples/instruments/02.aifc
#define SAMPLE_instruments_03_human_whistle_aifc 0x12c1f0 // build/us_pc/sound/samples/instruments/03_human_whistle.aifc
#define SAMPLE_instruments_04_bright_piano_aifc 0x1304e0 // build/us_pc/sound/samples/instruments/04_bright_piano.aifc
#define SAMPLE_instruments_05_acoustic_bass_aifc 0x1322f0 // build/us_pc/sound/samples/instruments/05_acoustic_bass.aifc
#define SAMPLE_instruments_06_kick_drum_1_aifc 0x135a80 // build/us_pc/sound/samples/instruments/06_kick_drum_1.aifc
#define SAMPLE_instruments_07_rimshot_aifc 0x136240 // build/us_pc/sound/samples/instruments/07_rimshot.aifc
#define SAMPLE_instruments_08_aifc 0x136dd0 // build/us_pc/sound/samples/instruments/08.aifc
#define SAMPLE_instruments_09_aifc 0x138250 // build/us_pc/sound/samples/instruments/09.aifc
#define SAMPLE_instruments_0A_tambourine_aifc 0x139d10 // build/us_pc/sound/samples/instruments/0A_tambourine.aifc
#define SAMPLE_instruments_0B_aifc 0x13c2f0 // build/us_pc/sound/samples/instruments/0B.aifc
#define SAMPLE_instruments_0C_conga_stick_aifc 0x13df10 // build/us_pc/sound/samples/instruments/0C_conga_stick.aifc
#define SAMPLE_instruments_0D_clave_aifc 0x13f0b0 // build/us_pc/sound/samples/instruments/0D_clave.aifc
#define SAMPLE_instruments_0E_hihat_closed_aifc 0x1402b0 // build/us_pc/sound/samples/instruments/0E_hihat_closed.aifc
#define SAMPLE_instruments_0F_hihat_open_aifc 0x140b00 // build/us_pc/sound/samples/instruments/0F_hihat_open.aifc
#define SAMPLE_instruments_10_cymbal_bell_aifc 0x143aa0 // build/us_pc/sound/samples/instruments/10_cymbal_bell.aifc
#define SAMPLE_instruments_11_splash_cymbal_aifc 0x146c20 // build/us_pc/sound/samples/instruments/11_splash_cymbal.aifc
#define SAMPLE_instruments_12_snare_drum_1_aifc 0x14b330 // build/us_pc/sound/samples/instruments/12_snare_drum_1.aifc
#define SAMPLE_instruments_13_snare_drum_2_aifc 0x14cf00 // build/us_pc/sound/samples/instruments/13_snare_drum_2.aifc
#define SAMPLE_instruments_14_strings_5_aifc 0x14f570 // build/us_pc/sound/samples/instruments/14_strings_5.aifc
#define SAMPLE_instruments_15_strings_4_aifc 0x1544c0 // build/us_pc/sound/samples/instruments/15_strings_4.aifc
#define SAMPLE_instruments_16_french_horns_aifc 0x159010 // build/us_pc/sound/samples/instruments/16_french_horns.aifc
#define SAMPLE_instruments_17_trumpet_aifc 0x15c960 // build/us_pc/sound/samples/instruments/17_trumpet.aifc
#define SAMPLE_instruments_18_timpani_aifc 0x160140 // build/us_pc/sound/samples/instruments/18_timpani.aifc
#define SAMPLE_instruments_19_brass_aifc 0x164ee0 // build/us_pc/sound/samples/instruments/19_brass.aifc
#define SAMPLE_instruments_1A_slap_bass_aifc 0x1695b0 // build/us_pc/sound/samples/instruments/1A_slap_bass.aifc
#define SAMPLE_instruments_1B_organ_2_aifc 0x16b910 // build/us_pc/sound/samples/instruments/1B_organ_2.aifc
#define SAMPLE_instruments_1C_aifc 0x16f6a0 // build/us_pc/sound/samples/instruments/1C.aifc
#define SAMPLE_instruments_1D_aifc 0x171070 // build/us_pc/sound/samples/instruments/1D.aifc
#define SAMPLE_instruments_1E_closed_triangle_aifc 0x176ca0 // build/us_pc/sound/samples/instruments/1E_closed_triangle.aifc
#define SAMPLE_instruments_1F_open_triangle_aifc 0x1770a0 // build/us_pc/sound/samples/instruments/1F_open_triangle.aifc
#define SAMPLE_instruments_20_cabasa_aifc 0x178920 // build/us_pc/sound/samples/instruments/20_cabasa.aifc
#define SAMPLE_instruments_21_sine_bass_aifc 0x1799b0 // build/us_pc/sound/samples/instruments/21_sine_bass.aifc
#define SAMPLE_instruments_22_boys_choir_aifc 0x17b6a0 // build/us_pc/sound/samples/instruments/22_boys_choir.aifc
#define SAMPLE_instruments_23_strings_1_aifc 0x17edb0 // build/us_pc/sound/samples/instruments/23_strings_1.aifc
#define SAMPLE_instruments_24_strings_2_aifc 0x182bc0 // build/us_pc/sound/samples/instruments/24_strings_2.aifc
#define SAMPLE_instruments_25_strings_3_aifc 0x1872b0 // build/us_pc/sound/samples/instruments/25_strings_3.aifc
#define SAMPLE_instruments_26_crystal_rhodes_aifc 0x18b710 // build/us_pc/sound/samples/instruments/26_crystal_rhodes.aifc
#define SAMPLE_instruments_27_harpsichord_aifc 0x192800 // build/us_pc/sound/samples/instruments/27_harpsichord.aifc
#define SAMPLE_instruments_28_sitar_1_aifc 0x198e50 // build/us_pc/sound/samples/instruments/28_sitar_1.aifc
#define SAMPLE_instruments_29_orchestra_hit_aifc 0x19cc50 // build/us_pc/sound/samples/instruments/29_orchestra_hit.aifc
#define SAMPLE_instruments_2A_aifc 0x19fdd0 // build/us_pc/sound/samples/instruments/2A.aifc
#define SAMPLE_instruments_2B_aifc 0x1a34b0 // build/us_pc/sound/samples/instruments/2B.aifc
#define SAMPLE_instruments_2C_aifc 0x1a52a0 // build/us_pc/sound/samples/instruments/2C.aifc
#define SAMPLE_instruments_2D_trombone_aifc 0x1a98e0 // build/us_pc/sound/samples/instruments/2D_trombone.aifc
#define SAMPLE_instruments_2E_accordion_aifc 0x1ad4f0 // build/us_pc/sound/samples/instruments/2E_accordion.aifc
#define SAMPLE_instruments_2F_sleigh_bells_aifc 0x1b1c30 // build/us_pc/sound/samples/instruments/2F_sleigh_bells.aifc
#define SAMPLE_instruments_30_rarefaction_lahna_aifc 0x1b6da0 // build/us_pc/sound/samples/instruments/30_rarefaction-lahna.aifc
#define SAMPLE_instruments_31_rarefaction_convolution_aifc 0x1bb3d0 // build/us_pc/sound/samples/instruments/31_rarefaction-convolution.aifc
#define SAMPLE_instruments_32_metal_rimshot_aifc 0x1bf010 // build/us_pc/sound/samples/instruments/32_metal_rimshot.aifc
#define SAMPLE_instruments_33_kick_drum_2_aifc 0x1c31a0 // build/us_pc/sound/samples/instruments/33_kick_drum_2.aifc
#define SAMPLE_instruments_34_alto_flute_aifc 0x1c4370 // build/us_pc/sound/samples/instruments/34_alto_flute.aifc
#define SAMPLE_instruments_35_gospel_organ_aifc 0x1c6810 // build/us_pc/sound/samples/instruments/35_gospel_organ.aifc
#define SAMPLE_instruments_36_sawtooth_synth_aifc 0x1c9220 // build/us_pc/sound/samples/instruments/36_sawtooth_synth.aifc
#define SAMPLE_instruments_37_square_synth_aifc 0x1cb2b0 // build/us_pc/sound/samples/instruments/37_square_synth.aifc
#define SAMPLE_instruments_38_electric_kick_drum_aifc 0x1ccfd0 // build/us_pc/sound/samples/instruments/38_electric_kick_drum.aifc
#define SAMPLE_instruments_39_sitar_2_aifc 0x1cd990 // build/us_pc/sound/samples/instruments/39_sitar_2.aifc
#define SAMPLE_instruments_3A_music_box_aifc 0x1d2c00 // build/us_pc/sound/samples/instruments/3A_music_box.aifc
#define SAMPLE_instruments_3B_banjo_2_aifc 0x1d6680 // build/us_pc/sound/samples/instruments/3B_banjo_2.aifc
#define SAMPLE_instruments_3C_acoustic_guitar_aifc 0x1dc0f0 // build/us_pc/sound/samples/instruments/3C_acoustic_guitar.aifc
#define SAMPLE_instruments_3D_aifc 0x1e0c20 // build/us_pc/sound/samples/instruments/3D.aifc
#define SAMPLE_instruments_3E_monk_choir_aifc 0x1e3cb0 // build/us_pc/sound/samples/instruments/3E_monk_choir.aifc
#define SAMPLE_instruments_3F_aifc 0x1e6990 // build/us_pc/sound/samples/instruments/3F.aifc
#define SAMPLE_instruments_40_bell_aifc 0x1eb730 // build/us_pc/sound/samples/instruments/40_bell.aifc
#define SAMPLE_instruments_41_pan_flute_aifc 0x1ef390 // build/us_pc/sound/samples/instruments/41_pan_flute.aifc
#define SAMPLE_instruments_42_vibraphone_aifc 0x1f39d0 // build/us_pc/sound/samples/instruments/42_vibraphone.aifc
#define SAMPLE_instruments_43_harmonica_aifc 0x1f4580 // build/us_pc/sound/samples/instruments/43_harmonica.aifc
#define SAMPLE_instruments_44_grand_piano_aifc 0x1f7730 // build/us_pc/sound/samples/instruments/44_grand_piano.aifc
#define SAMPLE_instruments_45_french_horns_lq_aifc 0x1fb2c0 // build/us_pc/sound/samples/instruments/45_french_horns_lq.aifc
#define SAMPLE_instruments_46_pizzicato_strings_1_aifc 0x1fcf90 // build/us_pc/sound/samples/instruments/46_pizzicato_strings_1.aifc
#define SAMPLE_instruments_47_pizzicato_strings_2_aifc 0x1ffc10 // build/us_pc/sound/samples/instruments/47_pizzicato_strings_2.aifc
#define SAMPLE_instruments_48_steel_drum_aifc 0x203040 // build/us_pc/sound/samples/instruments/48_steel_drum.aifc
#define SAMPLE_piranha_music_box_00_music_box_aifc 0x206a10 // build/us_pc/sound/samples/piranha_music_box/00_music_box.aifc
#define SAMPLE_course_start_00_la_aifc 0x20a490 // build/us_pc/sound/samples/course_start/00_la.aifc
#define SAMPLE_bowser_organ_00_organ_1_aifc 0x20bde0 // build/us_pc/sound/samples/bowser_organ/00_organ_1.aifc
#define SAMPLE_bowser_organ_01_organ_1_lq_aifc 0x215be0 // build/us_pc/sound/samples/bowser_organ/01_organ_1_lq.aifc
#define SAMPLE_bowser_organ_02_boys_choir_aifc 0x219d80 // build/us_pc/sound/samples/bowser_organ/02_boys_choir.aifc
#define SAMPLE_extended_00_aifc 0x456860 // build/us_pc/sound/samples/extended/00.aifc
#define SAMPLE_extended_00_la_aifc 0x4596a0 // build/us_pc/sound/samples/extended/00_la.aifc
#define SAMPLE_extended_00_music_box_aifc 0x45aff0 // build/us_pc/sound/samples/extended/00_music_box.aifc
#define SAMPLE_extended_00_organ_1_aifc 0x45ea70 // build/us_pc/sound/samples/extended/00_organ_1.aifc
#define SAMPLE_extended_01_banjo_1_aifc 0x468870 // build/us_pc/sound/samples/extended/01_banjo_1.aifc
#define SAMPLE_extended_01_organ_1_lq_aifc 0x46b110 // build/us_pc/sound/samples/extended/01_organ_1_lq.aifc
#define SAMPLE_extended_02_aifc 0x46f2b0 // build/us_pc/sound/samples/extended/02.aifc
#define SAMPLE_extended_02_boys_choir_aifc 0x473680 // build/us_pc/sound/samples/extended/02_boys_choir.aifc
#define SAMPLE_extended_03_human_whistle_aifc 0x476d90 // build/us_pc/sound/samples/extended/03_human_whistle.aifc
#define SAMPLE_extended_04_bright_piano_aifc 0x47b080 // build/us_pc/sound/samples/extended/04_bright_piano.aifc
#define SAMPLE_extended_05_acoustic_bass_aifc 0x47ce90 // build/us_pc/sound/samples/extended/05_acoustic_bass.aifc
#define SAMPLE_extended_06_kick_drum_1_aifc 0x480620 // build/us_pc/sound/samples/extended/06_kick_drum_1.aifc
#define SAMPLE_extended_07_rimshot_aifc 0x480de0 // build/us_pc/sound/samples/extended/07_rimshot.aifc
#define SAMPLE_extended_08_aifc 0x481970 // build/us_pc/sound/samples/extended/08.aifc
#define SAMPLE_extended_09_aifc 0x482df0 // build/us_pc/sound/samples/extended/09.aifc
#define SAMPLE_extended_0A_tambourine_aifc 0x4848b0 // build/us_pc/sound/samples/extended/0A_tambourine.aifc
#define SAMPLE_extended_0B_aifc 0x486e90 // build/us_pc/sound/samples/extended/0B.aifc
#define SAMPLE_extended_0C_conga_stick_aifc 0x488ab0 // build/us_pc/sound/samples/extended/0C_conga_stick.aifc
#define SAMPLE_extended_0D_clave_aifc 0x489c50 // build/us_pc/sound/samples/extended/0D_clave.aifc
#define SAMPLE_extended_0E_hihat_closed_aifc 0x48ae50 // build/us_pc/sound/samples/extended/0E_hihat_closed.aifc
#define SAMPLE_extended_0F_hihat_open_aifc 0x48b6a0 // build/us_pc/sound/samples/extended/0F_hihat_open.aifc
#define SAMPLE_extended_10_cymbal_bell_aifc 0x48e640 // build/us_pc/sound/samples/extended/10_cymbal_bell.aifc
#define SAMPLE_extended_11_splash_cymbal_aifc 0x4917c0 // build/us_pc/sound/samples/extended/11_splash_cymbal.aifc
#define SAMPLE_extended_12_snare_drum_1_aifc 0x495ed0 // build/us_pc/sound/samples/extended/12_snare_drum_1.aifc
#define SAMPLE_extended_13_snare_drum_2_aifc 0x497aa0 // build/us_pc/sound/samples/extended/13_snare_drum_2.aifc
#define SAMPLE_extended_14_strings_5_aifc 0x49a110 // build/us_pc/sound/samples/extended/14_strings_5.aifc
#define SAMPLE_extended_15_strings_4_aifc 0x49f060 // build/us_pc/sound/samples/extended/15_strings_4.aifc
#define SAMPLE_extended_16_french_horns_aifc 0x4a3bb0 // build/us_pc/sound/samples/extended/16_french_horns.aifc
#define SAMPLE_extended_17_trumpet_aifc 0x4a7500 // build/us_pc/sound/samples/extended/17_trumpet.aifc
#define SAMPLE_extended_18_timpani_aifc 0x4aace0 // build/us_pc/sound/samples/extended/18_timpani.aifc
#define SAMPLE_extended_19_brass_aifc 0x4afa80 // build/us_pc/sound/samples/extended/19_brass.aifc
#define SAMPLE_extended_1A_slap_bass_aifc 0x4b4150 // build/us_pc/sound/samples/extended/1A_slap_bass.aifc
#define SAMPLE_extended_1B_organ_2_aifc 0x4b64b0 // build/us_pc/sound/samples/extended/1B_organ_2.aifc
#define SAMPLE_extended_1C_aifc 0x4ba240 // build/us_pc/sound/samples/extended/1C.aifc
#define SAMPLE_extended_1D_aifc 0x4bbc10 // build/us_pc/sound/samples/extended/1D.aifc
#define SAMPLE_extended_1E_closed_triangle_aifc 0x4c1840 // build/us_pc/sound/samples/extended/1E_closed_triangle.aifc
#define SAMPLE_extended_1F_open_triangle_aifc 0x4c1c40 // build/us_pc/sound/samples/extended/1F_open_triangle.aifc
#define SAMPLE_extended_20_cabasa_aifc 0x4c34c0 // build/us_pc/sound/samples/extended/20_cabasa.aifc
#define SAMPLE_extended_21_sine_bass_aifc 0x4c4550 // build/us_pc/sound/samples/extended/21_sine_bass.aifc
#define SAMPLE_extended_22_boys_choir_aifc 0x4c6240 // build/us_pc/sound/samples/extended/22_boys_choir.aifc
#define SAMPLE_extended_23_strings_1_aifc 0x4c9950 // build/us_pc/sound/samples/extended/23_strings_1.aifc
#define SAMPLE_extended_24_strings_2_aifc 0x4cd760 // build/us_pc/sound/samples/extended/24_strings_2.aifc
#define SAMPLE_extended_25_strings_3_aifc 0x4d1e50 // build/us_pc/sound/samples/extended/25_strings_3.aifc
#define SAMPLE_extended_26_crystal_rhodes_aifc 0x4d62b0 // build/us_pc/sound/samples/extended/26_crystal_rhodes.aifc
#define SAMPLE_extended_27_harpsichord_aifc 0x4dd3a0 // build/us_pc/sound/samples/extended/27_harpsichord.aifc
#define SAMPLE_extended_28_sitar_1_aifc 0x4e39f0 // build/us_pc/sound/samples/extended/28_sitar_1.aifc
#define SAMPLE_extended_29_orchestra_hit_aifc 0x4e77f0 // build/us_pc/sound/samples/extended/29_orchestra_hit.aifc
#define SAMPLE_extended_2A_aifc 0x4ea970 // build/us_pc/sound/samples/extended/2A.aifc
#define SAMPLE_extended_2B_aifc 0x4ee050 // build/us_pc/sound/samples/extended/2B.aifc
#define SAMPLE_extended_2C_aifc 0x4efe40 // build/us_pc/sound/samples/extended/2C.aifc
#define SAMPLE_extended_2D_trombone_aifc 0x4f4480 // build/us_pc/sound/samples/extended/2D_trombone.aifc
#define SAMPLE_extended_2E_accordion_aifc 0x4f8090 // build/us_pc/sound/samples/extended/2E_accordion.aifc
#define SAMPLE_extended_2F_sleigh_bells_aifc 0x4fc7d0 // build/us_pc/sound/samples/extended/2F_sleigh_bells.aifc
#define SAMPLE_extended_30_rarefaction_lahna_aifc 0x501940 // build/us_pc/sound/samples/extended/30_rarefaction-lahna.aifc
#define SAMPLE_extended_31_rarefaction_convolution_aifc 0x505f70 // build/us_pc/sound/samples/extended/31_rarefaction-convolution.aifc
#define SAMPLE_extended_32_metal_rimshot_aifc 0x509bb0 // build/us_pc/sound/samples/extended/32_metal_rimshot.aifc
#define SAMPLE_extended_33_kick_drum_2_aifc 0x50dd40 // build/us_pc/sound/samples/extended/33_kick_drum_2.aifc
#define SAMPLE_extended_34_alto_flute_aifc 0x50ef10 // build/us_pc/sound/samples/extended/34_alto_flute.aifc
#define SAMPLE_extended_35_gospel_organ_aifc 0x5113b0 // build/us_pc/sound/samples/extended/35_gospel_organ.aifc
#define SAMPLE_extended_36_sawtooth_synth_aifc 0x513dc0 // build/us_pc/sound/samples/extended/36_sawtooth_synth.aifc
#define SAMPLE_extended_37_square_synth_aifc 0x515e50 // build/us_pc/sound/samples/extended/37_square_synth.aifc
#define SAMPLE_extended_38_electric_kick_drum_aifc 0x517b70 // build/us_pc/sound/samples/extended/38_electric_kick_drum.aifc
#define SAMPLE_extended_39_sitar_2_aifc 0x518530 // build/us_pc/sound/samples/extended/39_sitar_2.aifc
#define SAMPLE_extended_3A_music_box_aifc 0x51d7a0 // build/us_pc/sound/samples/extended/3A_music_box.aifc
#define SAMPLE_extended_3B_banjo_2_aifc 0x521220 // build/us_pc/sound/samples/extended/3B_banjo_2.aifc
#define SAMPLE_extended_3C_acoustic_guitar_aifc 0x526c90 // build/us_pc/sound/samples/extended/3C_acoustic_guitar.aifc
#define SAMPLE_extended_3D_aifc 0x52b7c0 // build/us_pc/sound/samples/extended/3D.aifc
#define SAMPLE_extended_3E_monk_choir_aifc 0x52e850 // build/us_pc/sound/samples/extended/3E_monk_choir.aifc
#define SAMPLE_extended_3F_aifc 0x531530 // build/us_pc/sound/samples/extended/3F.aifc
#define SAMPLE_extended_40_bell_aifc 0x5362d0 // build/us_pc/sound/samples/extended/40_bell.aifc
#define SAMPLE_extended_41_pan_flute_aifc 0x539f30 // build/us_pc/sound/samples/extended/41_pan_flute.aifc
#define SAMPLE_extended_42_vibraphone_aifc 0x53e570 // build/us_pc/sound/samples/extended/42_vibraphone.aifc
#define SAMPLE_extended_43_harmonica_aifc 0x53f120 // build/us_pc/sound/samples/extended/43_harmonica.aifc
#define SAMPLE_extended_44_grand_piano_aifc 0x5422d0 // build/us_pc/sound/samples/extended/44_grand_piano.aifc
#define SAMPLE_extended_45_french_horns_lq_aifc 0x545e60 // build/us_pc/sound/samples/extended/45_french_horns_lq.aifc
#define SAMPLE_extended_46_pizzicato_strings_1_aifc 0x547b30 // build/us_pc/sound/samples/extended/46_pizzicato_strings_1.aifc
#define SAMPLE_extended_47_pizzicato_strings_2_aifc 0x54a7b0 // build/us_pc/sound/samples/extended/47_pizzicato_strings_2.aifc
#define SAMPLE_extended_48_steel_drum_aifc 0x54dbe0 // build/us_pc/sound/samples/extended/48_steel_drum.aifc
