import re
import sys
from extract_functions import *
from common import *
from vec_types import *
from exposed_lists import \
    functions_files, \
    functions_whitelist, \
    functions_blacklist, \
    functions_hidden, \
    functions_version_excludes, \
    functions_params_types

verbose = len(sys.argv) > 1 and (sys.argv[1] == "-v" or sys.argv[1] == "--verbose")

rejects = ""
integer_types = ["u8", "u16", "u32", "u64", "s8", "s16", "s32", "s64", "int", "lua_Integer"]
number_types = ["f32", "float", "f64", "double", "lua_Number"]
parameter_keywords = ["VEC_OUT", "RET", "INOUT", "OPTIONAL"]
out_filename = 'src/pc/lua/smlua_functions_autogen.c'
out_filename_docs = 'docs/lua/functions%s.md'
out_filename_defs = 'autogen/lua_definitions/functions.lua'
manually_written_functions_filename = 'autogen/lua_definitions/manual.lua'
enums_filename = 'autogen/lua_definitions/constants.lua'
hooks_filename = 'autogen/lua_definitions/hooks.lua'
out_filename_hooks = 'docs/lua/guides/hooks.md'

###########################################################

template = """/* THIS FILE IS AUTOGENERATED */
/* SHOULD NOT BE MANUALLY CHANGED */

#include "smlua.h"

$[INCLUDES]

$[TYPES]

$[FUNCTIONS]

void smlua_bind_functions_autogen(void) {
    lua_State* L = gLuaState;
$[BINDS]
}
"""

###########################################################

vec_type_before = "    %s $[IDENTIFIER]; smlua_get_%s($[IDENTIFIER], $[INDEX]);\n"
vec_type_after  = "    smlua_push_%s($[IDENTIFIER], $[INDEX]);\n"

vec_type_check  = "smlua_check_%s(%i)"

#
# Special cases for sound functions
#

SOUND_FUNCTIONS = [
    "play_sound",
    "play_sound_with_freq_scale",
    "stop_sound",
    "stop_sounds_from_source",
]

vec3f_sound_before = "    f32 *$[IDENTIFIER] = smlua_get_vec3f_from_buffer(); smlua_get_vec3f($[IDENTIFIER], $[INDEX]);\n"

############################################################################

total_functions = 0
total_doc_functions = 0
header_h = ""

def reject_line(line):
    if len(line) == 0:
        return True
    if '(' not in line:
        return True
    if ')' not in line:
        return True
    if ';' not in line:
        return True

def normalize_type(t):
    if 'char' not in t:
        t = t.replace('const', '')

    t = t.strip()
    if ' ' in t:
        parts = t.split(' ', 1)
        t = parts[0] + ' ' + parts[1].replace(' ', '')
    return t

def is_enum(t):
    return t.startswith('enum ')

############################################################################

def build_vec_types():
    s = gen_comment_header("vec types")
    for type_name, vec_type in VEC_TYPES.items():

        # New
        s += "void smlua_new_%s(%s src) {\n" % (type_name.lower(), type_name)
        s += "    struct lua_State *L = gLuaState;\n"
        s += "    lua_newtable(L);\n"
        s += "    int tableIndex = lua_gettop(L);\n"
        for lua_field, c_field in vec_type["fields_mapping"].items():
            s += "    lua_pushstring(L, \"%s\");\n" % (lua_field)
            s += "    lua_push%s(L, src%s);\n" % (vec_type["field_lua_type"], c_field)
            s += "    lua_settable(L, tableIndex);\n"
        s += "}\n\n"

        # Get
        s += "void smlua_get_%s(%s dest, int index) {\n" % (type_name.lower(), type_name)
        for lua_field, c_field in vec_type["fields_mapping"].items():
            s += "    dest%s = smlua_get_%s_field(index, \"%s\");\n" % (c_field, vec_type["field_lua_type"], lua_field)
        s += "}\n\n"

        # Push
        s += "void smlua_push_%s(%s src, int index) {\n" % (type_name.lower(), type_name)
        for lua_field, c_field in vec_type["fields_mapping"].items():
            s += "    smlua_push_%s_field(index, \"%s\", src%s);\n" % (vec_type["field_lua_type"], lua_field, c_field)
        for lua_field, c_field in vec_type.get('optional_fields_mapping', {}).items():
            s += "    smlua_push_%s_field(index, \"%s\", src%s);\n" % (vec_type["field_lua_type"], lua_field, c_field)
        s += "}\n\n"

    return s

############################################################################

def build_param(fid, param, i):
    ptype = param['type']
    pid = param['identifier']

    if "struct TextureInfo" in ptype and "*" in ptype:
        return '    struct TextureInfo *texInfo = smlua_to_texture_info(L, %d);\n' % (i)

    if ptype in VEC_TYPES:
        if ptype == "Vec3f" and fid in SOUND_FUNCTIONS:
            return vec3f_sound_before.replace('$[IDENTIFIER]', str(pid)).replace('$[INDEX]', str(i))
        else:
            return (vec_type_before % (ptype, ptype.lower())).replace('$[IDENTIFIER]', str(pid)).replace('$[INDEX]', str(i))
    elif ptype == 'bool':
        return '    %s %s = smlua_to_boolean(L, %d);\n' % (ptype, pid, i)
    elif ptype in integer_types or is_enum(ptype):
        return '    %s %s = smlua_to_integer(L, %d);\n' % (ptype, pid, i)
    elif ptype in number_types:
        return '    %s %s = smlua_to_number(L, %d);\n' % (ptype, pid, i)
    elif ptype == 'const char*':
        return '    %s %s = smlua_to_string(L, %d);\n' % (ptype, pid, i)
    elif ptype == 'ByteString':
        return '    %s %s = smlua_to_bytestring(L, %d);\n' % (ptype, pid, i)
    elif ptype == 'LuaFunction':
        return '    %s %s = smlua_to_lua_function(L, %d);\n' % (ptype, pid, i)
    elif ptype == 'LuaTable':
        return '    %s %s = smlua_to_lua_table(L, %d);\n' % (ptype, pid, i)
    elif translate_type_to_lot(ptype) == 'LOT_POINTER':
        lvt = translate_type_to_lvt(ptype)
        return '    %s %s = (%s)smlua_to_cpointer(L, %d, %s);\n' % (ptype, pid, ptype, i, lvt)
    else:
        lot = translate_type_to_lot(ptype)
        s = '  %s %s = (%s)smlua_to_cobject(L, %d, %s);' % (ptype, pid, ptype, i, lot)

        if '???' in lot:
            s = '//' + s + ' <--- UNIMPLEMENTED'
        else:
            s = '  ' + s

        return s + '\n'

def build_param_after(param, i):
    ptype = param['type']
    pid = param['identifier']
    is_output = 'VEC_OUT' in param

    if ptype in VEC_TYPES and is_output:
        return (vec_type_after % (ptype.lower())).replace('$[IDENTIFIER]', str(pid)).replace('$[INDEX]', str(i))
    else:
        return ''

def build_param_check(param, i):
    ptype = param['type']

    if "struct TextureInfo" in ptype and "*" in ptype:
        return 'smlua_is_cobject(L, %d, LOT_TEXTUREINFO);\n' % (i)

    if ptype in VEC_TYPES \
      or ptype == 'LuaTable':    return 'lua_istable(L, %d)'    % (i)
    elif ptype == 'bool':        return 'lua_isboolean(L, %d)'  % (i)
    elif ptype in integer_types: return 'lua_isinteger(L, %d)'  % (i)
    elif ptype in number_types:  return 'lua_isnumber(L, %d)'   % (i)
    elif ptype == 'const char*' \
      or ptype == 'ByteString':  return 'lua_isstring(L, %d)'   % (i)
    elif ptype == 'LuaFunction': return 'lua_isfunction(L, %d)' % (i)
    elif translate_type_to_lot(ptype) == 'LOT_POINTER':
        lvt = translate_type_to_lvt(ptype)
        return 'smlua_is_cpointer(L, %d, %s)' % (i, lvt)
    else:
        lot = translate_type_to_lot(ptype)
        return 'smlua_is_cobject(L, %d, %s)' % (i, lot)

def build_return_value(id, rtype):
    lot = translate_type_to_lot(rtype)

    lfunc = 'UNIMPLEMENTED -->'
    if rtype in integer_types or is_enum(rtype):
        lfunc = 'lua_pushinteger'
    elif rtype in number_types:
        lfunc = 'lua_pushnumber'
    elif rtype == 'bool':
        lfunc = 'lua_pushboolean'
    elif rtype == 'char*':
        lfunc = 'lua_pushstring'
    elif rtype == 'const char*':
        lfunc = 'lua_pushstring'
    elif rtype == 'ByteString':
        lfunc = 'smlua_push_bytestring'
    elif rtype == 'LuaTable':
        lfunc = 'smlua_push_lua_table'
    elif lot == 'LOT_POINTER':
        lvt = translate_type_to_lvt(rtype)
        return '    smlua_push_pointer(L, %s, (void*)%s, NULL);\n' % (lvt, id)
    elif '???' not in lot and lot != 'LOT_NONE':
        return '    smlua_push_object(L, %s, %s, NULL);\n' % (lot, id)

    return '    %s(L, %s);\n' % (lfunc, id)

def build_call(function):
    ftype = function['type']
    fid = function['identifier']

    ccall = '%s(%s)' % (fid, ', '.join([('&' if ('RET' in x or 'INOUT' in x) else '') + x['identifier'] for x in function['params']]))

    if ftype == 'void':
        return '    %s;\n' % ccall
    # We can't possibly know the type of a void pointer,
    # So we just don't return anything from it
    elif ftype == 'void *':
        return '    %s;\n' % ccall

    if ftype in VECP_TYPES:
        return '    %s;\n' % ccall

    return build_return_value(ccall, ftype)

def split_function_parameters_and_returns(function):
    fparams = []
    freturns = []
    for param in function['params']:
        deref_type = param['type'][:param['type'].rfind('*')].strip() # Remove pointer
        if 'INOUT' in param:
            fparams.append({ **{ k: v for k, v in param.items() if k != "type" }, "type": deref_type})
            freturns.append({ **param, "rtype": deref_type })
        elif 'RET' in param:
            freturns.append({ **param, "rtype": deref_type })
        else:
            fparams.append(param)
    return fparams, freturns

def get_params_bounds(params):
    return len(params), len([param for param in params if 'OPTIONAL' not in param])

def build_overloaded_function(function, do_extern):
    s = ''
    fid = function['identifier']
    overload = function['overload']
    oblocks = []
    bounds = {}
    for func in overload:
        func['filename'] = function['filename']
        built = build_function(func, do_extern)
        if func['implemented']: function['implemented'] = True

        built = built.split('\n\n')[2:-1]
        built[-1] = built[-1][:-2]
        if len(built) == 3:
            built[0] = built[0].replace(func['identifier'], function['identifier'])
        built = '\n\n'.join(built)

        fparams, freturns = split_function_parameters_and_returns(func)
        params_max, params_min = get_params_bounds(fparams)

        bounds["top != %i" % params_max if params_min == params_max else "(top < %d || top > %d)" % (params_min, params_max)] \
             = "%i"        % params_max if params_min == params_max else "between %d and %d"      % (params_min, params_max)

        oblocks.append({'params': fparams, 'lines': built, 'count': params_min, 'max': params_max})

    s += """int smlua_func_%s(lua_State* L) {
    if (L == NULL) { return 0; }\n
    int top = lua_gettop(L);
    if (%s) {
        LOG_LUA_LINE("Improper param count for '%s': Expected %s, Received %%u", top);
        return 0;
    }\n\n""" % (fid, ' && '.join(bounds.keys()), fid, ' or '.join(bounds.values()))

    def add_block(block, i, unique=False):
        if block not in oblocks: return

        nonlocal s
        first = len(oblocks) == len(overload)
        last = len(oblocks) == 1
        s += '    ' if first else ' else '
        if not last:
            if unique: s += 'if (top == %i) ' % i
            else: s += 'if (%s) ' % build_param_check(block['params'][i - 1], i)
        s += '{\n'
        for line in block['lines'].splitlines():
            s += '    ' + line + '\n'
        s = s[:-1] + '\n    }'
        oblocks.remove(block)

    i = 0
    while len(oblocks) > 0:
        candidates = []
        ptypes = {}
        for block in oblocks:
            if i >= block['max']: continue
            if i + 1 == block['count'] and block['count'] == block['max']:
                candidates.append(block)

            ptype = block['params'][i]['type']
            if ptypes.get(ptype) is None: ptypes[ptype] = []
            ptypes[ptype].append(block)

        for blocks in ptypes.values():
            if len(blocks) == 1:
                for block in blocks: add_block(block, i + 1)

        if len(candidates) == 1:
            add_block(candidates[0], i + 1, True)

        i += 1

    s += '\n}\n'

    return s + '\n'

def build_function(function, do_extern):
    if function.get('overload') is not None:
        return build_overloaded_function(function, do_extern)

    s = ''
    fid = function['identifier']

    if fid in functions_version_excludes:
        s += '#ifndef ' + functions_version_excludes[fid] + '\n'

    fparams, freturns = split_function_parameters_and_returns(function)

    s += 'int smlua_func_%s(lua_State* L) {\n' % fid

    # make sure the bhv functions have a current object
    fname = function['filename']
    if fname == 'behavior_actions.h' or fname == 'obj_behaviors_2.h' or fname == 'obj_behaviors.h':
        if 'bhv_' in fid and len(fparams) == 0:
            s += '    if (!gCurrentObject) { return 0; }\n'

    s += """    if (L == NULL) { return 0; }\n
    int top = lua_gettop(L);"""

    params_max, params_min = get_params_bounds(fparams)
    if params_min == params_max:
        s += """
    if (top != %d) {
        LOG_LUA_LINE("Improper param count for '%%s': Expected %%u, Received %%u", "%s", %d, top);
        return 0;
    }\n\n""" % (params_max, fid, params_max)
    else:
        s += """
    if (top < %d || top > %d) {
        LOG_LUA_LINE("Improper param count for '%%s': Expected between %%u and %%u, Received %%u", "%s", %d, %d, top);
        return 0;
    }\n\n""" % (params_min, params_max, fid, params_min, params_max)

    is_interact_func = fid.startswith('interact_') and fname == 'interaction.h'

    i = 1
    for param in fparams:
        pid = param['identifier']
        if is_interact_func and pid == 'interactType':
            s += "    // interactType skipped so mods can't lie about what interaction it is\n"
        elif 'OPTIONAL' in param:
            sparam = build_param(fid, param, i)
            param_var, param_value = sparam.strip().split(' = ')
            param_type = param['type']
            s += '    %s = (%s) %s;\n' % (param_var, param_type, "NULL" if '*' in param_type else "0")
            s += '    if (top >= %d) {\n' % (i)
            s += '        %s = %s\n' % (pid, param_value)
            s += '        if (!gSmLuaConvertSuccess) { LOG_LUA("Failed to convert parameter %%u for function \'%%s\'", %d, "%s"); return 0; }\n' % (i, fid)
            s += '    }\n'
        else:
            s += build_param(fid, param, i)
            s += '    if (!gSmLuaConvertSuccess) { LOG_LUA("Failed to convert parameter %%u for function \'%%s\'", %d, "%s"); return 0; }\n' % (i, fid)
        i += 1
    if params_max > 0: s += '\n'

    if freturns:
        for param in freturns:
            if 'INOUT' not in param:
                pid = param['identifier']
                ptype = param['rtype']
                s += '    %s %s;\n' % (ptype, pid)
        s += '\n'

    if do_extern:
        s += '    extern %s\n' % function['line']

    push_value = True
    if is_interact_func:
        # special case for interaction functions to call the hooks associated with interactions
        s += "    lua_pushinteger(L, process_interaction(m, " + fid.upper() + ", o, " + fid + "));\n"
    else:
        call_str = build_call(function)
        push_value = "lua_push" in call_str
        s += call_str

    i = 1
    for param in function['params']:
        s += build_param_after(param, i)
        i += 1
    s += '\n'

    vec_out_count = 0

    # To allow chaining vector functions calls, return the table corresponding to the `VEC_OUT` parameter
    if function['type'] in VECP_TYPES:
        for i, param in enumerate(function['params']):
            if 'VEC_OUT' in param:
                vec_out_count += 1
                s += '    lua_settop(L, %d);\n' % (i + 1)
                break

    # Push extra return values
    if freturns:
        for param in freturns:
            pid = param['identifier']
            ptype = param['rtype']
            s += build_return_value(pid, ptype)
        s += '\n'

    num_returns = push_value + len(freturns) + vec_out_count
    s += '    return %d;\n}\n' % num_returns

    if fid in functions_version_excludes:
        s += '#endif\n'

    function['implemented'] = 'UNIMPLEMENTED' not in s
    if 'UNIMPLEMENTED' in s:
        s = "/*\n" + s + "*/\n"
    else:
        global total_functions
        total_functions += 1
        if function['description'][0] != "":
            global total_doc_functions
            total_doc_functions += 1
        elif verbose:
            print("UNDOCUMENTED: " + function['filename'] + ":     " + function['line'])

    return s + "\n"

def build_functions(processed_files):
    s = ''
    for processed_file in processed_files:
        s += gen_comment_header(processed_file['filename'])

        for function in processed_file['functions']:
            function['filename'] = processed_file['filename']
            s += build_function(function, processed_file['extern'])
    return s

def build_bind(function):
    fid = function['identifier']
    s = 'smlua_bind_function(L, "%s", smlua_func_%s);' % (fid, fid)
    if function['implemented']:
        s = '    ' + s
        # There is no point in adding the ifndef statement if the function is commented out here anyways.
        # So we only do it on implemented functions.
        if fid in functions_version_excludes:
            s = '#ifndef ' + functions_version_excludes[fid] + '\n' + s
            s += '\n#endif'
    else:
        s = '    //' + s + ' <--- UNIMPLEMENTED'
    return s + "\n"

def build_binds(processed_files):
    s = ''
    for processed_file in processed_files:
        s += "\n    // " + processed_file['filename'] + "\n"

        for function in processed_file['functions']:
            s += build_bind(function)
    return s

def build_includes():
    s = ''
    for f in functions_files:
        if not f.endswith('.h'):
            continue
        s += '#include "%s"\n' % f
    return s

############################################################################

def process_function(fname, line, description):
    if not allowed_identifier(functions_whitelist, functions_blacklist, fname, line):
        return None

    function = {}

    line = line.strip()
    function['line'] = line
    function['description'] = description  # use the specific description passed in

    line = line.replace('UNUSED', '')

    match = re.search(r'[a-zA-Z0-9_]+\(', line)
    function['type'] = normalize_type(line[0:match.span()[0]])
    function['identifier'] = match.group()[0:-1]

    function['params'] = []
    params_str = line.split('(', 1)[1].rsplit(')', 1)[0].strip()
    if len(params_str) == 0 or params_str == 'void':
        pass
    else:
        param_index = 0
        last_param_optional = None
        for param_str in params_str.split(','):
            param = {}
            param_str = param_str.strip()

            for param_keyword in parameter_keywords:
                keyword_index = param_str.find(param_keyword + ' ')
                if keyword_index != -1:
                    param[param_keyword] = True
                    param_str = (param_str[:keyword_index] + param_str[keyword_index+len(param_keyword)+1:]).strip()

            if param_str.endswith('*') or ' ' not in param_str:
                param['type'] = normalize_type(param_str)
                param['identifier'] = 'arg%d' % param_index
            else:
                match = re.search(r'[a-zA-Z0-9_\[\]]+$', param_str)
                if match == None:
                    return None
                param['type'] = normalize_type(param_str[0:match.span()[0]])
                param['identifier'] = match.group()

            if 'OPTIONAL' in param:
                last_param_optional = param['identifier']
            elif 'RET' not in param and last_param_optional is not None:
                print(f"REJECTED: {function['identifier']} -> mandatory parameter `{param['identifier']}` is following optional parameter `{last_param_optional}`")
                return None

            # override Vec3s/f
            if param['identifier'] == 'pos':
                if param['type'].replace(' ', '') == 'f32*':
                    param['type'] = 'Vec3f'
                if param['type'].replace(' ', '') == 's16*':
                    param['type'] = 'Vec3s'

            # remember lua function params
            lf_key = fname + '::' + function['identifier'] + '::' + param['identifier']
            if param['type'] == 'LuaFunction' and lf_key in functions_params_types:
                param['lua_function_params'] = functions_params_types[lf_key]

            function['params'].append(param)
            param_index += 1

    return function

def process_functions(fname, file_str, extracted_descriptions):
    functions = []
    overload_funcs = {}
    for line in file_str.splitlines():
        overload = None
        line = line.strip()
        if line.startswith(cobject_overload_identifier):
            line = line.split()
            overload = line[1]
            line = ' '.join(line[2:])
        if reject_line(line):
            global rejects
            rejects += line + '\n'
            continue
        description = extracted_descriptions.get(line, [""])
        fn = process_function(fname, line, description)
        if fn is None: continue

        if overload is not None:
            overload_func = overload_funcs.get(overload)
            if overload_func is None:
                overload_func = overload_funcs[overload] = { 'identifier': overload, 'overload': [] }
                functions.append(overload_func)
            overload_func['overload'].append(fn)
        else:
            functions.append(fn)
    return functions

def process_file(fname):
    processed_file = {}
    processed_file['filename'] = fname.replace('\\', '/').split('/')[-1]
    processed_file['extern'] = fname.endswith('.c')

    extracted_str, extracted_descriptions = extract_functions(fname)
    processed_file['functions'] = process_functions(fname, extracted_str, extracted_descriptions)

    return processed_file

def process_files():
    processed_files = []
    files = sorted(functions_files, key=lambda d: d.split('/')[-1])
    for f in files:
        processed_files.append(process_file(f))
    return processed_files


############################################################################

fuzz_from = ""
fuzz_to = ""
fuzz_functions = ""

def output_fuzz_function(fname, function):
    first = True
    comment = ' -- '
    fid = function['identifier']

    line = '        function() return ' + fid + '('

    for param in function['params']:
        if first:
            first = False
        else:
            line += ', '
            comment += ', '
        pid = param['identifier']
        ptype = param['type']
        ptype, plink = translate_type_to_lua(ptype)

        if '(' in pid or '[' in pid or ']' in pid:
            continue

        line += translate_type_to_rnd(ptype)

        comment += ptype

    line += ') end,\n'
    #if len(line) >= 80:
    #    line = line + '\n        ' + comment + '\n'
    #else:
    #    line = line.ljust(80) + comment + '\n'

    global fuzz_functions
    fuzz_functions += line

def output_fuzz_file():
    global fuzz_functions
    with open(fuzz_from) as f:
        file_str = f.read()
    with open(fuzz_to, 'w', encoding='utf-8', newline='\n') as f:
        f.write(file_str.replace('-- $[FUNCS]', fuzz_functions))

############################################################################

manual_function_types = {
    'boolean':  '`bool`',
    'integer':  '`integer`',
    'number':   '`number`',
    'string':   '`string`',
    'table':    '`table`',
    'function': '`function`',
    'fun':      '`function`',
    'nil':      '`nil`',
    'any':      '`any`',
}

def read_single_type(buffer: str):
    ptype = ''
    depth = 0
    for i, c in enumerate(buffer):
        if c in '<(':
            depth += 1
        elif c in '>)':
            depth = max(depth - 1, 0)
        elif depth == 0:
            if c.isalnum() or c in '_[]':
                ptype += c
            else:
                return ptype, buffer[i:]
    return ptype, ''

def read_type_and_description(line: str):
    ptype = ''
    pdesc = ''
    is_param = True
    is_function_return = False

    while line:
        stype, line = read_single_type(line)
        if stype:
            if is_function_return:
                is_function_return = False
                continue
            if is_param:
                ptype += stype
                is_param = False
            else:
                pdesc = stype + line
                break
        elif line[0] == ':':
            is_function_return = True
            line = line[1:]
        elif line[0] == ',':
            is_function_return = True
            line = line[1:]
        elif line[0] == '|':
            ptype += '|'
            is_param = True
            line = line[1:]
        else:
            line = line[1:]

    return ptype.strip(), pdesc.strip()

def get_empty_function_definition():
    return {
        'identifier': '',
        'params': [],
        'returns': [],
        'description': [],
        'lua_example': [],
    }

def read_manually_written_functions(in_filename):
    with open(in_filename, 'r', encoding='utf-8', newline='\n') as f:
        lines = f.readlines()

    classes = []
    functions = []
    function = get_empty_function_definition()
    text_type = None
    for line in lines:

        # Custom table
        if line.startswith('--- @class'):
            tokens = [token for token in line.split() if token]
            classes.append(tokens[2])

        # Parameter
        if line.startswith('--- @param'):
            tokens = [token for token in line.split() if token]
            ptype, pdesc = read_type_and_description(' '.join(tokens[3:]))
            function['params'].append({
                'name': tokens[2].strip('?'),
                'type': ptype,
                'desc': pdesc,
                'is_vararg': False,
            })
            text_type = 'description'

        # Vararg parameter
        elif line.startswith('--- @vararg'):
            tokens = [token for token in line.split() if token]
            ptype, pdesc = read_type_and_description(' '.join(tokens[2:]))
            ptokens = pdesc.split() or ['']
            function['params'].append({
                'name': ptokens[0],
                'type': ptype,
                'desc': " ".join(ptokens[1:]),
                'is_vararg': True,
            })
            text_type = 'description'

        # Return value
        elif line.startswith('--- @return'):
            tokens = [token for token in line.split() if token]
            rtype, rdesc = read_type_and_description(' '.join(tokens[2:]))
            rtokens = rdesc.split() or ['']
            function['returns'].append({
                'name': rtokens[0],
                'type': rtype,
                'desc': " ".join(rtokens[1:]),
            })
            text_type = 'description'

        # End of function doc
        elif line.startswith('function '):
            tokens = [token for token in line.replace('(', ' ').split() if token]
            function['identifier'] = tokens[1]
            function['description'] = '\n'.join(function['description']).strip('\n').split('\n')
            function['lua_example'] = '\n'.join(function['lua_example']).strip('\n').split('\n')
            functions.append(function)
            function = get_empty_function_definition()
            text_type = None

        # Lua example in doc
        elif line.startswith('--- ### Lua Example'):
            text_type = 'lua_example'

        # Doc
        elif line.startswith('---') and text_type:
            line_desc = line[4:].rstrip()
            function[text_type].append(line_desc)

        # Anything else
        else:
            function = get_empty_function_definition()
            text_type = None

    return functions, classes

enums_file = ''
def function_type_is_enum(ptype):
    global enums_file
    if not enums_file:
        with open(get_path(enums_filename), 'r', encoding='utf-8', newline='\n') as f:
            enums_file = f.read()

    return '@alias {ptype}\n'.format(ptype=ptype) in enums_file

def get_manual_function_type(ptype: str, classes, docs_dir):
    types = ptype.split('|')
    converted_types = []
    for t in types:
        type_str = ''
        if t.endswith('[]'):
            type_str += '`table` of '
            t = t[:-2]
        if t in manual_function_types:
            type_str += manual_function_types[t]
        elif t in classes:
            type_str += manual_function_types['table']
        elif t == 'SyncTable':
            type_str += '[SyncTable]({docs_dir}/globals.md#gGlobalSyncTable)'.format(docs_dir=docs_dir)
        elif function_type_is_enum(t):
            type_str += '[enum {t}]({docs_dir}/constants.md#enum-{t})'.format(t=t, docs_dir=docs_dir)
        else:
            type_str += '[{t}]({docs_dir}/structs.md#{t})'.format(t=t, docs_dir=docs_dir)
        converted_types.append(type_str)

    return ' \\| '.join(converted_types)

def doc_manual_function(function, classes, docs_dir, include_param_desc):
    fid = function['identifier']
    s = '\n## [%s](#%s)\n' % (fid, fid)

    s += '\n### Description\n'
    for line in function['description']:
        s +=  f'{line}\n'

    s += '\n### Lua Example\n'
    for line in function['lua_example']:
        s +=  f'{line}\n'

    s += '\n### Parameters\n'
    if function['params']:
        if include_param_desc:
            s += '| Field | Type | Description |\n'
            s += '| ----- | ---- | ----------- |\n'
        else:
            s += '| Field | Type |\n'
            s += '| ----- | ---- |\n'
        for param in function['params']:
            pname = param['name']
            ptype = param['type']
            is_vararg = param['is_vararg']
            if include_param_desc:
                s += '| %s%s | %s | %s |\n' % (pname, ('...' if is_vararg else ''), get_manual_function_type(ptype, classes, docs_dir), param.get('desc', ''))
            else:
                s += '| %s%s | %s |\n' % (pname, ('...' if is_vararg else ''), get_manual_function_type(ptype, classes, docs_dir))
    else:
        s += '- None\n'

    s += '\n### Returns\n'
    if function['returns']:
        for ret in function['returns']:
            rname = ret['name']
            rtype = ret['type']
            if rname:
                s += '- %s: %s\n' % (rname, get_manual_function_type(rtype, classes, docs_dir))
            else:
                s += '- %s\n' % get_manual_function_type(rtype, classes, docs_dir)
    else:
        s += '- None\n'

    s += '\n[:arrow_up_small:](#)\n\n<br />\n'

    return s

def doc_page_link(page_num):
    if page_num == 1:
        return 'functions.md'
    else:
        return 'functions-%d.md' % page_num

def doc_function_index(processed_files, manual_functions):
    s = '# Supported Functions\n'

    if manual_functions:
        s += '\n- manually written functions\n'
        for function in manual_functions:
            s += '   - [{identifier}](#{identifier})\n'.format(identifier=function['identifier'])
        s += '\n<br />\n\n'

    for processed_file in processed_files:
        page_num = processed_file['page_num']
        s += '- %s\n' % processed_file['filename']
        for function in processed_file['functions']:
            if not function['implemented']:
                continue
            if not allowed_identifier(None, functions_hidden, processed_file['filename'], function['identifier']):
                continue

            s += '   - [%s](%s#%s)\n' % (function['identifier'], doc_page_link(page_num), function['identifier'])
        s += '\n<br />\n\n'

    return s

def doc_lua_func_param(param):
    s = 'LuaFunction('

    lfp = param['lua_function_params']
    first_lfp = True

    for lfp_type in lfp:
        if not first_lfp:
            lfp_type += ', '
        first_lfp = False

        lfp_type, lfp_link = translate_type_to_lua(lfp_type)

        if lfp_link:
            s += '[%s](%s)' % (lfp_type, lfp_link)
        else:
            s += lfp_type

    s += ')'
    return s

def doc_overloaded_function(fname, function):
    s = ''
    overload = function['overload']
    skip, cont = 0, 0
    for i, func in enumerate(overload):
        for line in doc_function(fname, func).splitlines():
            if skip > 0: skip -= 1; continue
            if cont > 0: cont -= 1
            else: line = line.replace(func['identifier'], function['identifier'])

            if "C Prototype" in line: cont = 1
            if i+1 != len(overload) and "(#)" in line:
                s += "---"
                skip = 2
                break

            s += line + '\n'

    return s

def doc_function(fname, function):
    if function.get('overload'):
        return doc_overloaded_function(fname, function)

    if not function['implemented']:
        return ''

    # debug print out lua nuke functions
    if len(sys.argv) >= 2 and sys.argv[1] == 'fuzz':
        output_fuzz_function(fname, function)

    if not allowed_identifier(None, functions_hidden, fname, function['identifier']):
        return ''

    fid = function['identifier']
    s = '\n## [%s](#%s)\n' % (fid, fid)

    description = function.get('description', [""])

    rtype, rlink = translate_type_to_lua(function['type'])
    param_str = ', '.join([x['identifier'] for x in function['params'] if 'RET' not in x])

    if description[0] != "":
        s += '\n### Description\n'
        for line in description:
            s +=  f'{line}\n'

    s += "\n### Lua Example\n"
    rvalues = []
    if rtype is not None:
        rid = rtype.replace('`', '').split(' ')[0]
        rid = rid[0].lower() + rid[1:]
        rvalues.append((rid + 'Value', rtype, rlink))

    fparams, freturns = split_function_parameters_and_returns(function)
    for param in freturns:
        ptype, plink = translate_type_to_lua(param['rtype'])
        rvalues.append((param['identifier'], ptype, plink))

    if rvalues:
        s += "`local %s = %s(%s)`\n" % (", ".join([id for id, _, _ in rvalues]), fid, param_str)
    else:
        s += "`%s(%s)`\n" % (fid, param_str)

    s += '\n### Parameters\n'
    if len(fparams) > 0:
        s += '| Field | Type |\n'
        s += '| ----- | ---- |\n'
        for param in fparams:
            pid = param['identifier']
            ptype = param['type']
            ptype, plink = translate_type_to_lua(ptype)

            # build lua function params
            if param['type'] == 'LuaFunction' and 'lua_function_params' in param:
                ptype = doc_lua_func_param(param)

            if plink:
                s += '| %s | [%s](%s) |\n'  % (pid, ptype, plink)
                continue

            s += '| %s | %s |\n'  % (pid, ptype)

    else:
        s += '- None\n'

    s += '\n### Returns\n'
    if len(rvalues) > 0:
        for _, ptype, plink in rvalues:
            if plink:
                s += '- [%s](%s)\n' % (ptype, plink)
            else:
                s += '- %s\n' % ptype
    else:
        s += '- None\n'


    s += '\n### C Prototype\n'
    s += '`%s`\n' % function['line'].strip()

    s += '\n[:arrow_up_small:](#)\n\n<br />\n'

    return s

def doc_functions(fname, functions):
    s = ''
    for function in functions:
        s += doc_function(fname, function)
    return s

def doc_files(processed_files):
    pages = {}
    page_num = 1
    page_len_limit = 150000
    extra_space = 25000

    s = '## [:rewind: Lua Reference](lua.md)\n\n'
    s += '---\n\n$[FUNCTION_NAV_HERE]\n\n---\n\n'
    s += '$[FUNCTION_INDEX_HERE]'

    manual_functions, classes = read_manually_written_functions(get_path(manually_written_functions_filename))
    if manual_functions:
        s += '\n---\n# manually written functions\n'
        for function in manual_functions:
            s += doc_manual_function(function, classes, ".", False)

    for processed_file in processed_files:
        s_file  = '\n---'
        s_file += '\n# functions from %s\n\n<br />\n\n' % processed_file['filename']
        s_file += doc_functions(processed_file['filename'], processed_file['functions'])

        if len(s) + len(s_file) + extra_space > page_len_limit:
            s += '---\n\n$[FUNCTION_NAV_HERE]\n\n'
            pages[page_num] = s
            s = '## [:rewind: Lua Functions](functions.md)\n\n'
            s += '---\n\n$[FUNCTION_NAV_HERE]\n\n'
            page_num += 1
            extra_space = 0

        s += s_file
        processed_file['page_num'] = page_num

    s += '\n---\n\n$[FUNCTION_NAV_HERE]\n\n'
    pages[page_num] = s

    for pnum in pages:
        buffer = pages[pnum]
        page_name = ''
        if pnum == 1:
            buffer = buffer.replace('$[FUNCTION_INDEX_HERE]', doc_function_index(processed_files, manual_functions))
            page_name = ''
        else:
            page_name = '-%d' % pnum

        # build up nav
        function_nav = ''
        if (pnum - 1) in pages:
            function_nav += '[< prev](%s) | ' % doc_page_link(pnum - 1)
        for pnum_nav in pages:
            if pnum_nav == pnum:
                function_nav += '%d' % pnum_nav
            else:
                function_nav += '[%d](%s)' % (pnum_nav, doc_page_link(pnum_nav))

            if (pnum_nav + 1) in pages:
                function_nav += ' | '
        if (pnum + 1) in pages:
            function_nav += ' | [next >](%s)' % doc_page_link(pnum + 1)

        buffer = buffer.replace('$[FUNCTION_NAV_HERE', function_nav)

        with open(get_path(out_filename_docs % page_name), 'w', encoding='utf-8', newline='\n') as out:
            out.write(buffer)

############################################################################

def_pointers = []

def def_overloaded_function(fname, function):
    s = ''
    for func in function['overload']:
        s += def_function(fname, func).replace(func['identifier'], function['identifier'])

    return s

def def_function(fname, function):
    if function.get('overload') is not None:
        return def_overloaded_function(fname, function)

    s = ''
    if not function['implemented']:
        return ''

    fid = function['identifier']
    if not allowed_identifier(None, functions_hidden, fname, fid):
        return ''

    rtype, _ = translate_type_to_lua(function['type'])
    param_str = ', '.join([x['identifier'] for x in function['params'] if 'RET' not in x])

    rtypes = []
    if rtype is not None:
        rtypes.append((rtype, None))

    fparams, freturns = split_function_parameters_and_returns(function)
    for param in freturns:
        rtype, _ = translate_type_to_lua(param['rtype'])
        rid = param['identifier']
        rtypes.append((rtype, rid))

    if function['description'][0].startswith("[DEPRECATED"):
        s += "--- @deprecated\n"

    for param in fparams:
        pid = param['identifier']
        ptype = param['type']
        ptype, _ = translate_type_to_lua(ptype)

        ptype = translate_to_def(ptype)
        if ptype.startswith('Pointer_') and ptype not in def_pointers:
            def_pointers.append(ptype)

        s += '--- @param %s%s %s\n' % (pid, ('?' if 'OPTIONAL' in param else ''), ptype)

    for rtype, rid in rtypes:
        rtype = translate_to_def(rtype)
        if rtype.startswith('Pointer_') and rtype not in def_pointers:
            def_pointers.append(rtype)

        if rtype != "nil":
            s += ('--- @return %s' % rtype) + (' %s' % rid if rid else '') + '\n'

    if function['description'][0] != "":
        for n, line in enumerate(function['description']):
            s += "--- %s%s\n" % (line, "<br>" if n != len(function['description']) - 1 else "")
    s += "function %s(%s)\n    -- ...\nend\n\n" % (fid, param_str)

    return s


def def_files(processed_files):
    s = '-- AUTOGENERATED FOR CODE EDITORS --\n\n'
    for processed_file in processed_files:
        for function in processed_file['functions']:
            s += def_function(processed_file['filename'], function)

    for def_pointer in def_pointers:
        s += '--- @alias %s %s\n' % (def_pointer, def_pointer[8:])

    for vecp_type, vec_type in VECP_TYPES.items():
        s += '--- @alias %s %s\n' % (vecp_type, vec_type)

    with open(get_path(out_filename_defs), 'w', encoding='utf-8', newline='\n') as out:
        out.write(s)

############################################################################

def doc_hooks(in_filename, out_filename):
    hooks, classes = read_manually_written_functions(in_filename)

    s  = '## [:rewind: Lua Reference](../lua.md)\n\n'
    s += '# Hooks\n'
    s += 'Hooks are a way for the game to trigger Lua code, whereas the functions listed in [functions](../functions.md) allow Lua to trigger SM64 code.\n\n'

    if hooks:
        s += '# Supported Hooks\n'
        for hook in hooks:
            s += '- [{identifier}](#{identifier})\n'.format(identifier=hook['identifier'])
        s += '\n<br />\n'
        for hook in hooks:
            s += doc_manual_function(hook, classes, "..", True)

    with open(out_filename, 'w', encoding='utf-8', newline='\n') as out:
        out.write(s)

############################################################################

def main():
    processed_files = process_files()

    built_vec_types = build_vec_types()
    built_functions = build_functions(processed_files)
    built_binds = build_binds(processed_files)
    built_includes = build_includes()

    filename = get_path(out_filename)

    gen = template                                \
        .replace("$[TYPES]", built_vec_types)     \
        .replace("$[FUNCTIONS]", built_functions) \
        .replace("$[BINDS]", built_binds)         \
        .replace("$[INCLUDES]", built_includes)

    with open(filename, 'w', encoding='utf-8', newline='\n') as out:
        out.write(gen)

    if rejects != "":
        print(f"REJECTS:\n{rejects}")

    doc_files(processed_files)
    def_files(processed_files)

    doc_hooks(get_path(hooks_filename), get_path(out_filename_hooks))

    global total_functions
    print(f"Total functions: {total_functions}")
    global total_doc_functions
    print(f"Total documented functions: {total_doc_functions} ({round((total_doc_functions / total_functions) * 100, 2)}%)")

    if len(sys.argv) >= 2 and sys.argv[1] == 'fuzz':
        output_fuzz_file()

if __name__ == '__main__':
   main()
