#############
# CONSTANTS #
#############

# Autogen will look in these files for constants
constants_files = [
    "include/types.h",
    "include/sm64.h",
    "src/pc/lua/smlua_hooks.h",
    "src/game/area.h",
    "src/game/camera.h",
    "include/mario_animation_ids.h",
    "include/sounds.h",
    "src/game/characters.h",
    "src/pc/network/network.h",
    "src/pc/network/network_player.h",
    "include/PR/os_cont.h",
    "src/game/interaction.c",
    "src/game/interaction.h",
    "src/pc/djui/djui_hud_utils.h",
    "src/pc/controller/controller_mouse.h",
    "include/behavior_table.h",
    "src/pc/lua/utils/smlua_model_utils.h",
    "src/pc/lua/utils/smlua_misc_utils.h",
    "include/object_constants.h",
    "include/mario_geo_switch_case_ids.h",
    "src/game/object_list_processor.h",
    "src/engine/graph_node.h",
    "levels/level_defines.h",
    "levels/course_defines.h",
    "src/game/obj_behaviors.c",
    "src/game/save_file.h",
    "src/game/obj_behaviors_2.h",
    "include/dialog_ids.h",
    "include/seq_ids.h",
    "include/surface_terrains.h",
    "src/game/level_update.h",
    "src/pc/network/version.h",
    "include/geo_commands.h",
    "include/level_commands.h",
    "src/audio/external.h",
    "src/game/envfx_snow.h",
    "src/pc/mods/mod_storage.h",
    "src/pc/mods/mod_fs.h",
    "src/game/first_person_cam.h",
    "src/pc/djui/djui_console.h",
    "src/game/player_palette.h",
    "src/pc/network/lag_compensation.h",
    "src/pc/djui/djui_panel_menu.h",
    "src/engine/lighting_engine.h",
    "include/PR/gbi.h",
    "include/PR/gbi_extension.h",
    "src/pc/gfx/gfx_pc.h",
    "src/engine/surface_load.h",
    "src/pc/lua/utils/smlua_audio_utils.h",
]

# For each file, expose only these constants
constants_whitelist = { "__name__": "constants_whitelist",
    "include/geo_commands.h": [ "BACKGROUND" ],
    "include/level_commands.h": [ "WARP_CHECKPOINT", "WARP_NO_CHECKPOINT" ],
    "src/audio/external.h": [ "SEQ_PLAYER", "DS_" ],
    "src/pc/lua/utils/smlua_audio_utils.h": [ "MA_" ],
    "src/pc/mods/mod_storage.h": [ "MAX_KEYS", "MAX_KEY_VALUE_LENGTH" ],
    "include/PR/gbi.h": [
        "^G_NOOP$",
        "^G_SETOTHERMODE_H$",
        "^G_SETOTHERMODE_L$",
        "^G_ENDDL$",
        "^G_DL$",
        "^G_MOVEMEM$",
        "^G_MOVEWORD$",
        "^G_MTX$",
        "^G_GEOMETRYMODE$",
        "^G_POPMTX$",
        "^G_TEXTURE$",
        "^G_COPYMEM$",
        "^G_VTX$",
        "^G_TRI1$",
        "^G_TRI2$",
        "^G_SETCIMG$",
        "^G_SETZIMG$",
        "^G_SETTIMG$",
        "^G_SETCOMBINE$",
        "^G_SETENVCOLOR$",
        "^G_SETPRIMCOLOR$",
        "^G_SETBLENDCOLOR$",
        "^G_SETFOGCOLOR$",
        "^G_SETFILLCOLOR$",
        "^G_FILLRECT$",
        "^G_SETTILE$",
        "^G_LOADTILE$",
        "^G_LOADBLOCK$",
        "^G_SETTILESIZE$",
        "^G_LOADTLUT$",
        "^G_SETSCISSOR$",
        "^G_TEXRECTFLIP$",
        "^G_TEXRECT$",
    ],
    "include/PR/gbi_extension.h": [
        "^G_VTX_EXT$",
        "^G_PPARTTOCOLOR$",
        "^G_SETENVRGB$",
        "^G_STATE_EXT$",
    ],
}

# For each file, do not expose these constants
constants_blacklist = { "__name__": "constants_blacklist",
    "*": [ "^MAXCONTROLLERS$", "^AREA_[^T].*", "^AREA_T[HTO]", "^CONT_ERR.*", "^READ_MASK$", "^SIGN_RANGE$" ],
    "include/sm64.h": [ "END_DEMO" ],
    "include/types.h": [ "GRAPH_NODE_GUARD" ],
    "src/audio/external.h": [ "DS_DIFF" ],
    "src/game/save_file.h": [ "EEPROM_SIZE" ],
    "src/game/obj_behaviors.c": [ "^o$" ],
    "src/pc/djui/djui_console.h": [ "CONSOLE_MAX_TMP_BUFFER" ],
    "src/pc/lua/smlua_hooks.h": [ "^LUA_BEHAVIOR_.*", "MAX_HOOKED_.*", "^HOOK_RETURN_.*", "^ACTION_HOOK_.*", "^MOD_MENU_ELEMENT_.*" ],
    "src/pc/djui/djui_panel_menu.h": [ "RAINBOW_TEXT_LEN" ],
    "src/pc/mods/mod_fs.h": [ "INT_TYPE_MAX", "FLOAT_TYPE_MAX", "FILE_SEEK_MAX" ],
    "src/engine/surface_load.h": [ "NUM_CELLS" ],
    "src/pc/network/version.h": [ "VERSION_OFFSET" ],
}

# For each file, expose these constants, but hide them from the documentation or VSCode autocomplete
constants_hidden = { "__name__": "constants_hidden",
    "interaction.h": [ "INTERACT_UNKNOWN_08" ],
}

#############
# FUNCTIONS #
#############

# Autogen will look in these files for functions
functions_files = [
    "src/audio/external.h",
    "src/engine/math_util.h",
    "src/engine/math_util.inl",
    "src/engine/math_util_vec3f.inl",
    "src/engine/math_util_vec3i.inl",
    "src/engine/math_util_vec3s.inl",
    "src/engine/math_util_mat4.inl",
    "src/engine/surface_collision.h",
    "src/engine/surface_load.h",
    "src/game/camera.h",
    "src/game/characters.h",
    "src/game/mario_actions_airborne.c",
    "src/game/mario_actions_automatic.c",
    "src/game/mario_actions_cutscene.c",
    "src/game/mario_actions_moving.c",
    "src/game/mario_actions_object.c",
    "src/game/mario_actions_stationary.c",
    "src/game/mario_actions_submerged.c",
    "src/game/mario_step.h",
    "src/game/mario.h",
    "src/game/rumble_init.h",
    "src/pc/djui/djui_popup.h",
    "src/pc/network/network_utils.h",
    "src/pc/djui/djui_console.h",
    "src/pc/djui/djui_chat_message.h",
    "src/pc/djui/djui_language.h",
    "src/game/interaction.h",
    "src/game/level_info.h",
    "src/game/save_file.h",
    "src/game/sound_init.h",
    "src/pc/djui/djui_hud_utils.h",
    "src/pc/djui/djui_panel_menu.h",
    "src/pc/network/network_player.h",
    "src/pc/network/lag_compensation.h",
    "include/behavior_table.h",
    "src/pc/lua/utils/smlua_obj_utils.h",
    "src/pc/lua/utils/smlua_misc_utils.h",
    "src/pc/lua/utils/smlua_camera_utils.h",
    "src/pc/lua/utils/smlua_gfx_utils.h",
    "src/pc/lua/utils/smlua_collision_utils.h",
    "src/pc/lua/utils/smlua_model_utils.h",
    "src/pc/lua/utils/smlua_text_utils.h",
    "src/pc/lua/utils/smlua_audio_utils.h",
    "src/pc/lua/utils/smlua_level_utils.h",
    "src/pc/lua/utils/smlua_anim_utils.h",
    "src/pc/lua/utils/smlua_deprecated.h",
    "src/game/object_helpers.c",
    "src/game/obj_behaviors.c",
    "src/game/obj_behaviors_2.c",
    "src/game/platform_displacement.h",
    "src/game/spawn_sound.h",
    "src/game/object_list_processor.h",
    "src/game/behavior_actions.h",
    "src/game/mario_misc.h",
    "src/pc/mods/mod_storage.h",
    "src/pc/mods/mod_fs.h",
    "src/pc/utils/misc.h",
    "src/game/level_update.h",
    "src/game/area.h",
    "src/engine/level_script.h",
    "src/game/ingame_menu.h",
    "src/game/first_person_cam.h",
    "src/engine/behavior_script.h",
    "src/audio/seqplayer.h",
    "src/engine/lighting_engine.h",
    "src/pc/network/sync_object.h",
    "src/audio/load.h",
    "src/pc/djui/djui_gfx.h",
]

# For each file, expose only these functions
functions_whitelist = { "__name__": "functions_whitelist",
    "src/audio/external.h":                 [ " play_", "fade", "current_background", "stop_", "sound_banks", "drop_queued_background_music", "set_sound_moving_speed", "background_music_default_volume", "get_sound_pan", "sound_get_level_intensity", "set_audio_muted" ],
    "src/game/rumble_init.h":               [ "queue_rumble_", "reset_rumble_", "cancel_rumble", "is_rumble_finished_and_queue_empty" ],
    "src/pc/djui/djui_popup.h":             [ "create" ],
    "src/pc/djui/djui_language.h":          [ "djui_language_get" ],
    "src/pc/djui/djui_panel_menu.h":        [ "djui_menu_get_rainbow_string_color" ],
    "src/game/save_file.h":                 [ "get_level_", "save_file_get_", "save_file_set_flags", "save_file_clear_flags", "save_file_reload", "save_file_erase_current_backup_save", "save_file_set_star_flags", "save_file_is_cannon_unlocked", "save_file_set_cannon_unlocked", "touch_coin_score_age", "save_file_set_course_coin_score", "save_file_do_save", "save_file_remove_star_flags", "save_file_erase" ],
    "src/pc/lua/utils/smlua_model_utils.h": [ "smlua_model_util_get_id" ],
    "src/game/object_list_processor.h":     [ "set_object_respawn_info_bits" ],
    "src/game/platform_displacement.h":     [ "apply_platform_displacement" ],
    "src/game/mario_misc.h":                [ "bhv_toad.*", "bhv_unlock_door.*", "geo_get_.*" ],
    "src/game/level_update.h":              [ "level_trigger_warp", "get_painting_warp_node", "initiate_warp", "initiate_painting_warp", "warp_special", "lvl_set_current_level", "level_control_timer_running", "pressed_pause", "fade_into_special_warp", "get_instant_warp" ],
    "src/game/area.h":                      [ "get_mario_spawn_type", "area_get_warp_node", "area_get_any_warp_node", "play_transition" ],
    "src/engine/level_script.h":            [ "area_create_warp_node" ],
    "src/game/ingame_menu.h":               [ "set_min_dialog_width", "set_dialog_override_pos", "reset_dialog_override_pos", "set_dialog_override_color", "reset_dialog_override_color", "set_menu_mode", "create_dialog_box", "create_dialog_box_with_var", "create_dialog_inverted_box", "create_dialog_box_with_response", "reset_dialog_render_state", "set_dialog_box_state", "handle_special_dialog_text" ],
    "src/audio/seqplayer.h":                [ "sequence_player_set_tempo", "sequence_player_set_tempo_acc", "sequence_player_set_transposition", "sequence_player_get_tempo", "sequence_player_get_tempo_acc", "sequence_player_get_transposition", "sequence_player_get_volume", "sequence_player_get_fade_volume", "sequence_player_get_mute_volume_scale" ],
    "src/pc/network/sync_object.h":         [ "sync_object_is_initialized", "sync_object_is_owned_locally", "sync_object_get_object" ],
    "src/audio/load.h":                     [ "set_sound_bank_override" ],
    "src/pc/djui/djui_gfx.h":               [ "djui_gfx_get_scale" ],
}

# For each file, do not expose these functions
functions_blacklist = { "__name__": "functions_blacklist",
    "src/audio/external.h":                     [ " func_" ],
    "src/engine/surface_load.h":                [ "load_area_terrain", "alloc_surface_pools", "clear_dynamic_surfaces", "get_area_terrain_size", "alloc_surface", "add_surface", "remove_surface_from_partition", "delete_surface", "swap_and_pop_surface_pool", "add_surface_without_hook" ],
    "src/engine/surface_collision.h":           [ " debug_", "f32_find_wall_collision" ],
    "src/game/mario_actions_airborne.c":        [ "^[us]32 act_.*" ],
    "src/game/mario_actions_automatic.c":       [ "^[us]32 act_.*" ],
    "src/game/mario_actions_cutscene.c":        [ "^[us]32 act_.*", " geo_", "spawn_obj", "print_displaying_credits_entry" ],
    "src/game/mario_actions_moving.c":          [ "^[us]32 act_.*" ],
    "src/game/mario_actions_object.c":          [ "^[us]32 act_.*" ],
    "src/game/mario_actions_stationary.c":      [ "^[us]32 act_.*", "mario_exit_palette_editor" ],
    "src/game/mario_actions_submerged.c":       [ "^[us]32 act_.*" ],
    "src/game/mario_step.h":                    [ " stub_mario_step", "transfer_bully_speed" ],
    "src/game/mario.h":                         [ " init_mario" ],
    "src/pc/djui/djui_console.h":               [ " djui_console_create", "djui_console_message_create", "djui_console_message_dequeue" ],
    "src/pc/djui/djui_chat_message.h":          [ "create_from" ],
    "src/pc/djui/djui_hud_utils.h":             [ "djui_hud_clear_interp_data" ],
    "src/game/interaction.h":                   [ "process_interaction", "_handle_" ],
    "src/game/sound_init.h":                    [ "_loop_", "thread4_", "set_sound_mode" ],
    "src/pc/network/network_utils.h":           [ "network_get_player_text_color[^_]" ],
    "src/pc/network/network_player.h":          [ "_init", "_connected[^_]", "_shutdown", "_disconnected", "_update", "construct_player_popup", "network_player_name_valid" ],
    "src/game/object_helpers.c":                [ "spawn_obj", "^bhv_", "geo_", "abs[fi]", "^bit_shift", "_debug$", "stub_", "_set_model", "cur_obj_set_direction_table", "cur_obj_progress_direction_table", "bit_shift_left" ],
    "src/game/obj_behaviors.c":                 [ "debug_", "geo_", "turn_obj_away_from_surface"],
    "src/game/obj_behaviors_2.c":               [ "wiggler_jumped_on_attack_handler", "huge_goomba_weakly_attacked" ],
    "src/game/spawn_sound.h":                   [ "exec_anim_sound_state", "calc_dist_to_volume_range" ],
    "src/game/level_info.h":                    [ "_name_table", "convert_string_" ],
    "src/pc/lua/utils/smlua_obj_utils.h":       [ "spawn_object_remember_field" ],
    "src/game/camera.h":                        [ "geo_", "update_camera", "init_camera", "stub_camera", "^reset_camera", "move_point_along_spline", "romhack_camera_init_settings", "romhack_camera_reset_settings" ],
    "src/game/behavior_actions.h":              [ "bhv_dust_smoke_loop", "bhv_init_room", "geo_" ],
    "src/pc/lua/utils/smlua_audio_utils.h":     [ "audio_custom_shutdown", "smlua_audio_custom_deinit", "audio_destroy_pending_copies", "audio_custom_update_volume" ],
    "src/pc/lua/utils/smlua_level_utils.h":     [ "smlua_level_util_reset" ],
    "src/pc/lua/utils/smlua_text_utils.h":      [ "smlua_text_utils_init", "smlua_text_utils_shutdown", "smlua_text_utils_dialog_get_unmodified"],
    "src/pc/lua/utils/smlua_anim_utils.h":      [ "smlua_anim_util_reset", "smlua_anim_util_register_animation" ],
    "src/pc/lua/utils/smlua_gfx_utils.h":       [ "gfx_allocate_internal", "vtx_allocate_internal", "gfx_get_length_no_sentinel" ],
    "src/pc/network/lag_compensation.h":        [ "lag_compensation_clear" ],
    "src/game/first_person_cam.h":              [ "first_person_update" ],
    "src/pc/lua/utils/smlua_collision_utils.h": [ "collision_find_surface_on_ray" ],
    "src/engine/behavior_script.h":             [ "stub_behavior_script_2", "cur_obj_update" ],
    "src/pc/mods/mod_storage.h":                [ "mod_storage_shutdown" ],
    "src/pc/mods/mod_fs.h":                     [ "mod_fs_read_file_from_uri", "mod_fs_shutdown" ],
    "src/pc/utils/misc.h":                      [ "str_.*", "file_get_line", "delta_interpolate_(normal|rgba|mtx)", "detect_and_skip_mtx_interpolation", "precise_delay_f64", "can_update_game", "update_game", "open_url", "open_folder" ],
    "src/engine/lighting_engine.h":             [ "le_calculate_vertex_lighting", "le_clear", "le_shutdown" ],
}

# For each file, expose these functions, but hide them from the documentation or VSCode autocomplete
functions_hidden = { "__name__": "functions_hidden",
    "smlua_deprecated.h": [ ".*" ],
    "network_player.h":   [ "network_player_get_palette_color_channel", "network_player_get_override_palette_color_channel" ],
}

# For each function, expose it except for the specified version
functions_version_excludes = {
    "bhv_play_music_track_when_touched_loop": "VERSION_JP",
    "play_knockback_sound": "VERSION_JP",
    "cur_obj_spawn_star_at_y_offset": "VERSION_JP",
}

# For each function parameter, specify its type
functions_params_types = {
    "src/pc/lua/utils/smlua_obj_utils.h::spawn_object_sync::objSetupFunction": [ "struct Object*" ],
}

###########
# STRUCTS #
###########

# Autogen will look in these files for structs
structs_files = [
    "include/types.h",
    "src/game/area.h",
    "src/game/camera.h",
    "src/game/characters.h",
    "src/engine/surface_collision.h",
    "src/pc/network/network_player.h",
    "src/pc/djui/djui_hud_utils.h",
    "src/pc/djui/djui_theme.h",
    "src/game/object_helpers.h",
    "src/game/mario_step.h",
    "src/game/ingame_menu.h",
    "src/pc/lua/utils/smlua_anim_utils.h",
    "src/pc/lua/utils/smlua_misc_utils.h",
    "src/pc/lua/utils/smlua_camera_utils.h",
    "src/pc/lua/utils/smlua_collision_utils.h",
    "src/pc/lua/utils/smlua_level_utils.h",
    "src/game/spawn_sound.h",
    "src/pc/network/network.h",
    "src/game/hardcoded.h",
    "src/pc/mods/mod.h",
    "src/pc/mods/mod_fs.h",
    "src/pc/lua/utils/smlua_audio_utils.h",
    "src/game/paintings.h",
    "src/pc/djui/djui_types.h",
    "src/game/level_update.h",
    "src/game/first_person_cam.h",
    "src/game/player_palette.h",
    "src/engine/graph_node.h",
    "include/PR/gbi.h",
]

# For each file, expose only these structs
structs_whitelist = { "__name__": "structs_whitelist",
    "src/pc/network/network.h": [ "ServerSettings", "NametagsSettings" ],
    "src/pc/djui/djui_types.h": [ "DjuiColor" ],
    "src/game/level_update.h": [ "HudDisplay" ],
    "src/game/player_palette.h": [ "PlayerPalette" ],
    "src/game/ingame_menu.h" : [ "DialogEntry" ],
    "include/PR/gbi.h": [ "Gfx", "^Vtx$" ],
}

# For each file, do not expose these structs
structs_blacklist = { "__name__": "structs_blacklist",
}

# Ignore these structs entirely across all files
structs_excluded = [
    'AnimationTable',
    'BullyCollisionData',
    'CameraFOVStatus',
    'CameraStoredInfo',
    'CameraTrigger',
    'Cutscene',
    'CutsceneSplinePoint',
    'CutsceneVariable',
    'FloorGeometry',
    'GraphNode_802A45E4',
    'HandheldShakePoint',
    'LinearTransitionPoint',
    'MarioAnimDmaRelatedThing',
    'ModFile',
    'ModeTransitionInfo',
    'OffsetSizePair',
    'PaintingMeshVertex',
    'ParallelTrackingPoint',
    'PlayerGeometry',
    'SPTask',
    'SoundState',
    'TransitionInfo',
    'UnusedArea28',
    'VblankHandler',
    'Vtx_Interp',
    'WarpTransition',
    'WarpTransitionData',
]

# For each struct, expose only these fields
structs_fields_whitelist = { "__name__": "structs_fields_whitelist",
}

# For each struct, do not expose these fields
structs_fields_blacklist = { "__name__": "structs_fields_blacklist",
    "Mod": [ "files", "showedScriptWarning", "customBehaviorIndex", "customObjectFields" ],
    "Camera": [ "paletteEditorCapState" ],
    "NetworkPlayer": [ "gag", "moderator", "discordId", "rxPacketHash", "rxSeqIds" ],
    "GraphNode": [ "_guard1", "_guard2", "padding" ],
    "GraphNodeRoot": ["unk15", "views"],
    "GraphNodeMasterList": [ "listHeads", "listTails" ],
    "GraphNodeCullingRadius": [ "pad1E" ],
    "GraphNodeTranslation": [ "pad1E" ],
    "GraphNodeBackground": [ "unused" ],
    "GraphNodePerspective": [ "unused" ],
    "GraphNodeSwitchCase": [ "unused" ],
    "GraphNodeObject": [ "unk4C" ],
    "FnGraphNode": [ "luaTokenIndex" ],
    "Object": [ "firstSurface", "customFields", "bhvStack", "bhvStackIndex" ],
    "Animation": [ "unusedBoneCount" ],
    "ModAudio": [ "alive", "sound", "decoder", "buffer", "bufferSize", "copiesTail", "next", "prev", "parent" ],
    "Painting": [ "normalDisplayList", "textureMaps", "rippleDisplayList", "ripples" ],
    "DialogEntry": [ "str" ],
    "ModFsFile": [ "data", "capacity" ],
    "ModFs": [ "files" ],
}

# For each struct, expose these fields, but hide them from the documentation or VSCode autocomplete
structs_fields_hidden = { "__name__": "structs_fields_hidden",
    "NetworkPlayer": [ "paletteIndex", "overridePaletteIndex", "overridePaletteIndexLp" ],
    "ModAudio": [ "^file$", "relativePath" ], # compatibility band-aid
    "Camera": [ "filler31", "filler3C", "unusedVec1" ],
    "LakituState": [ "filler30", "filler3E", "filler72", "unusedVec1", "unusedVec2" ],
    "SpawnInfo": [ "unk18" ],
}

# For each struct field, expose it except for the specified version
structs_fields_version_excludes = {
    "oCameraLakituMusicPlayed": "VERSION_JP",
    "oCoinUnk1B0": "VERSION_JP",
}

# For each struct and field, specify its type
structs_fields_types = {
    "Surface": {
        "normal": "Vec3f"
    },
    "Object": {
        "oAnimations": "ObjectAnimPointer*"
    },
}

# For each struct, specify which fields are mutable (read and write)
structs_fields_mutable = {
    "NetworkPlayer": [ "overrideModelIndex", "overridePalette", "overridePaletteIndex" ],
}

# For each struct, specify which fields are immutable (read-only)
structs_fields_immutable = {
    "MarioState": [ "playerIndex", "controller", "marioObj", "marioBodyState", "statusForCamera", "area", "dialogId" ],
    "MarioAnimation": [ "animDmaTable" ],
    "ObjectNode": [ "next", "prev" ],
    "Character": [ "*" ],
    "NetworkPlayer": [ "*" ],
    "TextureInfo": [ "*" ],
    "Object": ["oSyncID", "coopFlags", "oChainChompSegments", "oWigglerSegments", "oHauntedChairUnk100", "oTTCTreadmillBigSurface", "oTTCTreadmillSmallSurface", "bhvStackIndex", "respawnInfoType", "numSurfaces", "bhvStack" ],
    "Surface": [ "poolType", "socId" ],
    "GlobalObjectAnimations": [ "*"],
    "SpawnParticlesInfo": [ "model" ],
    "WaterDropletParams": [ "model" ],
    "MarioBodyState": [ "updateTorsoTime", "updateHeadPosTime", "animPartsPos", "animPartsRot", "currAnimPart" ],
    "Area": [ "localAreaTimer", "nextSyncID", "objectSpawnInfos", "paintingWarpNodes", "warpNodes" ],
    "Mod": [ "*" ],
    "ModFile": [ "*" ],
    "Painting": [ "id", "imageCount", "textureType", "textureWidth", "textureHeight" ],
    "SpawnInfo": [ "syncID", "next", "unk18" ],
    "CustomLevelInfo": [ "next" ],
    "GraphNode": [ "children", "next", "parent", "prev", "type" ],
    "GraphNodeBackground": [ "prevCameraTimestamp", "unused" ],
    "GraphNodeCamera": [ "matrixPtrPrev", "prevTimestamp" ],
    "GraphNodeHeldObject": [ "prevShadowPosTimestamp" ],
    "GraphNodeObject": [ "angle", "animInfo", "cameraToObject", "node", "pos", "prevAngle", "prevPos", "prevScale", "prevScaleTimestamp", "prevShadowPos", "prevShadowPosTimestamp", "prevThrowMatrix", "prevThrowMatrixTimestamp", "prevTimestamp", "scale", "shadowPos", "sharedChild", "skipInterpolationTimestamp", "throwMatrixPrev", "unk4C", ],
    "GraphNodeObjectParent": [ "sharedChild" ],
    "GraphNodePerspective": [ "unused" ],
    "GraphNodeSwitchCase": [ "fnNode", "unused" ],
    "GraphNodeRoot": ["node", "areaIndex", "numViews"],
    "ObjectWarpNode": [ "next" ],
    "Animation": [ "*" ],
    "AnimationTable": [ "*" ],
    "Controller": [ "controllerData", "statusData" ],
    "FirstPersonCamera": [ "enabled" ],
    "ModAudio": [ "flags" ],
    "Gfx": [ "w0", "w1" ], # to protect from invalid type conversions
    "DialogEntry": [ "unused", "linesPerBox", "leftOffset", "width", "str", "text", "replaced"],
    "ModFsFile": [ "*" ],
    "ModFs": [ "*" ],
    "StaticObjectCollision": [ "*" ],
}
