#define POSSIBLE_NUM_PLAYERS 4

#define GFX_SCREEN_WIDTH()  (((GFX_DIMENSIONS_ASPECT_RATIO * SCREEN_HEIGHT) / 2) * gSw)
#define GFX_SCREEN_HEIGHT() ((SCREEN_HEIGHT / 2) * gSh)
#define GFX_SCREEN_WIDTH_PLAYER()  (((GFX_DIMENSIONS_FROM_RIGHT_EDGE(0) + GFX_DIMENSIONS_FROM_LEFT_EDGE(0)) / 2) * gSw)
#define GFX_HALF_SCREEN_WIDTH()  (GFX_SCREEN_WIDTH()  / 2)
#define GFX_HALF_SCREEN_HEIGHT() (GFX_SCREEN_HEIGHT() / 2)
#define GFX_SCREEN_X() (GFX_SCREEN_WIDTH()  * gSx)
#define GFX_SCREEN_Y() (GFX_SCREEN_HEIGHT() * gSy)
