CREDIT_SUPPORTERS = {
    "Saul",
    "Ellie",
    "Lyrae",
    "Sophia",
    "maemae",
    "charity",
    "FunkyLion",
    "VioletArts",
    "Nope208",
    "Jack Black",
    "GRAND DAD",
    "Key's Artworks",
    "Kale!",
}