extern const GeoLayout ddd_area_1_geo[];
extern const GeoLayout ddd_area_1[];
extern const Collision ddd_area_1_collision[];
extern const MacroObject ddd_area_1_macro_objs[];
extern Lights1 ddd_dl_Material_003_f3d_lights;
extern Lights1 ddd_dl_Material_004_f3d_lights;
extern Lights1 ddd_dl_Material_005_f3d_lights;
extern u8 ddd_dl_big_bricks_blue_ci8[];
extern u8 ddd_dl_big_bricks_blue_ci8_pal_rgba16[];
extern u8 ddd_dl_tile_ci8[];
extern u8 ddd_dl_tile_ci8_pal_rgba16[];
extern u8 ddd_dl_dirt2_ci8[];
extern u8 ddd_dl_dirt2_ci8_pal_rgba16[];
extern Vtx ddd_dl_LevelGeo_mesh_layer_1_vtx_0[2299];
extern Gfx ddd_dl_LevelGeo_mesh_layer_1_tri_0[];
extern Vtx ddd_dl_LevelGeo_mesh_layer_1_vtx_1[74];
extern Gfx ddd_dl_LevelGeo_mesh_layer_1_tri_1[];
extern Vtx ddd_dl_LevelGeo_mesh_layer_1_vtx_2[765];
extern Gfx ddd_dl_LevelGeo_mesh_layer_1_tri_2[];
extern Gfx mat_ddd_dl_Material_003_f3d[];
extern Gfx mat_revert_ddd_dl_Material_003_f3d[];
extern Gfx mat_ddd_dl_Material_004_f3d[];
extern Gfx mat_revert_ddd_dl_Material_004_f3d[];
extern Gfx mat_ddd_dl_Material_005_f3d[];
extern Gfx mat_revert_ddd_dl_Material_005_f3d[];
extern Gfx ddd_dl_LevelGeo_mesh_layer_1[];
extern Gfx ddd_dl_material_revert_render_settings[];
