#include "levels/ddd/texture_include.inc.c"
#include "levels/ddd/area_1/collision.inc.c"
#include "levels/ddd/area_1/macro.inc.c"
#include "levels/ddd/area_1/spline.inc.c"
#include "levels/ddd/model.inc.c"
