extern const GeoLayout magnum_geo[];
extern Lights1 magnum_darkergray_lights;
extern Lights1 magnum_metal_lights;
extern u8 magnum_noise_i8[];
extern u8 magnum_plat_rgba16[];
extern Vtx magnum_Arm_mesh_layer_1_vtx_0[64];
extern Gfx magnum_Arm_mesh_layer_1_tri_0[];
extern Vtx magnum_Arm_mesh_layer_1_vtx_1[8];
extern Gfx magnum_Arm_mesh_layer_1_tri_1[];
extern Vtx magnum_Arm_mesh_layer_1_vtx_2[533];
extern Gfx magnum_Arm_mesh_layer_1_tri_2[];
extern Gfx mat_magnum_darkergray[];
extern Gfx mat_magnum_black_layer1[];
extern Gfx mat_revert_magnum_black_layer1[];
extern Gfx mat_magnum_metal[];
extern Gfx mat_revert_magnum_metal[];
extern Gfx magnum_Arm_mesh_layer_1[];
extern Gfx magnum_material_revert_render_settings[];
