#include "levels/canals/texture_include.inc.c"
#include "levels/canals/area_1/collision.inc.c"
#include "levels/canals/area_1/macro.inc.c"
#include "levels/canals/area_1/spline.inc.c"
#include "levels/canals/model.inc.c"
