@echo off

REM Opens MSYS2 shell.
C:\msys64\msys2_shell.cmd -mingw64 -here

REM Opens MSYS2 in cmd, However anything in this file will not execute after.
rem C:\msys64\usr\bin\bash.exe --login -i -here

REM Clean our previous build of the game.
rem make -C tools clean && make clean

REM Make our game.

REM ######################## US ########################

REM make VERSION=us COMPILER=gcc EXTERNAL_DATA=1 COMPARE=0 BETTERCAMERA=1 NODRAWINGDISTANCE=1 IMMEDIATELOAD=1 DEBUG=1 DEVELOPMENT=1 -j9 && gdb ./build/us_pc/sm64coopdx.exe

REM make VERSION=us COMPILER=clang EXTERNAL_DATA=1 COMPARE=0 BETTERCAMERA=1 NODRAWINGDISTANCE=1 IMMEDIATELOAD=1 DEBUG=1 DEVELOPMENT=0 -j9 && ./build/us_pc/sm64.us.f3dex2e.exe

REM make VERSION=us COMPILER=clang EXTERNAL_DATA=1 COMPARE=0 BETTERCAMERA=1 NODRAWINGDISTANCE=1 IMMEDIATELOAD=1 DEBUG=0 DEVELOPMENT=1 -j9 && ./build/us_pc/sm64.us.f3dex2e.exe

REM make VERSION=us COMPILER=clang EXTERNAL_DATA=1 COMPARE=0 BETTERCAMERA=1 NODRAWINGDISTANCE=1 IMMEDIATELOAD=1 DEBUG=0 DEVELOPMENT=0 -j9 && ./build/us_pc/sm64.us.f3dex2e.exe

REM #### US (D3D11) #####

REM make VERSION=us RENDER_API=D3D11 COMPILER=clang EXTERNAL_DATA=0 COMPARE=0 BETTERCAMERA=1 NODRAWINGDISTANCE=1 IMMEDIATELOAD=1 DEBUG=1 DEVELOPMENT=1 -j9 && gdb ./build/us_pc/sm64.us.f3dex2e.exe

REM make VERSION=us RENDER_API=D3D11 COMPILER=clang EXTERNAL_DATA=0 COMPARE=0 BETTERCAMERA=1 NODRAWINGDISTANCE=1 IMMEDIATELOAD=1 DEBUG=1 DEVELOPMENT=0 -j9 && ./build/us_pc/sm64.us.f3dex2e.exe

REM make VERSION=us RENDER_API=D3D11 COMPILER=clang EXTERNAL_DATA=0 COMPARE=0 BETTERCAMERA=1 NODRAWINGDISTANCE=1 IMMEDIATELOAD=1 DEBUG=0 DEVELOPMENT=1 -j9 && ./build/us_pc/sm64.us.f3dex2e.exe

REM make VERSION=us RENDER_API=D3D11 COMPILER=clang EXTERNAL_DATA=0 COMPARE=0 BETTERCAMERA=1 NODRAWINGDISTANCE=1 IMMEDIATELOAD=1 DEBUG=0 DEVELOPMENT=0 -j9 && ./build/us_pc/sm64.us.f3dex2e.exe


REM ######################## EU ########################

REM make VERSION=eu COMPILER=clang EXTERNAL_DATA=0 COMPARE=0 BETTERCAMERA=1 NODRAWINGDISTANCE=1 IMMEDIATELOAD=1 DEBUG=1 DEVELOPMENT=1 -j9 && gdb ./build/eu_pc/sm64.eu.f3dex2e.exe

REM make VERSION=eu COMPILER=clang EXTERNAL_DATA=0 COMPARE=0 BETTERCAMERA=1 NODRAWINGDISTANCE=1 IMMEDIATELOAD=1 DEBUG=1 DEVELOPMENT=0 -j9 && ./build/eu_pc/sm64.eu.f3dex2e.exe

REM make VERSION=eu COMPILER=clang EXTERNAL_DATA=0 COMPARE=0 BETTERCAMERA=1 NODRAWINGDISTANCE=1 IMMEDIATELOAD=1 DEBUG=0 DEVELOPMENT=1 -j9 && ./build/eu_pc/sm64.eu.f3dex2e.exe

REM make VERSION=eu COMPILER=clang EXTERNAL_DATA=0 COMPARE=0 BETTERCAMERA=1 NODRAWINGDISTANCE=1 IMMEDIATELOAD=1 DEBUG=0 DEVELOPMENT=0 -j9 && ./build/eu_pc/sm64.eu.f3dex2e.exe

REM #### EU (D3D11) ####

REM make VERSION=eu RENDER_API=D3D11 COMPILER=clang EXTERNAL_DATA=0 COMPARE=0 BETTERCAMERA=1 NODRAWINGDISTANCE=1 IMMEDIATELOAD=1 DEBUG=1 DEVELOPMENT=1 -j9 && gdb ./build/eu_pc/sm64.eu.f3dex2e.exe

REM make VERSION=eu RENDER_API=D3D11 COMPILER=clang EXTERNAL_DATA=0 COMPARE=0 BETTERCAMERA=1 NODRAWINGDISTANCE=1 IMMEDIATELOAD=1 DEBUG=1 DEVELOPMENT=0 -j9 && ./build/eu_pc/sm64.eu.f3dex2e.exe

REM make VERSION=eu RENDER_API=D3D11 COMPILER=clang EXTERNAL_DATA=0 COMPARE=0 BETTERCAMERA=1 NODRAWINGDISTANCE=1 IMMEDIATELOAD=1 DEBUG=0 DEVELOPMENT=1 -j9 && ./build/eu_pc/sm64.eu.f3dex2e.exe

REM make VERSION=eu RENDER_API=D3D11 COMPILER=clang EXTERNAL_DATA=0 COMPARE=0 BETTERCAMERA=1 NODRAWINGDISTANCE=1 IMMEDIATELOAD=1 DEBUG=0 DEVELOPMENT=0 -j9 && ./build/eu_pc/sm64.eu.f3dex2e.exe


REM ######################## JP ########################

REM make VERSION=jp COMPILER=clang EXTERNAL_DATA=0 COMPARE=0 BETTERCAMERA=1 NODRAWINGDISTANCE=1 IMMEDIATELOAD=1 DEBUG=1 DEVELOPMENT=1 -j9 && gdb ./build/jp_pc/sm64.jp.f3dex2e.exe

REM make VERSION=jp COMPILER=clang EXTERNAL_DATA=0 COMPARE=0 BETTERCAMERA=1 NODRAWINGDISTANCE=1 IMMEDIATELOAD=1 DEBUG=1 DEVELOPMENT=0 -j9 && ./build/jp_pc/sm64.jp.f3dex2e.exe

REM make VERSION=jp COMPILER=clang EXTERNAL_DATA=0 COMPARE=0 BETTERCAMERA=1 NODRAWINGDISTANCE=1 IMMEDIATELOAD=1 DEBUG=0 DEVELOPMENT=1 -j9 && ./build/jp_pc/sm64.jp.f3dex2e.exe

REM make VERSION=jp COMPILER=clang EXTERNAL_DATA=0 COMPARE=0 BETTERCAMERA=1 NODRAWINGDISTANCE=1 IMMEDIATELOAD=1 DEBUG=0 DEVELOPMENT=0 -j9 && ./build/jp_pc/sm64.jp.f3dex2e.exe

REM ##### JP (D3D11) #####

REM make VERSION=jp RENDER_API=D3D11 COMPILER=clang EXTERNAL_DATA=0 COMPARE=0 BETTERCAMERA=1 NODRAWINGDISTANCE=1 IMMEDIATELOAD=1 DEBUG=1 DEVELOPMENT=1 -j9 && gdb ./build/jp_pc/sm64.jp.f3dex2e.exe

REM make VERSION=jp RENDER_API=D3D11 COMPILER=clang EXTERNAL_DATA=0 COMPARE=0 BETTERCAMERA=1 NODRAWINGDISTANCE=1 IMMEDIATELOAD=1 DEBUG=1 DEVELOPMENT=0 -j9 && ./build/jp_pc/sm64.jp.f3dex2e.exe

REM make VERSION=jp RENDER_API=D3D11 COMPILER=clang EXTERNAL_DATA=0 COMPARE=0 BETTERCAMERA=1 NODRAWINGDISTANCE=1 IMMEDIATELOAD=1 DEBUG=0 DEVELOPMENT=1 -j9 && ./build/jp_pc/sm64.jp.f3dex2e.exe

REM make VERSION=jp RENDER_API=D3D11 COMPILER=clang EXTERNAL_DATA=0 COMPARE=0 BETTERCAMERA=1 NODRAWINGDISTANCE=1 IMMEDIATELOAD=1 DEBUG=0 DEVELOPMENT=0 -j9 && ./build/jp_pc/sm64.jp.f3dex2e.exe


REM ######################## SH ########################

REM make VERSION=sh COMPILER=clang EXTERNAL_DATA=0 COMPARE=0 BETTERCAMERA=1 NODRAWINGDISTANCE=1 IMMEDIATELOAD=1 DEBUG=1 DEVELOPMENT=1 -j9 && gdb ./build/sh_pc/sm64.sh.f3dex2e.exe

REM make VERSION=sh COMPILER=clang EXTERNAL_DATA=0 COMPARE=0 BETTERCAMERA=1 NODRAWINGDISTANCE=1 IMMEDIATELOAD=1 DEBUG=1 DEVELOPMENT=0 -j9 && ./build/sh_pc/sm64.sh.f3dex2e.exe

REM make VERSION=sh COMPILER=clang EXTERNAL_DATA=0 COMPARE=0 BETTERCAMERA=1 NODRAWINGDISTANCE=1 IMMEDIATELOAD=1 DEBUG=0 DEVELOPMENT=1 -j9 && ./build/sh_pc/sm64.sh.f3dex2e.exe

REM make VERSION=sh COMPILER=clang EXTERNAL_DATA=0 COMPARE=0 BETTERCAMERA=1 NODRAWINGDISTANCE=1 IMMEDIATELOAD=1 DEBUG=0 DEVELOPMENT=0 -j9 && ./build/sh_pc/sm64.sh.f3dex2e.exe

REM ##### SH (D3D11) #####

REM make VERSION=sh RENDER_API=D3D11 COMPILER=clang EXTERNAL_DATA=0 COMPARE=0 BETTERCAMERA=1 NODRAWINGDISTANCE=1 IMMEDIATELOAD=1 DEBUG=1 DEVELOPMENT=1 -j9 && gdb ./build/sh_pc/sm64.sh.f3dex2e.exe

REM make VERSION=sh RENDER_API=D3D11 COMPILER=clang EXTERNAL_DATA=0 COMPARE=0 BETTERCAMERA=1 NODRAWINGDISTANCE=1 IMMEDIATELOAD=1 DEBUG=1 DEVELOPMENT=0 -j9 && ./build/sh_pc/sm64.sh.f3dex2e.exe

REM make VERSION=sh RENDER_API=D3D11 COMPILER=clang EXTERNAL_DATA=0 COMPARE=0 BETTERCAMERA=1 NODRAWINGDISTANCE=1 IMMEDIATELOAD=1 DEBUG=0 DEVELOPMENT=1 -j9 && ./build/sh_pc/sm64.sh.f3dex2e.exe

REM make VERSION=sh RENDER_API=D3D11 COMPILER=clang EXTERNAL_DATA=0 COMPARE=0 BETTERCAMERA=1 NODRAWINGDISTANCE=1 IMMEDIATELOAD=1 DEBUG=0 DEVELOPMENT=0 -j9 && ./build/sh_pc/sm64.sh.f3dex2e.exe