#define SAMPLE_sfx_1_00_twirl_aifc 0x170 // build/us_pc/sound/samples/sfx_1/00_twirl.aifc
#define SAMPLE_sfx_1_01_brushing_aifc 0x860 // build/us_pc/sound/samples/sfx_1/01_brushing.aifc
#define SAMPLE_sfx_1_02_hand_touch_aifc 0x3130 // build/us_pc/sound/samples/sfx_1/02_hand_touch.aifc
#define SAMPLE_sfx_1_03_yoshi_aifc 0x3460 // build/us_pc/sound/samples/sfx_1/03_yoshi.aifc
#define SAMPLE_sfx_1_04_plop_aifc 0x4630 // build/us_pc/sound/samples/sfx_1/04_plop.aifc
#define SAMPLE_sfx_1_05_heavy_landing_aifc 0x57c0 // build/us_pc/sound/samples/sfx_1/05_heavy_landing.aifc
#define SAMPLE_sfx_terrain_00_step_default_aifc 0x7310 // build/us_pc/sound/samples/sfx_terrain/00_step_default.aifc
#define SAMPLE_sfx_terrain_01_step_grass_aifc 0x7370 // build/us_pc/sound/samples/sfx_terrain/01_step_grass.aifc
#define SAMPLE_sfx_terrain_02_step_stone_aifc 0x7620 // build/us_pc/sound/samples/sfx_terrain/02_step_stone.aifc
#define SAMPLE_sfx_terrain_03_step_spooky_aifc 0x7860 // build/us_pc/sound/samples/sfx_terrain/03_step_spooky.aifc
#define SAMPLE_sfx_terrain_04_step_snow_aifc 0x7ef0 // build/us_pc/sound/samples/sfx_terrain/04_step_snow.aifc
#define SAMPLE_sfx_terrain_05_step_ice_aifc 0x8570 // build/us_pc/sound/samples/sfx_terrain/05_step_ice.aifc
#define SAMPLE_sfx_terrain_06_step_metal_aifc 0x86d0 // build/us_pc/sound/samples/sfx_terrain/06_step_metal.aifc
#define SAMPLE_sfx_terrain_07_step_sand_aifc 0xa0b0 // build/us_pc/sound/samples/sfx_terrain/07_step_sand.aifc
#define SAMPLE_sfx_water_00_plunge_aifc 0xace0 // build/us_pc/sound/samples/sfx_water/00_plunge.aifc
#define SAMPLE_sfx_water_01_splash_aifc 0xe470 // build/us_pc/sound/samples/sfx_water/01_splash.aifc
#define SAMPLE_sfx_water_02_swim_aifc 0xf960 // build/us_pc/sound/samples/sfx_water/02_swim.aifc
#define SAMPLE_sfx_4_00_aifc 0x114f0 // build/us_pc/sound/samples/sfx_4/00.aifc
#define SAMPLE_sfx_4_01_aifc 0x13180 // build/us_pc/sound/samples/sfx_4/01.aifc
#define SAMPLE_sfx_4_02_aifc 0x14350 // build/us_pc/sound/samples/sfx_4/02.aifc
#define SAMPLE_sfx_4_03_aifc 0x15410 // build/us_pc/sound/samples/sfx_4/03.aifc
#define SAMPLE_sfx_4_04_aifc 0x168e0 // build/us_pc/sound/samples/sfx_4/04.aifc
#define SAMPLE_sfx_4_05_aifc 0x17390 // build/us_pc/sound/samples/sfx_4/05.aifc
#define SAMPLE_sfx_4_06_aifc 0x17ea0 // build/us_pc/sound/samples/sfx_4/06.aifc
#define SAMPLE_sfx_4_07_aifc 0x188f0 // build/us_pc/sound/samples/sfx_4/07.aifc
#define SAMPLE_sfx_4_08_aifc 0x19750 // build/us_pc/sound/samples/sfx_4/08.aifc
#define SAMPLE_sfx_4_09_aifc 0x1bfd0 // build/us_pc/sound/samples/sfx_4/09.aifc
#define SAMPLE_sfx_5_00_aifc 0x1c7a0 // build/us_pc/sound/samples/sfx_5/00.aifc
#define SAMPLE_sfx_5_01_aifc 0x1dd80 // build/us_pc/sound/samples/sfx_5/01.aifc
#define SAMPLE_sfx_5_02_aifc 0x1edb0 // build/us_pc/sound/samples/sfx_5/02.aifc
#define SAMPLE_sfx_5_03_aifc 0x21a30 // build/us_pc/sound/samples/sfx_5/03.aifc
#define SAMPLE_sfx_5_04_aifc 0x231f0 // build/us_pc/sound/samples/sfx_5/04.aifc
#define SAMPLE_sfx_5_05_aifc 0x243f0 // build/us_pc/sound/samples/sfx_5/05.aifc
#define SAMPLE_sfx_5_06_aifc 0x27b90 // build/us_pc/sound/samples/sfx_5/06.aifc
#define SAMPLE_sfx_5_07_aifc 0x28340 // build/us_pc/sound/samples/sfx_5/07.aifc
#define SAMPLE_sfx_5_08_aifc 0x2a6b0 // build/us_pc/sound/samples/sfx_5/08.aifc
#define SAMPLE_sfx_5_09_aifc 0x2b130 // build/us_pc/sound/samples/sfx_5/09.aifc
#define SAMPLE_sfx_5_0A_aifc 0x2b840 // build/us_pc/sound/samples/sfx_5/0A.aifc
#define SAMPLE_sfx_5_0B_aifc 0x2be10 // build/us_pc/sound/samples/sfx_5/0B.aifc
#define SAMPLE_sfx_5_0C_aifc 0x2ea20 // build/us_pc/sound/samples/sfx_5/0C.aifc
#define SAMPLE_sfx_5_0D_aifc 0x34330 // build/us_pc/sound/samples/sfx_5/0D.aifc
#define SAMPLE_sfx_5_0E_aifc 0x3c180 // build/us_pc/sound/samples/sfx_5/0E.aifc
#define SAMPLE_sfx_5_0F_aifc 0x3d1f0 // build/us_pc/sound/samples/sfx_5/0F.aifc
#define SAMPLE_sfx_5_10_aifc 0x3f6a0 // build/us_pc/sound/samples/sfx_5/10.aifc
#define SAMPLE_sfx_5_11_aifc 0x3fae0 // build/us_pc/sound/samples/sfx_5/11.aifc
#define SAMPLE_sfx_5_12_aifc 0x431d0 // build/us_pc/sound/samples/sfx_5/12.aifc
#define SAMPLE_sfx_5_13_aifc 0x43e60 // build/us_pc/sound/samples/sfx_5/13.aifc
#define SAMPLE_sfx_5_14_aifc 0x47730 // build/us_pc/sound/samples/sfx_5/14.aifc
#define SAMPLE_sfx_5_15_aifc 0x4a040 // build/us_pc/sound/samples/sfx_5/15.aifc
#define SAMPLE_sfx_5_16_aifc 0x4a810 // build/us_pc/sound/samples/sfx_5/16.aifc
#define SAMPLE_sfx_5_17_aifc 0x4b1c0 // build/us_pc/sound/samples/sfx_5/17.aifc
#define SAMPLE_sfx_5_18_aifc 0x4c120 // build/us_pc/sound/samples/sfx_5/18.aifc
#define SAMPLE_sfx_5_19_aifc 0x4c940 // build/us_pc/sound/samples/sfx_5/19.aifc
#define SAMPLE_sfx_5_1A_aifc 0x4cc70 // build/us_pc/sound/samples/sfx_5/1A.aifc
#define SAMPLE_sfx_5_1B_aifc 0x4f4a0 // build/us_pc/sound/samples/sfx_5/1B.aifc
#define SAMPLE_sfx_5_1C_aifc 0x50e50 // build/us_pc/sound/samples/sfx_5/1C.aifc
#define SAMPLE_sfx_6_00_aifc 0x51ed0 // build/us_pc/sound/samples/sfx_6/00.aifc
#define SAMPLE_sfx_6_01_aifc 0x52760 // build/us_pc/sound/samples/sfx_6/01.aifc
#define SAMPLE_sfx_6_02_aifc 0x53420 // build/us_pc/sound/samples/sfx_6/02.aifc
#define SAMPLE_sfx_6_03_aifc 0x55730 // build/us_pc/sound/samples/sfx_6/03.aifc
#define SAMPLE_sfx_6_04_aifc 0x594e0 // build/us_pc/sound/samples/sfx_6/04.aifc
#define SAMPLE_sfx_6_05_aifc 0x59fd0 // build/us_pc/sound/samples/sfx_6/05.aifc
#define SAMPLE_sfx_6_06_aifc 0x5b990 // build/us_pc/sound/samples/sfx_6/06.aifc
#define SAMPLE_sfx_6_07_aifc 0x5c050 // build/us_pc/sound/samples/sfx_6/07.aifc
#define SAMPLE_sfx_6_08_aifc 0x5c580 // build/us_pc/sound/samples/sfx_6/08.aifc
#define SAMPLE_sfx_6_09_aifc 0x5e210 // build/us_pc/sound/samples/sfx_6/09.aifc
#define SAMPLE_sfx_6_0A_aifc 0x5eb30 // build/us_pc/sound/samples/sfx_6/0A.aifc
#define SAMPLE_sfx_6_0B_aifc 0x5f4b0 // build/us_pc/sound/samples/sfx_6/0B.aifc
#define SAMPLE_sfx_6_0C_aifc 0x5fd40 // build/us_pc/sound/samples/sfx_6/0C.aifc
#define SAMPLE_sfx_6_0D_aifc 0x611f0 // build/us_pc/sound/samples/sfx_6/0D.aifc
#define SAMPLE_sfx_7_00_aifc 0x63a70 // build/us_pc/sound/samples/sfx_7/00.aifc
#define SAMPLE_sfx_7_01_aifc 0x63f30 // build/us_pc/sound/samples/sfx_7/01.aifc
#define SAMPLE_sfx_7_02_aifc 0x64d80 // build/us_pc/sound/samples/sfx_7/02.aifc
#define SAMPLE_sfx_7_03_aifc 0x65240 // build/us_pc/sound/samples/sfx_7/03.aifc
#define SAMPLE_sfx_7_04_aifc 0x67ba0 // build/us_pc/sound/samples/sfx_7/04.aifc
#define SAMPLE_sfx_7_05_aifc 0x6a5e0 // build/us_pc/sound/samples/sfx_7/05.aifc
#define SAMPLE_sfx_7_06_aifc 0x6b5f0 // build/us_pc/sound/samples/sfx_7/06.aifc
#define SAMPLE_sfx_7_07_aifc 0x6c8c0 // build/us_pc/sound/samples/sfx_7/07.aifc
#define SAMPLE_sfx_7_08_aifc 0x6dca0 // build/us_pc/sound/samples/sfx_7/08.aifc
#define SAMPLE_sfx_7_09_aifc 0x6e210 // build/us_pc/sound/samples/sfx_7/09.aifc
#define SAMPLE_sfx_7_0A_aifc 0x6f160 // build/us_pc/sound/samples/sfx_7/0A.aifc
#define SAMPLE_sfx_7_0B_aifc 0x709b0 // build/us_pc/sound/samples/sfx_7/0B.aifc
#define SAMPLE_sfx_7_0C_aifc 0x71f50 // build/us_pc/sound/samples/sfx_7/0C.aifc
#define SAMPLE_sfx_7_0D_chain_chomp_bark_aifc 0x74240 // build/us_pc/sound/samples/sfx_7/0D_chain_chomp_bark.aifc
#define SAMPLE_sfx_mario_00_mario_jump_hoo_aifc 0x74960 // build/us_pc/sound/samples/sfx_mario/00_mario_jump_hoo.aifc
#define SAMPLE_sfx_mario_01_mario_jump_wah_aifc 0x750c0 // build/us_pc/sound/samples/sfx_mario/01_mario_jump_wah.aifc
#define SAMPLE_sfx_mario_02_mario_yah_aifc 0x758d0 // build/us_pc/sound/samples/sfx_mario/02_mario_yah.aifc
#define SAMPLE_sfx_mario_03_mario_haha_aifc 0x76360 // build/us_pc/sound/samples/sfx_mario/03_mario_haha.aifc
#define SAMPLE_sfx_mario_04_mario_yahoo_aifc 0x77e60 // build/us_pc/sound/samples/sfx_mario/04_mario_yahoo.aifc
#define SAMPLE_sfx_mario_05_mario_uh_aifc 0x79fb0 // build/us_pc/sound/samples/sfx_mario/05_mario_uh.aifc
#define SAMPLE_sfx_mario_06_mario_hrmm_aifc 0x7aab0 // build/us_pc/sound/samples/sfx_mario/06_mario_hrmm.aifc
#define SAMPLE_sfx_mario_07_mario_wah2_aifc 0x7bc30 // build/us_pc/sound/samples/sfx_mario/07_mario_wah2.aifc
#define SAMPLE_sfx_mario_08_mario_whoa_aifc 0x7c6c0 // build/us_pc/sound/samples/sfx_mario/08_mario_whoa.aifc
#define SAMPLE_sfx_mario_09_mario_eeuh_aifc 0x7e750 // build/us_pc/sound/samples/sfx_mario/09_mario_eeuh.aifc
#define SAMPLE_sfx_mario_0A_mario_attacked_aifc 0x80080 // build/us_pc/sound/samples/sfx_mario/0A_mario_attacked.aifc
#define SAMPLE_sfx_mario_0B_mario_ooof_aifc 0x81690 // build/us_pc/sound/samples/sfx_mario/0B_mario_ooof.aifc
#define SAMPLE_sfx_mario_0C_mario_here_we_go_aifc 0x82c40 // build/us_pc/sound/samples/sfx_mario/0C_mario_here_we_go.aifc
#define SAMPLE_sfx_mario_0D_mario_yawning_aifc 0x85e50 // build/us_pc/sound/samples/sfx_mario/0D_mario_yawning.aifc
#define SAMPLE_sfx_mario_0E_mario_snoring1_aifc 0x89750 // build/us_pc/sound/samples/sfx_mario/0E_mario_snoring1.aifc
#define SAMPLE_sfx_mario_0F_mario_snoring2_aifc 0x8b830 // build/us_pc/sound/samples/sfx_mario/0F_mario_snoring2.aifc
#define SAMPLE_sfx_mario_10_mario_doh_aifc 0x8c3f0 // build/us_pc/sound/samples/sfx_mario/10_mario_doh.aifc
#define SAMPLE_sfx_mario_11_mario_game_over_aifc 0x8d810 // build/us_pc/sound/samples/sfx_mario/11_mario_game_over.aifc
#define SAMPLE_sfx_mario_12_mario_hello_aifc 0x8f140 // build/us_pc/sound/samples/sfx_mario/12_mario_hello.aifc
#define SAMPLE_sfx_mario_13_mario_press_start_to_play_aifc 0x90c60 // build/us_pc/sound/samples/sfx_mario/13_mario_press_start_to_play.aifc
#define SAMPLE_sfx_mario_14_mario_twirl_bounce_aifc 0x94230 // build/us_pc/sound/samples/sfx_mario/14_mario_twirl_bounce.aifc
#define SAMPLE_sfx_mario_15_mario_snoring3_aifc 0x95370 // build/us_pc/sound/samples/sfx_mario/15_mario_snoring3.aifc
#define SAMPLE_sfx_mario_16_mario_so_longa_bowser_aifc 0xad330 // build/us_pc/sound/samples/sfx_mario/16_mario_so_longa_bowser.aifc
#define SAMPLE_sfx_mario_17_mario_ima_tired_aifc 0xb07e0 // build/us_pc/sound/samples/sfx_mario/17_mario_ima_tired.aifc
#define SAMPLE_sfx_mario_18_mario_waha_aifc 0xb3470 // build/us_pc/sound/samples/sfx_mario/18_mario_waha.aifc
#define SAMPLE_sfx_mario_19_mario_yippee_aifc 0xb5a50 // build/us_pc/sound/samples/sfx_mario/19_mario_yippee.aifc
#define SAMPLE_sfx_mario_1A_mario_lets_a_go_aifc 0xb7d90 // build/us_pc/sound/samples/sfx_mario/1A_mario_lets_a_go.aifc
#define SAMPLE_sfx_9_00_aifc 0xb9e20 // build/us_pc/sound/samples/sfx_9/00.aifc
#define SAMPLE_sfx_9_01_aifc 0xbb5a0 // build/us_pc/sound/samples/sfx_9/01.aifc
#define SAMPLE_sfx_9_02_aifc 0xbc160 // build/us_pc/sound/samples/sfx_9/02.aifc
#define SAMPLE_sfx_9_03_aifc 0xbec90 // build/us_pc/sound/samples/sfx_9/03.aifc
#define SAMPLE_sfx_9_04_camera_buzz_aifc 0xc0da0 // build/us_pc/sound/samples/sfx_9/04_camera_buzz.aifc
#define SAMPLE_sfx_9_05_camera_shutter_aifc 0xc1c20 // build/us_pc/sound/samples/sfx_9/05_camera_shutter.aifc
#define SAMPLE_sfx_9_06_aifc 0xc22b0 // build/us_pc/sound/samples/sfx_9/06.aifc
#define SAMPLE_sfx_mario_peach_00_mario_waaaooow_aifc 0xc4970 // build/us_pc/sound/samples/sfx_mario_peach/00_mario_waaaooow.aifc
#define SAMPLE_sfx_mario_peach_01_mario_hoohoo_aifc 0xcaa30 // build/us_pc/sound/samples/sfx_mario_peach/01_mario_hoohoo.aifc
#define SAMPLE_sfx_mario_peach_02_mario_panting_aifc 0xcc010 // build/us_pc/sound/samples/sfx_mario_peach/02_mario_panting.aifc
#define SAMPLE_sfx_mario_peach_03_mario_dying_aifc 0xcd490 // build/us_pc/sound/samples/sfx_mario_peach/03_mario_dying.aifc
#define SAMPLE_sfx_mario_peach_04_mario_on_fire_aifc 0xd1240 // build/us_pc/sound/samples/sfx_mario_peach/04_mario_on_fire.aifc
#define SAMPLE_sfx_mario_peach_05_mario_uh2_aifc 0xd5920 // build/us_pc/sound/samples/sfx_mario_peach/05_mario_uh2.aifc
#define SAMPLE_sfx_mario_peach_06_mario_coughing_aifc 0xd6210 // build/us_pc/sound/samples/sfx_mario_peach/06_mario_coughing.aifc
#define SAMPLE_sfx_mario_peach_07_mario_its_a_me_mario_aifc 0xd6c10 // build/us_pc/sound/samples/sfx_mario_peach/07_mario_its_a_me_mario.aifc
#define SAMPLE_sfx_mario_peach_08_mario_punch_yah_aifc 0xdae90 // build/us_pc/sound/samples/sfx_mario_peach/08_mario_punch_yah.aifc
#define SAMPLE_sfx_mario_peach_09_mario_punch_hoo_aifc 0xdb730 // build/us_pc/sound/samples/sfx_mario_peach/09_mario_punch_hoo.aifc
#define SAMPLE_sfx_mario_peach_0A_mario_mama_mia_aifc 0xdcd90 // build/us_pc/sound/samples/sfx_mario_peach/0A_mario_mama_mia.aifc
#define SAMPLE_sfx_mario_peach_0B_mario_okey_dokey_aifc 0xdedd0 // build/us_pc/sound/samples/sfx_mario_peach/0B_mario_okey_dokey.aifc
#define SAMPLE_sfx_mario_peach_0C_mario_drowning_aifc 0xe0e00 // build/us_pc/sound/samples/sfx_mario_peach/0C_mario_drowning.aifc
#define SAMPLE_sfx_mario_peach_0D_mario_thank_you_playing_my_game_aifc 0xe3d30 // build/us_pc/sound/samples/sfx_mario_peach/0D_mario_thank_you_playing_my_game.aifc
#define SAMPLE_sfx_mario_peach_0E_peach_dear_mario_aifc 0xe91a0 // build/us_pc/sound/samples/sfx_mario_peach/0E_peach_dear_mario.aifc
#define SAMPLE_sfx_mario_peach_0F_peach_mario_aifc 0xfe6d0 // build/us_pc/sound/samples/sfx_mario_peach/0F_peach_mario.aifc
#define SAMPLE_sfx_mario_peach_10_peach_power_of_the_stars_aifc 0x100380 // build/us_pc/sound/samples/sfx_mario_peach/10_peach_power_of_the_stars.aifc
#define SAMPLE_sfx_mario_peach_11_peach_thanks_to_you_aifc 0x1078f0 // build/us_pc/sound/samples/sfx_mario_peach/11_peach_thanks_to_you.aifc
#define SAMPLE_sfx_mario_peach_12_peach_thank_you_mario_aifc 0x10b580 // build/us_pc/sound/samples/sfx_mario_peach/12_peach_thank_you_mario.aifc
#define SAMPLE_sfx_mario_peach_13_peach_something_special_aifc 0x10ed00 // build/us_pc/sound/samples/sfx_mario_peach/13_peach_something_special.aifc
#define SAMPLE_sfx_mario_peach_14_peach_bake_a_cake_aifc 0x114b50 // build/us_pc/sound/samples/sfx_mario_peach/14_peach_bake_a_cake.aifc
#define SAMPLE_sfx_mario_peach_15_peach_for_mario_aifc 0x11e5e0 // build/us_pc/sound/samples/sfx_mario_peach/15_peach_for_mario.aifc
#define SAMPLE_sfx_mario_peach_16_peach_mario2_aifc 0x120a10 // build/us_pc/sound/samples/sfx_mario_peach/16_peach_mario2.aifc
#define SAMPLE_instruments_00_aifc 0x1225d0 // build/us_pc/sound/samples/instruments/00.aifc
#define SAMPLE_instruments_01_banjo_1_aifc 0x125410 // build/us_pc/sound/samples/instruments/01_banjo_1.aifc
#define SAMPLE_instruments_02_aifc 0x127cb0 // build/us_pc/sound/samples/instruments/02.aifc
#define SAMPLE_instruments_03_human_whistle_aifc 0x12c080 // build/us_pc/sound/samples/instruments/03_human_whistle.aifc
#define SAMPLE_instruments_04_bright_piano_aifc 0x130370 // build/us_pc/sound/samples/instruments/04_bright_piano.aifc
#define SAMPLE_instruments_05_acoustic_bass_aifc 0x132180 // build/us_pc/sound/samples/instruments/05_acoustic_bass.aifc
#define SAMPLE_instruments_06_kick_drum_1_aifc 0x135910 // build/us_pc/sound/samples/instruments/06_kick_drum_1.aifc
#define SAMPLE_instruments_07_rimshot_aifc 0x1360d0 // build/us_pc/sound/samples/instruments/07_rimshot.aifc
#define SAMPLE_instruments_08_aifc 0x136c60 // build/us_pc/sound/samples/instruments/08.aifc
#define SAMPLE_instruments_09_aifc 0x1380e0 // build/us_pc/sound/samples/instruments/09.aifc
#define SAMPLE_instruments_0A_tambourine_aifc 0x139ba0 // build/us_pc/sound/samples/instruments/0A_tambourine.aifc
#define SAMPLE_instruments_0B_aifc 0x13c180 // build/us_pc/sound/samples/instruments/0B.aifc
#define SAMPLE_instruments_0C_conga_stick_aifc 0x13dda0 // build/us_pc/sound/samples/instruments/0C_conga_stick.aifc
#define SAMPLE_instruments_0D_clave_aifc 0x13ef40 // build/us_pc/sound/samples/instruments/0D_clave.aifc
#define SAMPLE_instruments_0E_hihat_closed_aifc 0x140140 // build/us_pc/sound/samples/instruments/0E_hihat_closed.aifc
#define SAMPLE_instruments_0F_hihat_open_aifc 0x140990 // build/us_pc/sound/samples/instruments/0F_hihat_open.aifc
#define SAMPLE_instruments_10_cymbal_bell_aifc 0x143930 // build/us_pc/sound/samples/instruments/10_cymbal_bell.aifc
#define SAMPLE_instruments_11_splash_cymbal_aifc 0x146ab0 // build/us_pc/sound/samples/instruments/11_splash_cymbal.aifc
#define SAMPLE_instruments_12_snare_drum_1_aifc 0x14b1c0 // build/us_pc/sound/samples/instruments/12_snare_drum_1.aifc
#define SAMPLE_instruments_13_snare_drum_2_aifc 0x14cd90 // build/us_pc/sound/samples/instruments/13_snare_drum_2.aifc
#define SAMPLE_instruments_14_strings_5_aifc 0x14f400 // build/us_pc/sound/samples/instruments/14_strings_5.aifc
#define SAMPLE_instruments_15_strings_4_aifc 0x154350 // build/us_pc/sound/samples/instruments/15_strings_4.aifc
#define SAMPLE_instruments_16_french_horns_aifc 0x158ea0 // build/us_pc/sound/samples/instruments/16_french_horns.aifc
#define SAMPLE_instruments_17_trumpet_aifc 0x15c7f0 // build/us_pc/sound/samples/instruments/17_trumpet.aifc
#define SAMPLE_instruments_18_timpani_aifc 0x15ffd0 // build/us_pc/sound/samples/instruments/18_timpani.aifc
#define SAMPLE_instruments_19_brass_aifc 0x164d70 // build/us_pc/sound/samples/instruments/19_brass.aifc
#define SAMPLE_instruments_1A_slap_bass_aifc 0x169440 // build/us_pc/sound/samples/instruments/1A_slap_bass.aifc
#define SAMPLE_instruments_1B_organ_2_aifc 0x16b7a0 // build/us_pc/sound/samples/instruments/1B_organ_2.aifc
#define SAMPLE_instruments_1C_aifc 0x16f530 // build/us_pc/sound/samples/instruments/1C.aifc
#define SAMPLE_instruments_1D_aifc 0x170f00 // build/us_pc/sound/samples/instruments/1D.aifc
#define SAMPLE_instruments_1E_closed_triangle_aifc 0x176b30 // build/us_pc/sound/samples/instruments/1E_closed_triangle.aifc
#define SAMPLE_instruments_1F_open_triangle_aifc 0x176f30 // build/us_pc/sound/samples/instruments/1F_open_triangle.aifc
#define SAMPLE_instruments_20_cabasa_aifc 0x1787b0 // build/us_pc/sound/samples/instruments/20_cabasa.aifc
#define SAMPLE_instruments_21_sine_bass_aifc 0x179840 // build/us_pc/sound/samples/instruments/21_sine_bass.aifc
#define SAMPLE_instruments_22_boys_choir_aifc 0x17b530 // build/us_pc/sound/samples/instruments/22_boys_choir.aifc
#define SAMPLE_instruments_23_strings_1_aifc 0x17ec40 // build/us_pc/sound/samples/instruments/23_strings_1.aifc
#define SAMPLE_instruments_24_strings_2_aifc 0x182a50 // build/us_pc/sound/samples/instruments/24_strings_2.aifc
#define SAMPLE_instruments_25_strings_3_aifc 0x187140 // build/us_pc/sound/samples/instruments/25_strings_3.aifc
#define SAMPLE_instruments_26_crystal_rhodes_aifc 0x18b5a0 // build/us_pc/sound/samples/instruments/26_crystal_rhodes.aifc
#define SAMPLE_instruments_27_harpsichord_aifc 0x192690 // build/us_pc/sound/samples/instruments/27_harpsichord.aifc
#define SAMPLE_instruments_28_sitar_1_aifc 0x198ce0 // build/us_pc/sound/samples/instruments/28_sitar_1.aifc
#define SAMPLE_instruments_29_orchestra_hit_aifc 0x19cae0 // build/us_pc/sound/samples/instruments/29_orchestra_hit.aifc
#define SAMPLE_instruments_2A_aifc 0x19fc60 // build/us_pc/sound/samples/instruments/2A.aifc
#define SAMPLE_instruments_2B_aifc 0x1a3340 // build/us_pc/sound/samples/instruments/2B.aifc
#define SAMPLE_instruments_2C_aifc 0x1a5130 // build/us_pc/sound/samples/instruments/2C.aifc
#define SAMPLE_instruments_2D_trombone_aifc 0x1a9770 // build/us_pc/sound/samples/instruments/2D_trombone.aifc
#define SAMPLE_instruments_2E_accordion_aifc 0x1ad380 // build/us_pc/sound/samples/instruments/2E_accordion.aifc
#define SAMPLE_instruments_2F_sleigh_bells_aifc 0x1b1ac0 // build/us_pc/sound/samples/instruments/2F_sleigh_bells.aifc
#define SAMPLE_instruments_30_rarefaction_lahna_aifc 0x1b6c30 // build/us_pc/sound/samples/instruments/30_rarefaction-lahna.aifc
#define SAMPLE_instruments_31_rarefaction_convolution_aifc 0x1bb260 // build/us_pc/sound/samples/instruments/31_rarefaction-convolution.aifc
#define SAMPLE_instruments_32_metal_rimshot_aifc 0x1beea0 // build/us_pc/sound/samples/instruments/32_metal_rimshot.aifc
#define SAMPLE_instruments_33_kick_drum_2_aifc 0x1c3030 // build/us_pc/sound/samples/instruments/33_kick_drum_2.aifc
#define SAMPLE_instruments_34_alto_flute_aifc 0x1c4200 // build/us_pc/sound/samples/instruments/34_alto_flute.aifc
#define SAMPLE_instruments_35_gospel_organ_aifc 0x1c66a0 // build/us_pc/sound/samples/instruments/35_gospel_organ.aifc
#define SAMPLE_instruments_36_sawtooth_synth_aifc 0x1c90b0 // build/us_pc/sound/samples/instruments/36_sawtooth_synth.aifc
#define SAMPLE_instruments_37_square_synth_aifc 0x1cb140 // build/us_pc/sound/samples/instruments/37_square_synth.aifc
#define SAMPLE_instruments_38_electric_kick_drum_aifc 0x1cce60 // build/us_pc/sound/samples/instruments/38_electric_kick_drum.aifc
#define SAMPLE_instruments_39_sitar_2_aifc 0x1cd820 // build/us_pc/sound/samples/instruments/39_sitar_2.aifc
#define SAMPLE_instruments_3A_music_box_aifc 0x1d2a90 // build/us_pc/sound/samples/instruments/3A_music_box.aifc
#define SAMPLE_instruments_3B_banjo_2_aifc 0x1d6510 // build/us_pc/sound/samples/instruments/3B_banjo_2.aifc
#define SAMPLE_instruments_3C_acoustic_guitar_aifc 0x1dbf80 // build/us_pc/sound/samples/instruments/3C_acoustic_guitar.aifc
#define SAMPLE_instruments_3D_aifc 0x1e0ab0 // build/us_pc/sound/samples/instruments/3D.aifc
#define SAMPLE_instruments_3E_monk_choir_aifc 0x1e3b40 // build/us_pc/sound/samples/instruments/3E_monk_choir.aifc
#define SAMPLE_instruments_3F_aifc 0x1e6820 // build/us_pc/sound/samples/instruments/3F.aifc
#define SAMPLE_instruments_40_bell_aifc 0x1eb5c0 // build/us_pc/sound/samples/instruments/40_bell.aifc
#define SAMPLE_instruments_41_pan_flute_aifc 0x1ef220 // build/us_pc/sound/samples/instruments/41_pan_flute.aifc
#define SAMPLE_instruments_42_vibraphone_aifc 0x1f3860 // build/us_pc/sound/samples/instruments/42_vibraphone.aifc
#define SAMPLE_instruments_43_harmonica_aifc 0x1f4410 // build/us_pc/sound/samples/instruments/43_harmonica.aifc
#define SAMPLE_instruments_44_grand_piano_aifc 0x1f75c0 // build/us_pc/sound/samples/instruments/44_grand_piano.aifc
#define SAMPLE_instruments_45_french_horns_lq_aifc 0x1fb150 // build/us_pc/sound/samples/instruments/45_french_horns_lq.aifc
#define SAMPLE_instruments_46_pizzicato_strings_1_aifc 0x1fce20 // build/us_pc/sound/samples/instruments/46_pizzicato_strings_1.aifc
#define SAMPLE_instruments_47_pizzicato_strings_2_aifc 0x1ffaa0 // build/us_pc/sound/samples/instruments/47_pizzicato_strings_2.aifc
#define SAMPLE_instruments_48_steel_drum_aifc 0x202ed0 // build/us_pc/sound/samples/instruments/48_steel_drum.aifc
#define SAMPLE_piranha_music_box_00_music_box_aifc 0x2068a0 // build/us_pc/sound/samples/piranha_music_box/00_music_box.aifc
#define SAMPLE_course_start_00_la_aifc 0x20a320 // build/us_pc/sound/samples/course_start/00_la.aifc
#define SAMPLE_bowser_organ_00_organ_1_aifc 0x20bc70 // build/us_pc/sound/samples/bowser_organ/00_organ_1.aifc
#define SAMPLE_bowser_organ_01_organ_1_lq_aifc 0x215a70 // build/us_pc/sound/samples/bowser_organ/01_organ_1_lq.aifc
#define SAMPLE_bowser_organ_02_boys_choir_aifc 0x219c10 // build/us_pc/sound/samples/bowser_organ/02_boys_choir.aifc
#define SAMPLE_extended_00_aifc 0x4566f0 // build/us_pc/sound/samples/extended/00.aifc
#define SAMPLE_extended_00_la_aifc 0x459530 // build/us_pc/sound/samples/extended/00_la.aifc
#define SAMPLE_extended_00_music_box_aifc 0x45ae80 // build/us_pc/sound/samples/extended/00_music_box.aifc
#define SAMPLE_extended_00_organ_1_aifc 0x45e900 // build/us_pc/sound/samples/extended/00_organ_1.aifc
#define SAMPLE_extended_01_banjo_1_aifc 0x468700 // build/us_pc/sound/samples/extended/01_banjo_1.aifc
#define SAMPLE_extended_01_organ_1_lq_aifc 0x46afa0 // build/us_pc/sound/samples/extended/01_organ_1_lq.aifc
#define SAMPLE_extended_02_aifc 0x46f140 // build/us_pc/sound/samples/extended/02.aifc
#define SAMPLE_extended_02_boys_choir_aifc 0x473510 // build/us_pc/sound/samples/extended/02_boys_choir.aifc
#define SAMPLE_extended_03_human_whistle_aifc 0x476c20 // build/us_pc/sound/samples/extended/03_human_whistle.aifc
#define SAMPLE_extended_04_bright_piano_aifc 0x47af10 // build/us_pc/sound/samples/extended/04_bright_piano.aifc
#define SAMPLE_extended_05_acoustic_bass_aifc 0x47cd20 // build/us_pc/sound/samples/extended/05_acoustic_bass.aifc
#define SAMPLE_extended_06_kick_drum_1_aifc 0x4804b0 // build/us_pc/sound/samples/extended/06_kick_drum_1.aifc
#define SAMPLE_extended_07_rimshot_aifc 0x480c70 // build/us_pc/sound/samples/extended/07_rimshot.aifc
#define SAMPLE_extended_08_aifc 0x481800 // build/us_pc/sound/samples/extended/08.aifc
#define SAMPLE_extended_09_aifc 0x482c80 // build/us_pc/sound/samples/extended/09.aifc
#define SAMPLE_extended_0A_tambourine_aifc 0x484740 // build/us_pc/sound/samples/extended/0A_tambourine.aifc
#define SAMPLE_extended_0B_aifc 0x486d20 // build/us_pc/sound/samples/extended/0B.aifc
#define SAMPLE_extended_0C_conga_stick_aifc 0x488940 // build/us_pc/sound/samples/extended/0C_conga_stick.aifc
#define SAMPLE_extended_0D_clave_aifc 0x489ae0 // build/us_pc/sound/samples/extended/0D_clave.aifc
#define SAMPLE_extended_0E_hihat_closed_aifc 0x48ace0 // build/us_pc/sound/samples/extended/0E_hihat_closed.aifc
#define SAMPLE_extended_0F_hihat_open_aifc 0x48b530 // build/us_pc/sound/samples/extended/0F_hihat_open.aifc
#define SAMPLE_extended_10_cymbal_bell_aifc 0x48e4d0 // build/us_pc/sound/samples/extended/10_cymbal_bell.aifc
#define SAMPLE_extended_11_splash_cymbal_aifc 0x491650 // build/us_pc/sound/samples/extended/11_splash_cymbal.aifc
#define SAMPLE_extended_12_snare_drum_1_aifc 0x495d60 // build/us_pc/sound/samples/extended/12_snare_drum_1.aifc
#define SAMPLE_extended_13_snare_drum_2_aifc 0x497930 // build/us_pc/sound/samples/extended/13_snare_drum_2.aifc
#define SAMPLE_extended_14_strings_5_aifc 0x499fa0 // build/us_pc/sound/samples/extended/14_strings_5.aifc
#define SAMPLE_extended_15_strings_4_aifc 0x49eef0 // build/us_pc/sound/samples/extended/15_strings_4.aifc
#define SAMPLE_extended_16_french_horns_aifc 0x4a3a40 // build/us_pc/sound/samples/extended/16_french_horns.aifc
#define SAMPLE_extended_17_trumpet_aifc 0x4a7390 // build/us_pc/sound/samples/extended/17_trumpet.aifc
#define SAMPLE_extended_18_timpani_aifc 0x4aab70 // build/us_pc/sound/samples/extended/18_timpani.aifc
#define SAMPLE_extended_19_brass_aifc 0x4af910 // build/us_pc/sound/samples/extended/19_brass.aifc
#define SAMPLE_extended_1A_slap_bass_aifc 0x4b3fe0 // build/us_pc/sound/samples/extended/1A_slap_bass.aifc
#define SAMPLE_extended_1B_organ_2_aifc 0x4b6340 // build/us_pc/sound/samples/extended/1B_organ_2.aifc
#define SAMPLE_extended_1C_aifc 0x4ba0d0 // build/us_pc/sound/samples/extended/1C.aifc
#define SAMPLE_extended_1D_aifc 0x4bbaa0 // build/us_pc/sound/samples/extended/1D.aifc
#define SAMPLE_extended_1E_closed_triangle_aifc 0x4c16d0 // build/us_pc/sound/samples/extended/1E_closed_triangle.aifc
#define SAMPLE_extended_1F_open_triangle_aifc 0x4c1ad0 // build/us_pc/sound/samples/extended/1F_open_triangle.aifc
#define SAMPLE_extended_20_cabasa_aifc 0x4c3350 // build/us_pc/sound/samples/extended/20_cabasa.aifc
#define SAMPLE_extended_21_sine_bass_aifc 0x4c43e0 // build/us_pc/sound/samples/extended/21_sine_bass.aifc
#define SAMPLE_extended_22_boys_choir_aifc 0x4c60d0 // build/us_pc/sound/samples/extended/22_boys_choir.aifc
#define SAMPLE_extended_23_strings_1_aifc 0x4c97e0 // build/us_pc/sound/samples/extended/23_strings_1.aifc
#define SAMPLE_extended_24_strings_2_aifc 0x4cd5f0 // build/us_pc/sound/samples/extended/24_strings_2.aifc
#define SAMPLE_extended_25_strings_3_aifc 0x4d1ce0 // build/us_pc/sound/samples/extended/25_strings_3.aifc
#define SAMPLE_extended_26_crystal_rhodes_aifc 0x4d6140 // build/us_pc/sound/samples/extended/26_crystal_rhodes.aifc
#define SAMPLE_extended_27_harpsichord_aifc 0x4dd230 // build/us_pc/sound/samples/extended/27_harpsichord.aifc
#define SAMPLE_extended_28_sitar_1_aifc 0x4e3880 // build/us_pc/sound/samples/extended/28_sitar_1.aifc
#define SAMPLE_extended_29_orchestra_hit_aifc 0x4e7680 // build/us_pc/sound/samples/extended/29_orchestra_hit.aifc
#define SAMPLE_extended_2A_aifc 0x4ea800 // build/us_pc/sound/samples/extended/2A.aifc
#define SAMPLE_extended_2B_aifc 0x4edee0 // build/us_pc/sound/samples/extended/2B.aifc
#define SAMPLE_extended_2C_aifc 0x4efcd0 // build/us_pc/sound/samples/extended/2C.aifc
#define SAMPLE_extended_2D_trombone_aifc 0x4f4310 // build/us_pc/sound/samples/extended/2D_trombone.aifc
#define SAMPLE_extended_2E_accordion_aifc 0x4f7f20 // build/us_pc/sound/samples/extended/2E_accordion.aifc
#define SAMPLE_extended_2F_sleigh_bells_aifc 0x4fc660 // build/us_pc/sound/samples/extended/2F_sleigh_bells.aifc
#define SAMPLE_extended_30_rarefaction_lahna_aifc 0x5017d0 // build/us_pc/sound/samples/extended/30_rarefaction-lahna.aifc
#define SAMPLE_extended_31_rarefaction_convolution_aifc 0x505e00 // build/us_pc/sound/samples/extended/31_rarefaction-convolution.aifc
#define SAMPLE_extended_32_metal_rimshot_aifc 0x509a40 // build/us_pc/sound/samples/extended/32_metal_rimshot.aifc
#define SAMPLE_extended_33_kick_drum_2_aifc 0x50dbd0 // build/us_pc/sound/samples/extended/33_kick_drum_2.aifc
#define SAMPLE_extended_34_alto_flute_aifc 0x50eda0 // build/us_pc/sound/samples/extended/34_alto_flute.aifc
#define SAMPLE_extended_35_gospel_organ_aifc 0x511240 // build/us_pc/sound/samples/extended/35_gospel_organ.aifc
#define SAMPLE_extended_36_sawtooth_synth_aifc 0x513c50 // build/us_pc/sound/samples/extended/36_sawtooth_synth.aifc
#define SAMPLE_extended_37_square_synth_aifc 0x515ce0 // build/us_pc/sound/samples/extended/37_square_synth.aifc
#define SAMPLE_extended_38_electric_kick_drum_aifc 0x517a00 // build/us_pc/sound/samples/extended/38_electric_kick_drum.aifc
#define SAMPLE_extended_39_sitar_2_aifc 0x5183c0 // build/us_pc/sound/samples/extended/39_sitar_2.aifc
#define SAMPLE_extended_3A_music_box_aifc 0x51d630 // build/us_pc/sound/samples/extended/3A_music_box.aifc
#define SAMPLE_extended_3B_banjo_2_aifc 0x5210b0 // build/us_pc/sound/samples/extended/3B_banjo_2.aifc
#define SAMPLE_extended_3C_acoustic_guitar_aifc 0x526b20 // build/us_pc/sound/samples/extended/3C_acoustic_guitar.aifc
#define SAMPLE_extended_3D_aifc 0x52b650 // build/us_pc/sound/samples/extended/3D.aifc
#define SAMPLE_extended_3E_monk_choir_aifc 0x52e6e0 // build/us_pc/sound/samples/extended/3E_monk_choir.aifc
#define SAMPLE_extended_3F_aifc 0x5313c0 // build/us_pc/sound/samples/extended/3F.aifc
#define SAMPLE_extended_40_bell_aifc 0x536160 // build/us_pc/sound/samples/extended/40_bell.aifc
#define SAMPLE_extended_41_pan_flute_aifc 0x539dc0 // build/us_pc/sound/samples/extended/41_pan_flute.aifc
#define SAMPLE_extended_42_vibraphone_aifc 0x53e400 // build/us_pc/sound/samples/extended/42_vibraphone.aifc
#define SAMPLE_extended_43_harmonica_aifc 0x53efb0 // build/us_pc/sound/samples/extended/43_harmonica.aifc
#define SAMPLE_extended_44_grand_piano_aifc 0x542160 // build/us_pc/sound/samples/extended/44_grand_piano.aifc
#define SAMPLE_extended_45_french_horns_lq_aifc 0x545cf0 // build/us_pc/sound/samples/extended/45_french_horns_lq.aifc
#define SAMPLE_extended_46_pizzicato_strings_1_aifc 0x5479c0 // build/us_pc/sound/samples/extended/46_pizzicato_strings_1.aifc
#define SAMPLE_extended_47_pizzicato_strings_2_aifc 0x54a640 // build/us_pc/sound/samples/extended/47_pizzicato_strings_2.aifc
#define SAMPLE_extended_48_steel_drum_aifc 0x54da70 // build/us_pc/sound/samples/extended/48_steel_drum.aifc
