#include "levels/ccm/texture_include.inc.c"
#include "levels/ccm/area_1/collision.inc.c"
#include "levels/ccm/area_1/macro.inc.c"
#include "levels/ccm/area_1/spline.inc.c"
#include "levels/ccm/model.inc.c"
