extern const GeoLayout pistol_geo[];
extern Lights1 pistol_gray_lights;
extern Lights1 pistol_darkergray_lights;
extern u8 pistol_noise_i8[];
extern Vtx pistol_Arm_mesh_layer_1_vtx_0[174];
extern Gfx pistol_Arm_mesh_layer_1_tri_0[];
extern Vtx pistol_Arm_mesh_layer_1_vtx_1[34];
extern Gfx pistol_Arm_mesh_layer_1_tri_1[];
extern Vtx pistol_Arm_mesh_layer_1_vtx_2[6];
extern Gfx pistol_Arm_mesh_layer_1_tri_2[];
extern Gfx mat_pistol_gray[];
extern Gfx mat_pistol_darkergray[];
extern Gfx mat_pistol_black_layer1[];
extern Gfx mat_revert_pistol_black_layer1[];
extern Gfx pistol_Arm_mesh_layer_1[];
extern Gfx pistol_material_revert_render_settings[];
