const GeoLayout mirror_room_area_2_geo[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_TRANSLATE_ROTATE(0, 0, 900, 0, 180, 180, 0),
        GEO_OPEN_NODE(),
            GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -3518, -1408, -2028, mirror_room_dl_5_GeoRoot_castle_inside_2_inside_castle_seg7_dl_0704A0E8_001_mesh_layer_1),
            GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, -3518, -1408, -2028, mirror_room_dl_6_GeoRoot_castle_inside_2_inside_castle_seg7_dl_0704A2E0_mesh_layer_5),
            GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -3518, -1408, -2028, 90, 0, 0, mirror_room_dl_7_GeoRoot_castle_inside_2_inside_castle_seg7_dl_0704AA98_mesh_layer_1),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mirror_room_area_2[] = {
    GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
    GEO_OPEN_NODE(),
        GEO_ZBUFFER(0),
        GEO_OPEN_NODE(),
            GEO_NODE_ORTHO(100.0000),
            GEO_OPEN_NODE(),
                GEO_BACKGROUND_COLOR(0x0001),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ZBUFFER(1),
        GEO_OPEN_NODE(),
            GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
            GEO_OPEN_NODE(),
                GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
                GEO_OPEN_NODE(),
                    GEO_BRANCH(1, mirror_room_area_2_geo),
                    GEO_RENDER_OBJ(),
                    GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};
