GRAPH_NODE_TYPE(GRAPH_NODE_TYPE_ROOT,                 0x001,                              GraphNodeRoot,                LOT_GRAPHNODEROOT)
GRAPH_NODE_TYPE(GRAPH_NODE_TYPE_ORTHO_PROJECTION,     0x002,                              GraphNodeOrthoProjection,     LOT_GRAPHNODEORTHOPROJECTION)
GRAPH_NODE_TYPE(GRAPH_NODE_TYPE_PERSPECTIVE,          0x003 | GRAPH_NODE_TYPE_FUNCTIONAL, GraphNodePerspective,         LOT_GRAPHNODEPERSPECTIVE)
GRAPH_NODE_TYPE(GRAPH_NODE_TYPE_MASTER_LIST,          0x004,                              GraphNodeMasterList,          LOT_GRAPHNODEMASTERLIST)
GRAPH_NODE_TYPE(GRAPH_NODE_TYPE_START,                0x00A,                              GraphNodeStart,               LOT_GRAPHNODESTART)
GRAPH_NODE_TYPE(GRAPH_NODE_TYPE_LEVEL_OF_DETAIL,      0x00B,                              GraphNodeLevelOfDetail,       LOT_GRAPHNODELEVELOFDETAIL)
GRAPH_NODE_TYPE(GRAPH_NODE_TYPE_SWITCH_CASE,          0x00C | GRAPH_NODE_TYPE_FUNCTIONAL, GraphNodeSwitchCase,          LOT_GRAPHNODESWITCHCASE)
GRAPH_NODE_TYPE(GRAPH_NODE_TYPE_CAMERA,               0x014 | GRAPH_NODE_TYPE_FUNCTIONAL, GraphNodeCamera,              LOT_GRAPHNODECAMERA)
GRAPH_NODE_TYPE(GRAPH_NODE_TYPE_TRANSLATION_ROTATION, 0x015,                              GraphNodeTranslationRotation, LOT_GRAPHNODETRANSLATIONROTATION)
GRAPH_NODE_TYPE(GRAPH_NODE_TYPE_TRANSLATION,          0x016,                              GraphNodeTranslation,         LOT_GRAPHNODETRANSLATION)
GRAPH_NODE_TYPE(GRAPH_NODE_TYPE_ROTATION,             0x017,                              GraphNodeRotation,            LOT_GRAPHNODEROTATION)
GRAPH_NODE_TYPE(GRAPH_NODE_TYPE_OBJECT,               0x018,                              GraphNodeObject,              LOT_GRAPHNODEOBJECT)
GRAPH_NODE_TYPE(GRAPH_NODE_TYPE_ANIMATED_PART,        0x019,                              GraphNodeAnimatedPart,        LOT_GRAPHNODEANIMATEDPART)
GRAPH_NODE_TYPE(GRAPH_NODE_TYPE_BILLBOARD,            0x01A,                              GraphNodeBillboard,           LOT_GRAPHNODEBILLBOARD)
GRAPH_NODE_TYPE(GRAPH_NODE_TYPE_DISPLAY_LIST,         0x01B,                              GraphNodeDisplayList,         LOT_GRAPHNODEDISPLAYLIST)
GRAPH_NODE_TYPE(GRAPH_NODE_TYPE_SCALE,                0x01C,                              GraphNodeScale,               LOT_GRAPHNODESCALE)
GRAPH_NODE_TYPE(GRAPH_NODE_TYPE_SCALE_XYZ,            0x01D,                              GraphNodeScaleXYZ,            LOT_GRAPHNODESCALEXYZ)
GRAPH_NODE_TYPE(GRAPH_NODE_TYPE_SHADOW,               0x028,                              GraphNodeShadow,              LOT_GRAPHNODESHADOW)
GRAPH_NODE_TYPE(GRAPH_NODE_TYPE_OBJECT_PARENT,        0x029,                              GraphNodeObjectParent,        LOT_GRAPHNODEOBJECTPARENT)
GRAPH_NODE_TYPE(GRAPH_NODE_TYPE_GENERATED_LIST,       0x02A | GRAPH_NODE_TYPE_FUNCTIONAL, GraphNodeGenerated,           LOT_GRAPHNODEGENERATED)
GRAPH_NODE_TYPE(GRAPH_NODE_TYPE_BACKGROUND,           0x02C | GRAPH_NODE_TYPE_FUNCTIONAL, GraphNodeBackground,          LOT_GRAPHNODEBACKGROUND)
GRAPH_NODE_TYPE(GRAPH_NODE_TYPE_HELD_OBJ,             0x02E | GRAPH_NODE_TYPE_FUNCTIONAL, GraphNodeHeldObject,          LOT_GRAPHNODEHELDOBJECT)
GRAPH_NODE_TYPE(GRAPH_NODE_TYPE_CULLING_RADIUS,       0x02F,                              GraphNodeCullingRadius,       LOT_GRAPHNODECULLINGRADIUS)
GRAPH_NODE_TYPE(GRAPH_NODE_TYPE_BONE,                 0x030,                              GraphNodeBone,                LOT_GRAPHNODEBONE)
