#include "src/game/envfx_snow.h"

const GeoLayout canals_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, canals_dl_ground_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, canals_dl_pillar_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, canals_dl_ramp_mesh_layer_1),
		GEO_ASM(0, geo_hide_if_dnc),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, canals_dl_skybox_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, canals_dl_waterplane_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, canals_dl_waterplane_001_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout canals_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_OCEAN_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 100000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_FREE_ROAM, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, canals_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, canals_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, canals_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
