#include "geo_header.h"
const GeoLayout toads_cap_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 180, 75),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
            GEO_ASM(LAYER_OPAQUE + 3, geo_mario_set_player_colors),
            GEO_ASM(LAYER_ALPHA + 3, geo_mario_set_player_colors),
            GEO_ASM(LAYER_TRANSPARENT + 3, geo_mario_set_player_colors),
				GEO_ASM(10, geo_update_layer_transparency),
				GEO_SWITCH_CASE(2, geo_switch_anim_state),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, toad_cap_mesh_layer_1),
						GEO_DISPLAY_LIST(LAYER_ALPHA, toad_cap_mesh_layer_5),
					GEO_CLOSE_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, toad_cap_mesh_layer_1),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, toad_cap_mesh_layer_5),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, toad_cap_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, toad_cap_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, toad_cap_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};

const GeoLayout toads_metal_cap_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 180, 75),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
            GEO_ASM(LAYER_OPAQUE + 3, geo_mario_set_player_colors),
            GEO_ASM(LAYER_ALPHA + 3, geo_mario_set_player_colors),
            GEO_ASM(LAYER_TRANSPARENT + 3, geo_mario_set_player_colors),
				GEO_ASM(10, geo_update_layer_transparency),
				GEO_SWITCH_CASE(2, geo_switch_anim_state),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, toad_cap_Metal_Cap_mesh_layer_1),
					GEO_CLOSE_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, toad_cap_Metal_Cap_mesh_layer_1),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, toad_cap_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, toad_cap_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, toad_cap_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};

const GeoLayout toads_wing_cap_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 180, 75),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
            GEO_ASM(LAYER_OPAQUE + 3, geo_mario_set_player_colors),
            GEO_ASM(LAYER_ALPHA + 3, geo_mario_set_player_colors),
            GEO_ASM(LAYER_TRANSPARENT + 3, geo_mario_set_player_colors),
				GEO_ASM(10, geo_update_layer_transparency),
				GEO_SWITCH_CASE(2, geo_switch_anim_state),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_NODE_START(),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, toad_cap_mesh_layer_1),
							GEO_DISPLAY_LIST(LAYER_ALPHA, toad_cap_mesh_layer_5),
							GEO_DISPLAY_LIST(LAYER_ALPHA, toad_cap_Wing_Cap_Wings_mesh_layer_4),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_NODE_START(),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, toad_cap_mesh_layer_1),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, toad_cap_mesh_layer_5),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, toad_cap_Wing_Cap_Wings_mesh_layer_4),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, toad_cap_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, toad_cap_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, toad_cap_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};

const GeoLayout toads_winged_metal_cap_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 180, 75),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
            GEO_ASM(LAYER_OPAQUE + 3, geo_mario_set_player_colors),
            GEO_ASM(LAYER_ALPHA + 3, geo_mario_set_player_colors),
            GEO_ASM(LAYER_TRANSPARENT + 3, geo_mario_set_player_colors),
				GEO_ASM(10, geo_update_layer_transparency),
				GEO_SWITCH_CASE(2, geo_switch_anim_state),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_NODE_START(),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, toad_cap_Metal_Cap_mesh_layer_1),
							GEO_DISPLAY_LIST(LAYER_ALPHA, toad_cap_Winged_Metal_Cap_Wings_mesh_layer_4),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_NODE_START(),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, toad_cap_Metal_Cap_mesh_layer_1),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, toad_cap_Winged_Metal_Cap_Wings_mesh_layer_4),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, toad_cap_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, toad_cap_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, toad_cap_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
