s16 tilt_body_running(struct MarioState *m);
void play_step_sound(struct MarioState *m, s16 frame1, s16 frame2);
void align_with_floor(struct MarioState *m);
s32 begin_walking_action(struct MarioState *m, f32 forwardVel, u32 action, u32 actionArg);
void check_ledge_climb_down(struct MarioState *m);
void slide_bonk(struct MarioState *m, u32 fastAction, u32 slowAction);
s32 set_triple_jump_action(struct MarioState *m, UNUSED u32 action, UNUSED u32 actionArg);
void update_sliding_angle(struct MarioState *m, f32 accel, f32 lossFactor);
s32 update_sliding(struct MarioState *m, f32 stopSpeed);
void apply_slope_accel(struct MarioState *m);
s32 apply_landing_accel(struct MarioState *m, f32 frictionFactor);
void update_shell_speed(struct MarioState *m);
s32 apply_slope_decel(struct MarioState *m, f32 decelCoef);
s32 update_decelerating_speed(struct MarioState *m);
void update_walking_speed(struct MarioState *m);
s32 should_begin_sliding(struct MarioState *m);
s32 analog_stick_held_back(struct MarioState *m);
s32 check_ground_dive_or_punch(struct MarioState *m);
s32 begin_braking_action(struct MarioState *m);
void anim_and_audio_for_walk(struct MarioState *m);
void anim_and_audio_for_hold_walk(struct MarioState *m);
void anim_and_audio_for_heavy_walk(struct MarioState *m);
void push_or_sidle_wall(struct MarioState *m, Vec3f startPos);
void tilt_body_walking(struct MarioState *m, s16 startYaw);
void tilt_body_ground_shell(struct MarioState *m, s16 startYaw);
void tilt_body_butt_slide(struct MarioState *m);
void common_slide_action(struct MarioState *m, u32 endAction, u32 airAction, s32 animation);
s32 common_slide_action_with_jump(struct MarioState *m, u32 stopAction, u32 jumpAction, u32 airAction, s32 animation);
s32 stomach_slide_action(struct MarioState *m, u32 stopAction, u32 airAction, s32 animation);
s32 common_ground_knockback_action(struct MarioState *m, s32 animation, s32 arg2, s32 arg3, s32 arg4);
u32 common_landing_action(struct MarioState *m, s16 animation, u32 airAction);
s32 quicksand_jump_land_action(struct MarioState *m, s32 animation1, s32 animation2, u32 endAction, u32 airAction);
s32 check_common_moving_cancels(struct MarioState *m);
s32 mario_execute_moving_action(struct MarioState *m);
