void print_displaying_credits_entry(void);
void bhv_end_peach_loop(void);
void bhv_end_toad_loop(void);
void handle_save_menu(struct MarioState *m);
struct Object *spawn_obj_at_mario_rel_yaw(struct MarioState *m, s32 model, BehaviorScript *behavior, s16 relYaw);
void cutscene_take_cap_off(struct MarioState *m);
void cutscene_put_cap_on(struct MarioState *m);
u8 should_start_or_continue_dialog(struct MarioState* m, struct Object* object);
void general_star_dance_handler(struct MarioState *m, s32 isInWater);
void stuck_in_ground_handler(struct MarioState *m, s32 animation, s32 unstuckFrame, s32 target2, s32 target3, s32 endAction);
void generate_yellow_sparkles(s16 x, s16 y, s16 z, f32 radius);