void add_tree_leaf_particles(struct MarioState *m);
void play_climbing_sounds(struct MarioState *m, s32 b);
s32 set_pole_position(struct MarioState *m, f32 offsetY);
s32 perform_hanging_step(struct MarioState *m, Vec3f nextPos);
s32 update_hang_moving(struct MarioState *m);
void update_hang_stationary(struct MarioState *m);
s32 let_go_of_ledge(struct MarioState *m);
void climb_up_ledge(struct MarioState *m);
void update_ledge_climb_camera(struct MarioState *m);
void update_ledge_climb(struct MarioState *m, s32 animation, u32 endAction);
s32 check_common_automatic_cancels(struct MarioState *m);
s32 mario_execute_automatic_action(struct MarioState *m);
