void add_tree_leaf_particles(struct MarioState *m);
void play_climbing_sounds(struct MarioState *m, s32 b);
s32 set_pole_position(struct MarioState *m, f32 offsetY);
s32 act_holding_pole(struct MarioState *m);
s32 act_climbing_pole(struct MarioState *m);
s32 act_grab_pole_slow(struct MarioState *m);
s32 act_grab_pole_fast(struct MarioState *m);
s32 act_top_of_pole_transition(struct MarioState *m);
s32 act_top_of_pole(struct MarioState *m);
s32 perform_hanging_step(struct MarioState *m, Vec3f nextPos);
s32 update_hang_moving(struct MarioState *m);
void update_hang_stationary(struct MarioState *m);
s32 act_start_hanging(struct MarioState *m);
s32 act_hanging(struct MarioState *m);
s32 act_hang_moving(struct MarioState *m);
s32 let_go_of_ledge(struct MarioState *m);
void climb_up_ledge(struct MarioState *m);
void update_ledge_climb_camera(struct MarioState *m);
void update_ledge_climb(struct MarioState *m, s32 animation, u32 endAction);
s32 act_ledge_grab(struct MarioState *m);
s32 act_ledge_climb_slow(struct MarioState *m);
s32 act_ledge_climb_down(struct MarioState *m);
s32 act_ledge_climb_fast(struct MarioState *m);
s32 act_grabbed(struct MarioState *m);
s32 act_in_cannon(struct MarioState *m);
s32 act_tornado_twirling(struct MarioState *m);
s32 act_bubbled(struct MarioState* m);
s32 check_common_automatic_cancels(struct MarioState *m);
s32 mario_execute_automatic_action(struct MarioState *m);
