void play_flip_sounds(struct MarioState *m, s16 frame1, s16 frame2, s16 frame3);
void play_far_fall_sound(struct MarioState *m);
void play_knockback_sound(struct MarioState *m);
s32 lava_boost_on_wall(struct MarioState *m);
s32 check_fall_damage(struct MarioState *m, u32 hardFallAction);
s32 check_kick_or_dive_in_air(struct MarioState *m);
s32 should_get_stuck_in_ground(struct MarioState *m);
s32 check_fall_damage_or_get_stuck(struct MarioState *m, u32 hardFallAction);
s32 check_horizontal_wind(struct MarioState *m);
void update_air_with_turn(struct MarioState *m);
void update_air_without_turn(struct MarioState *m);
void update_lava_boost_or_twirling(struct MarioState *m);
void update_flying_yaw(struct MarioState *m);
void update_flying_pitch(struct MarioState *m);
void update_flying(struct MarioState *m);
u32 common_air_action_step(struct MarioState *m, u32 landAction, s32 animation, u32 stepArg);
u32 common_air_knockback_step(struct MarioState *m, u32 landAction, u32 hardFallAction, s32 animation, f32 speed);
s32 check_wall_kick(struct MarioState *m);
s32 check_common_airborne_cancels(struct MarioState *m);
s32 mario_execute_airborne_action(struct MarioState *m);
