#include "levels/hl/texture_include.inc.c"
#include "levels/hl/area_1/collision.inc.c"
#include "levels/hl/area_1/macro.inc.c"
#include "levels/hl/area_1/spline.inc.c"
#include "levels/hl/model.inc.c"
