#include "src/game/envfx_snow.h"

const GeoLayout waluigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt1[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_OPAQUE, waluigi_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_1___eye_half_v3_1),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt2[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_OPAQUE, waluigi_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eye_closed_v3_2),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt3[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_OPAQUE, waluigi_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eye_closed_v3_2),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt4[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_OPAQUE, waluigi_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eye_closed_v3_2),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt5[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_OPAQUE, waluigi_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eye_closed_v3_2),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt6[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_OPAQUE, waluigi_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eye_closed_v3_2),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt7[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_OPAQUE, waluigi_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_7___eye_X_v3_3),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_armature_002_switch_option_002[] = {
    GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -43, 0, 0, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
        GEO_OPEN_NODE(),
            GEO_NODE_START(),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, waluigi_002_switch_option_head__no_cap__mesh_layer_1),
            GEO_CLOSE_NODE(),
            GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt1),
            GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt2),
            GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt3),
            GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt4),
            GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt5),
            GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt6),
            GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt7),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_right_hand_open_armature[] = {
    GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -70, -6, 17, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 72, 0, 0, waluigi_002_switch_option_right_hand_open_mesh_layer_1),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_left_hand_open_armature[] = {
    GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -70, -6, -21, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 72, 0, 0, waluigi_002_switch_option_left_hand_open_mesh_layer_1),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_left_hand_peace_armature[] = {
    GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -70, -6, -21, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 72, 0, 0, waluigi_004_switch_option_left_hand_peace_mesh_layer_1),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_left_hand_cap_armature[] = {
    GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -70, -6, -21, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 72, 0, 0, waluigi_005_switch_option_left_hand_cap_mesh_layer_1),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_left_hand_wing_cap_armature[] = {
    GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -70, -6, -21, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 72, 0, 0, waluigi_006_switch_option_left_hand_wing_cap_mesh_layer_1),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_ALPHA, waluigi_006_switch_option_left_hand_wing_cap_wings_mesh_layer_4),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt1[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_TRANSPARENT, waluigi_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_1___eye_half_v3_1),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt2[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_TRANSPARENT, waluigi_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eye_closed_v3_2),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt3[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_TRANSPARENT, waluigi_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eye_closed_v3_2),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt4[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_TRANSPARENT, waluigi_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eye_closed_v3_2),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt5[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_TRANSPARENT, waluigi_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eye_closed_v3_2),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt6[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_TRANSPARENT, waluigi_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eye_closed_v3_2),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt7[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_TRANSPARENT, waluigi_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_7___eye_X_v3_3),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt1_jump_waluigi_armature_002_switch_option_002[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -43, 0, 0, 0, 0, 0),
        GEO_OPEN_NODE(),
            GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
            GEO_OPEN_NODE(),
                GEO_NODE_START(),
                GEO_OPEN_NODE(),
                    GEO_DISPLAY_LIST(LAYER_TRANSPARENT, waluigi_002_switch_option_head__no_cap__mesh_layer_1),
                GEO_CLOSE_NODE(),
                GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt1),
                GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt2),
                GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt3),
                GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt4),
                GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt5),
                GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt6),
                GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt7),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt1_jump_waluigi_right_hand_open_armature[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -70, -6, 17, 0, 0, 0),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 72, 0, 0, waluigi_002_switch_option_right_hand_open_mesh_layer_1),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt1_jump_waluigi_left_hand_open_armature[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -70, -6, -21, 0, 0, 0),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 72, 0, 0, waluigi_002_switch_option_left_hand_open_mesh_layer_1),
            GEO_OPEN_NODE(),
                GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt1_jump_waluigi_left_hand_peace_armature[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -70, -6, -21, 0, 0, 0),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 72, 0, 0, waluigi_004_switch_option_left_hand_peace_mesh_layer_1),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt1_jump_waluigi_left_hand_cap_armature[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -70, -6, -21, 0, 0, 0),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 72, 0, 0, waluigi_005_switch_option_left_hand_cap_mesh_layer_1),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt1_jump_waluigi_left_hand_wing_cap_armature[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -70, -6, -21, 0, 0, 0),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 72, 0, 0, waluigi_006_switch_option_left_hand_wing_cap_mesh_layer_1),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, waluigi_006_switch_option_left_hand_wing_cap_wings_mesh_layer_4),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt1[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_TRANSPARENT, waluigi_000_displaylist_mesh_layer_1_mat_override_face_1___eye_half_v3_1),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt2[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_TRANSPARENT, waluigi_000_displaylist_mesh_layer_1_mat_override_face_2___eye_closed_v3_2),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt3[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_TRANSPARENT, waluigi_000_displaylist_mesh_layer_1_mat_override_face_2___eye_closed_v3_2),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt4[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_TRANSPARENT, waluigi_000_displaylist_mesh_layer_1_mat_override_face_2___eye_closed_v3_2),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt5[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_TRANSPARENT, waluigi_000_displaylist_mesh_layer_1_mat_override_face_2___eye_closed_v3_2),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt6[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_TRANSPARENT, waluigi_000_displaylist_mesh_layer_1_mat_override_face_2___eye_closed_v3_2),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt7[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_TRANSPARENT, waluigi_000_displaylist_mesh_layer_1_mat_override_face_7___eye_X_v3_3),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt1[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 1, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, waluigi_000_offset_mesh_layer_1),
            GEO_OPEN_NODE(),
                GEO_ASM(0, geo_move_mario_part_from_parent),
                GEO_ASM(0, geo_mario_tilt_torso),
                GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 83, 0, 0, waluigi_000_offset_001_mesh_layer_1),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 90, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ASM(0, geo_mario_head_rotation),
                            GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
                            GEO_OPEN_NODE(),
                                GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
                                GEO_OPEN_NODE(),
                                    GEO_NODE_START(),
                                    GEO_OPEN_NODE(),
                                        GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
                                        GEO_OPEN_NODE(),
                                            GEO_NODE_START(),
                                            GEO_OPEN_NODE(),
                                                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, waluigi_000_displaylist_mesh_layer_1),
                                            GEO_CLOSE_NODE(),
                                            GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt1),
                                            GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt2),
                                            GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt3),
                                            GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt4),
                                            GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt5),
                                            GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt6),
                                            GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt7),
                                        GEO_CLOSE_NODE(),
                                    GEO_CLOSE_NODE(),
                                    GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt1_jump_waluigi_armature_002_switch_option_002),
                                GEO_CLOSE_NODE(),
                                GEO_TRANSLATE_ROTATE(LAYER_FORCE, 134, -55, -117, 15, -33, -133),
                                GEO_OPEN_NODE(),
                                    GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
                                    GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
                                    GEO_OPEN_NODE(),
                                        GEO_DISPLAY_LIST(LAYER_TRANSPARENT, waluigi_000_displaylist_001_mesh_layer_4),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                                GEO_TRANSLATE_ROTATE(LAYER_FORCE, 134, -55, 117, -15, 33, -133),
                                GEO_OPEN_NODE(),
                                    GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
                                    GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
                                    GEO_OPEN_NODE(),
                                        GEO_DISPLAY_LIST(LAYER_TRANSPARENT, waluigi_000_displaylist_002_mesh_layer_4),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 65, -6, 78, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, waluigi_000_offset_003_mesh_layer_1),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 106, 0, 0, waluigi_000_offset_004_mesh_layer_1),
                                GEO_OPEN_NODE(),
                                    GEO_SWITCH_CASE(1, geo_switch_mario_hand),
                                    GEO_OPEN_NODE(),
                                        GEO_NODE_START(),
                                        GEO_OPEN_NODE(),
                                            GEO_ANIMATED_PART(LAYER_OPAQUE, 106, 0, 0, NULL),
                                            GEO_OPEN_NODE(),
                                                GEO_ASM(1, geo_mario_hand_foot_scaler),
                                                GEO_SCALE(LAYER_FORCE, 65536),
                                                GEO_OPEN_NODE(),
                                                    GEO_DISPLAY_LIST(LAYER_TRANSPARENT, waluigi_000_displaylist_003_mesh_layer_1),
                                                GEO_CLOSE_NODE(),
                                            GEO_CLOSE_NODE(),
                                        GEO_CLOSE_NODE(),
                                        GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt1_jump_waluigi_right_hand_open_armature),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 66, -6, -74, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, waluigi_000_offset_006_mesh_layer_1),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 106, 0, 0, waluigi_000_offset_007_mesh_layer_1),
                                GEO_OPEN_NODE(),
                                    GEO_SWITCH_CASE(0, geo_switch_mario_hand),
                                    GEO_OPEN_NODE(),
                                        GEO_NODE_START(),
                                        GEO_OPEN_NODE(),
                                            GEO_ANIMATED_PART(LAYER_OPAQUE, 106, 0, 0, NULL),
                                            GEO_OPEN_NODE(),
                                                GEO_ASM(0, geo_mario_hand_foot_scaler),
                                                GEO_SCALE(LAYER_FORCE, 65536),
                                                GEO_OPEN_NODE(),
                                                    GEO_DISPLAY_LIST(LAYER_TRANSPARENT, waluigi_000_displaylist_004_mesh_layer_1),
                                                GEO_CLOSE_NODE(),
                                                GEO_HELD_OBJECT(0, -104, -6, -21, geo_switch_mario_hand_grab_pos),
                                            GEO_CLOSE_NODE(),
                                        GEO_CLOSE_NODE(),
                                        GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt1_jump_waluigi_left_hand_open_armature),
                                        GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt1_jump_waluigi_left_hand_peace_armature),
                                        GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt1_jump_waluigi_left_hand_cap_armature),
                                        GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt1_jump_waluigi_left_hand_wing_cap_armature),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 24, -10, 50, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, waluigi_000_offset_009_mesh_layer_1),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 165, 0, 0, waluigi_000_offset_010_LEFT_KNEE_mesh_layer_1),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 134, 0, 0, waluigi_000_offset_011_BOTTOM_LEG_mesh_layer_1),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 24, -10, -50, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, waluigi_000_offset_012_mesh_layer_1),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 165, 0, 0, waluigi_000_offset_013_RIGHT_KNEE_mesh_layer_1),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 134, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ASM(2, geo_mario_hand_foot_scaler),
                                GEO_SCALE(LAYER_FORCE, 65536),
                                GEO_OPEN_NODE(),
                                    GEO_DISPLAY_LIST(LAYER_TRANSPARENT, waluigi_000_displaylist_005_mesh_layer_1),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt2_jump_waluigi_armature_002_switch_option_002[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -43, 0, 0, 0, 0, 0),
        GEO_OPEN_NODE(),
            GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
            GEO_OPEN_NODE(),
                GEO_NODE_START(),
                GEO_OPEN_NODE(),
                    GEO_DISPLAY_LIST(LAYER_OPAQUE, waluigi_002_switch_option_head__no_cap__mesh_layer_1_mat_override_metal_v3_0),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt2_jump_waluigi_right_hand_open_armature[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -70, -6, 17, 0, 0, 0),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 72, 0, 0, waluigi_002_switch_option_right_hand_open_mesh_layer_1_mat_override_metal_v3_0),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt2_jump_waluigi_left_hand_open_armature[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -70, -6, -21, 0, 0, 0),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 72, 0, 0, waluigi_002_switch_option_left_hand_open_mesh_layer_1_mat_override_metal_v3_0),
            GEO_OPEN_NODE(),
                GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt2_jump_waluigi_left_hand_peace_armature[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -70, -6, -21, 0, 0, 0),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 72, 0, 0, waluigi_004_switch_option_left_hand_peace_mesh_layer_1_mat_override_metal_v3_0),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt2_jump_waluigi_left_hand_cap_armature[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -70, -6, -21, 0, 0, 0),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 72, 0, 0, waluigi_005_switch_option_left_hand_cap_mesh_layer_1_mat_override_metal_v3_0),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt2_jump_waluigi_left_hand_wing_cap_armature[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -70, -6, -21, 0, 0, 0),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 72, 0, 0, waluigi_006_switch_option_left_hand_wing_cap_mesh_layer_1_mat_override_metal_v3_0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_ALPHA, waluigi_006_switch_option_left_hand_wing_cap_wings_mesh_layer_4_mat_override_metal_v3_0),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt2[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 1, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, waluigi_000_offset_mesh_layer_1_mat_override_metal_v3_0),
            GEO_OPEN_NODE(),
                GEO_ASM(0, geo_move_mario_part_from_parent),
                GEO_ASM(0, geo_mario_tilt_torso),
                GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 83, 0, 0, waluigi_000_offset_001_mesh_layer_1_mat_override_metal_v3_0),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 90, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ASM(0, geo_mario_head_rotation),
                            GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
                            GEO_OPEN_NODE(),
                                GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
                                GEO_OPEN_NODE(),
                                    GEO_NODE_START(),
                                    GEO_OPEN_NODE(),
                                        GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
                                        GEO_OPEN_NODE(),
                                            GEO_NODE_START(),
                                            GEO_OPEN_NODE(),
                                                GEO_DISPLAY_LIST(LAYER_OPAQUE, waluigi_000_displaylist_mesh_layer_1_mat_override_metal_v3_0),
                                            GEO_CLOSE_NODE(),
                                        GEO_CLOSE_NODE(),
                                    GEO_CLOSE_NODE(),
                                    GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt2_jump_waluigi_armature_002_switch_option_002),
                                GEO_CLOSE_NODE(),
                                GEO_TRANSLATE_ROTATE(LAYER_FORCE, 134, -55, -117, 15, -33, -133),
                                GEO_OPEN_NODE(),
                                    GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
                                    GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
                                    GEO_OPEN_NODE(),
                                        GEO_DISPLAY_LIST(LAYER_ALPHA, waluigi_000_displaylist_001_mesh_layer_4_mat_override_metal_v3_0),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                                GEO_TRANSLATE_ROTATE(LAYER_FORCE, 134, -55, 117, -15, 33, -133),
                                GEO_OPEN_NODE(),
                                    GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
                                    GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
                                    GEO_OPEN_NODE(),
                                        GEO_DISPLAY_LIST(LAYER_ALPHA, waluigi_000_displaylist_002_mesh_layer_4_mat_override_metal_v3_0),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 65, -6, 78, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, waluigi_000_offset_003_mesh_layer_1_mat_override_metal_v3_0),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 106, 0, 0, waluigi_000_offset_004_mesh_layer_1_mat_override_metal_v3_0),
                                GEO_OPEN_NODE(),
                                    GEO_SWITCH_CASE(1, geo_switch_mario_hand),
                                    GEO_OPEN_NODE(),
                                        GEO_NODE_START(),
                                        GEO_OPEN_NODE(),
                                            GEO_ANIMATED_PART(LAYER_OPAQUE, 106, 0, 0, NULL),
                                            GEO_OPEN_NODE(),
                                                GEO_ASM(1, geo_mario_hand_foot_scaler),
                                                GEO_SCALE(LAYER_FORCE, 65536),
                                                GEO_OPEN_NODE(),
                                                    GEO_DISPLAY_LIST(LAYER_OPAQUE, waluigi_000_displaylist_003_mesh_layer_1_mat_override_metal_v3_0),
                                                GEO_CLOSE_NODE(),
                                            GEO_CLOSE_NODE(),
                                        GEO_CLOSE_NODE(),
                                        GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt2_jump_waluigi_right_hand_open_armature),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 66, -6, -74, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, waluigi_000_offset_006_mesh_layer_1_mat_override_metal_v3_0),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 106, 0, 0, waluigi_000_offset_007_mesh_layer_1_mat_override_metal_v3_0),
                                GEO_OPEN_NODE(),
                                    GEO_SWITCH_CASE(0, geo_switch_mario_hand),
                                    GEO_OPEN_NODE(),
                                        GEO_NODE_START(),
                                        GEO_OPEN_NODE(),
                                            GEO_ANIMATED_PART(LAYER_OPAQUE, 106, 0, 0, NULL),
                                            GEO_OPEN_NODE(),
                                                GEO_ASM(0, geo_mario_hand_foot_scaler),
                                                GEO_SCALE(LAYER_FORCE, 65536),
                                                GEO_OPEN_NODE(),
                                                    GEO_DISPLAY_LIST(LAYER_OPAQUE, waluigi_000_displaylist_004_mesh_layer_1_mat_override_metal_v3_0),
                                                GEO_CLOSE_NODE(),
                                                GEO_HELD_OBJECT(0, -104, -6, -21, geo_switch_mario_hand_grab_pos),
                                            GEO_CLOSE_NODE(),
                                        GEO_CLOSE_NODE(),
                                        GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt2_jump_waluigi_left_hand_open_armature),
                                        GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt2_jump_waluigi_left_hand_peace_armature),
                                        GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt2_jump_waluigi_left_hand_cap_armature),
                                        GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt2_jump_waluigi_left_hand_wing_cap_armature),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 24, -10, 50, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, waluigi_000_offset_009_mesh_layer_1_mat_override_metal_v3_0),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 165, 0, 0, waluigi_000_offset_010_LEFT_KNEE_mesh_layer_1_mat_override_metal_v3_0),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 134, 0, 0, waluigi_000_offset_011_BOTTOM_LEG_mesh_layer_1_mat_override_metal_v3_0),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 24, -10, -50, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, waluigi_000_offset_012_mesh_layer_1_mat_override_metal_v3_0),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 165, 0, 0, waluigi_000_offset_013_RIGHT_KNEE_mesh_layer_1_mat_override_metal_v3_0),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 134, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ASM(2, geo_mario_hand_foot_scaler),
                                GEO_SCALE(LAYER_FORCE, 65536),
                                GEO_OPEN_NODE(),
                                    GEO_DISPLAY_LIST(LAYER_OPAQUE, waluigi_000_displaylist_005_mesh_layer_1_mat_override_metal_v3_0),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt3_jump_waluigi_armature_002_switch_option_002[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -43, 0, 0, 0, 0, 0),
        GEO_OPEN_NODE(),
            GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
            GEO_OPEN_NODE(),
                GEO_NODE_START(),
                GEO_OPEN_NODE(),
                    GEO_DISPLAY_LIST(LAYER_TRANSPARENT, waluigi_002_switch_option_head__no_cap__mesh_layer_1_mat_override_metal_v3_0),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt3_jump_waluigi_right_hand_open_armature[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -70, -6, 17, 0, 0, 0),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 72, 0, 0, waluigi_002_switch_option_right_hand_open_mesh_layer_1_mat_override_metal_v3_0),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt3_jump_waluigi_left_hand_open_armature[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -70, -6, -21, 0, 0, 0),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 72, 0, 0, waluigi_002_switch_option_left_hand_open_mesh_layer_1_mat_override_metal_v3_0),
            GEO_OPEN_NODE(),
                GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt3_jump_waluigi_left_hand_peace_armature[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -70, -6, -21, 0, 0, 0),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 72, 0, 0, waluigi_004_switch_option_left_hand_peace_mesh_layer_1_mat_override_metal_v3_0),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt3_jump_waluigi_left_hand_cap_armature[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -70, -6, -21, 0, 0, 0),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 72, 0, 0, waluigi_005_switch_option_left_hand_cap_mesh_layer_1_mat_override_metal_v3_0),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt3_jump_waluigi_left_hand_wing_cap_armature[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -70, -6, -21, 0, 0, 0),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 72, 0, 0, waluigi_006_switch_option_left_hand_wing_cap_mesh_layer_1_mat_override_metal_v3_0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, waluigi_006_switch_option_left_hand_wing_cap_wings_mesh_layer_4_mat_override_metal_v3_0),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt3[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 1, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, waluigi_000_offset_mesh_layer_1_mat_override_metal_v3_0),
            GEO_OPEN_NODE(),
                GEO_ASM(0, geo_move_mario_part_from_parent),
                GEO_ASM(0, geo_mario_tilt_torso),
                GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 83, 0, 0, waluigi_000_offset_001_mesh_layer_1_mat_override_metal_v3_0),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 90, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ASM(0, geo_mario_head_rotation),
                            GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
                            GEO_OPEN_NODE(),
                                GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
                                GEO_OPEN_NODE(),
                                    GEO_NODE_START(),
                                    GEO_OPEN_NODE(),
                                        GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
                                        GEO_OPEN_NODE(),
                                            GEO_NODE_START(),
                                            GEO_OPEN_NODE(),
                                                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, waluigi_000_displaylist_mesh_layer_1_mat_override_metal_v3_0),
                                            GEO_CLOSE_NODE(),
                                        GEO_CLOSE_NODE(),
                                    GEO_CLOSE_NODE(),
                                    GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt3_jump_waluigi_armature_002_switch_option_002),
                                GEO_CLOSE_NODE(),
                                GEO_TRANSLATE_ROTATE(LAYER_FORCE, 134, -55, -117, 15, -33, -133),
                                GEO_OPEN_NODE(),
                                    GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
                                    GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
                                    GEO_OPEN_NODE(),
                                        GEO_DISPLAY_LIST(LAYER_TRANSPARENT, waluigi_000_displaylist_001_mesh_layer_4_mat_override_metal_v3_0),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                                GEO_TRANSLATE_ROTATE(LAYER_FORCE, 134, -55, 117, -15, 33, -133),
                                GEO_OPEN_NODE(),
                                    GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
                                    GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
                                    GEO_OPEN_NODE(),
                                        GEO_DISPLAY_LIST(LAYER_TRANSPARENT, waluigi_000_displaylist_002_mesh_layer_4_mat_override_metal_v3_0),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 65, -6, 78, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, waluigi_000_offset_003_mesh_layer_1_mat_override_metal_v3_0),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 106, 0, 0, waluigi_000_offset_004_mesh_layer_1_mat_override_metal_v3_0),
                                GEO_OPEN_NODE(),
                                    GEO_SWITCH_CASE(1, geo_switch_mario_hand),
                                    GEO_OPEN_NODE(),
                                        GEO_NODE_START(),
                                        GEO_OPEN_NODE(),
                                            GEO_ANIMATED_PART(LAYER_OPAQUE, 106, 0, 0, NULL),
                                            GEO_OPEN_NODE(),
                                                GEO_ASM(1, geo_mario_hand_foot_scaler),
                                                GEO_SCALE(LAYER_FORCE, 65536),
                                                GEO_OPEN_NODE(),
                                                    GEO_DISPLAY_LIST(LAYER_TRANSPARENT, waluigi_000_displaylist_003_mesh_layer_1_mat_override_metal_v3_0),
                                                GEO_CLOSE_NODE(),
                                            GEO_CLOSE_NODE(),
                                        GEO_CLOSE_NODE(),
                                        GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt3_jump_waluigi_right_hand_open_armature),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 66, -6, -74, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, waluigi_000_offset_006_mesh_layer_1_mat_override_metal_v3_0),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 106, 0, 0, waluigi_000_offset_007_mesh_layer_1_mat_override_metal_v3_0),
                                GEO_OPEN_NODE(),
                                    GEO_SWITCH_CASE(0, geo_switch_mario_hand),
                                    GEO_OPEN_NODE(),
                                        GEO_NODE_START(),
                                        GEO_OPEN_NODE(),
                                            GEO_ANIMATED_PART(LAYER_OPAQUE, 106, 0, 0, NULL),
                                            GEO_OPEN_NODE(),
                                                GEO_ASM(0, geo_mario_hand_foot_scaler),
                                                GEO_SCALE(LAYER_FORCE, 65536),
                                                GEO_OPEN_NODE(),
                                                    GEO_DISPLAY_LIST(LAYER_TRANSPARENT, waluigi_000_displaylist_004_mesh_layer_1_mat_override_metal_v3_0),
                                                GEO_CLOSE_NODE(),
                                                GEO_HELD_OBJECT(0, -104, -6, -21, geo_switch_mario_hand_grab_pos),
                                            GEO_CLOSE_NODE(),
                                        GEO_CLOSE_NODE(),
                                        GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt3_jump_waluigi_left_hand_open_armature),
                                        GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt3_jump_waluigi_left_hand_peace_armature),
                                        GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt3_jump_waluigi_left_hand_cap_armature),
                                        GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt3_jump_waluigi_left_hand_wing_cap_armature),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 24, -10, 50, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, waluigi_000_offset_009_mesh_layer_1_mat_override_metal_v3_0),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 165, 0, 0, waluigi_000_offset_010_LEFT_KNEE_mesh_layer_1_mat_override_metal_v3_0),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 134, 0, 0, waluigi_000_offset_011_BOTTOM_LEG_mesh_layer_1_mat_override_metal_v3_0),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 24, -10, -50, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, waluigi_000_offset_012_mesh_layer_1_mat_override_metal_v3_0),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 165, 0, 0, waluigi_000_offset_013_RIGHT_KNEE_mesh_layer_1_mat_override_metal_v3_0),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 134, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ASM(2, geo_mario_hand_foot_scaler),
                                GEO_SCALE(LAYER_FORCE, 65536),
                                GEO_OPEN_NODE(),
                                    GEO_DISPLAY_LIST(LAYER_TRANSPARENT, waluigi_000_displaylist_005_mesh_layer_1_mat_override_metal_v3_0),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt1[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_OPAQUE, waluigi_000_displaylist_mesh_layer_1_mat_override_face_1___eye_half_v3_1),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt2[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_OPAQUE, waluigi_000_displaylist_mesh_layer_1_mat_override_face_2___eye_closed_v3_2),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt3[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_OPAQUE, waluigi_000_displaylist_mesh_layer_1_mat_override_face_2___eye_closed_v3_2),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt4[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_OPAQUE, waluigi_000_displaylist_mesh_layer_1_mat_override_face_2___eye_closed_v3_2),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt5[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_OPAQUE, waluigi_000_displaylist_mesh_layer_1_mat_override_face_2___eye_closed_v3_2),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt6[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_OPAQUE, waluigi_000_displaylist_mesh_layer_1_mat_override_face_2___eye_closed_v3_2),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt7[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(LAYER_OPAQUE, waluigi_000_displaylist_mesh_layer_1_mat_override_face_7___eye_X_v3_3),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};
const GeoLayout waluigi_geo[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_SHADOW(1, 180, 100),
        GEO_OPEN_NODE(),
            GEO_SCALE(LAYER_FORCE, 16384),
            GEO_OPEN_NODE(),
                GEO_ASM(0, geo_mario_set_player_colors),
                GEO_ASM(0, geo_mirror_mario_backface_culling),
                GEO_ASM(0, geo_mirror_mario_set_alpha),
                GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
                GEO_OPEN_NODE(),
                    GEO_NODE_START(),
                    GEO_OPEN_NODE(),
                        GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
                        GEO_OPEN_NODE(),
                            GEO_NODE_START(),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 1, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, waluigi_000_offset_mesh_layer_1),
                                    GEO_OPEN_NODE(),
                                        GEO_ASM(0, geo_move_mario_part_from_parent),
                                        GEO_ASM(0, geo_mario_tilt_torso),
                                        GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
                                        GEO_OPEN_NODE(),
                                            GEO_ANIMATED_PART(LAYER_OPAQUE, 83, 0, 0, waluigi_000_offset_001_mesh_layer_1),
                                            GEO_OPEN_NODE(),
                                                GEO_ANIMATED_PART(LAYER_OPAQUE, 90, 0, 0, NULL),
                                                GEO_OPEN_NODE(),
                                                    GEO_ASM(0, geo_mario_head_rotation),
                                                    GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
                                                    GEO_OPEN_NODE(),
                                                        GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
                                                        GEO_OPEN_NODE(),
                                                            GEO_NODE_START(),
                                                            GEO_OPEN_NODE(),
                                                                GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
                                                                GEO_OPEN_NODE(),
                                                                    GEO_NODE_START(),
                                                                    GEO_OPEN_NODE(),
                                                                        GEO_DISPLAY_LIST(LAYER_OPAQUE, waluigi_000_displaylist_mesh_layer_1),
                                                                    GEO_CLOSE_NODE(),
                                                                    GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt1),
                                                                    GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt2),
                                                                    GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt3),
                                                                    GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt4),
                                                                    GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt5),
                                                                    GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt6),
                                                                    GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt7),
                                                                GEO_CLOSE_NODE(),
                                                            GEO_CLOSE_NODE(),
                                                            GEO_BRANCH(1, waluigi_armature_002_switch_option_002),
                                                        GEO_CLOSE_NODE(),
                                                        GEO_TRANSLATE_ROTATE(LAYER_FORCE, 134, -55, -117, 15, -33, -133),
                                                        GEO_OPEN_NODE(),
                                                            GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
                                                            GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
                                                            GEO_OPEN_NODE(),
                                                                GEO_DISPLAY_LIST(LAYER_ALPHA, waluigi_000_displaylist_001_mesh_layer_4),
                                                            GEO_CLOSE_NODE(),
                                                        GEO_CLOSE_NODE(),
                                                        GEO_TRANSLATE_ROTATE(LAYER_FORCE, 134, -55, 117, -15, 33, -133),
                                                        GEO_OPEN_NODE(),
                                                            GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
                                                            GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
                                                            GEO_OPEN_NODE(),
                                                                GEO_DISPLAY_LIST(LAYER_ALPHA, waluigi_000_displaylist_002_mesh_layer_4),
                                                            GEO_CLOSE_NODE(),
                                                        GEO_CLOSE_NODE(),
                                                    GEO_CLOSE_NODE(),
                                                GEO_CLOSE_NODE(),
                                                GEO_ANIMATED_PART(LAYER_OPAQUE, 65, -6, 78, NULL),
                                                GEO_OPEN_NODE(),
                                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, waluigi_000_offset_003_mesh_layer_1),
                                                    GEO_OPEN_NODE(),
                                                        GEO_ANIMATED_PART(LAYER_OPAQUE, 106, 0, 0, waluigi_000_offset_004_mesh_layer_1),
                                                        GEO_OPEN_NODE(),
                                                            GEO_SWITCH_CASE(1, geo_switch_mario_hand),
                                                            GEO_OPEN_NODE(),
                                                                GEO_NODE_START(),
                                                                GEO_OPEN_NODE(),
                                                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 106, 0, 0, NULL),
                                                                    GEO_OPEN_NODE(),
                                                                        GEO_ASM(1, geo_mario_hand_foot_scaler),
                                                                        GEO_SCALE(LAYER_FORCE, 65536),
                                                                        GEO_OPEN_NODE(),
                                                                            GEO_DISPLAY_LIST(LAYER_OPAQUE, waluigi_000_displaylist_003_mesh_layer_1),
                                                                        GEO_CLOSE_NODE(),
                                                                    GEO_CLOSE_NODE(),
                                                                GEO_CLOSE_NODE(),
                                                                GEO_BRANCH(1, waluigi_right_hand_open_armature),
                                                            GEO_CLOSE_NODE(),
                                                        GEO_CLOSE_NODE(),
                                                    GEO_CLOSE_NODE(),
                                                GEO_CLOSE_NODE(),
                                                GEO_ANIMATED_PART(LAYER_OPAQUE, 66, -6, -74, NULL),
                                                GEO_OPEN_NODE(),
                                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, waluigi_000_offset_006_mesh_layer_1),
                                                    GEO_OPEN_NODE(),
                                                        GEO_ANIMATED_PART(LAYER_OPAQUE, 106, 0, 0, waluigi_000_offset_007_mesh_layer_1),
                                                        GEO_OPEN_NODE(),
                                                            GEO_SWITCH_CASE(0, geo_switch_mario_hand),
                                                            GEO_OPEN_NODE(),
                                                                GEO_NODE_START(),
                                                                GEO_OPEN_NODE(),
                                                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 106, 0, 0, NULL),
                                                                    GEO_OPEN_NODE(),
                                                                        GEO_ASM(0, geo_mario_hand_foot_scaler),
                                                                        GEO_SCALE(LAYER_FORCE, 65536),
                                                                        GEO_OPEN_NODE(),
                                                                            GEO_DISPLAY_LIST(LAYER_OPAQUE, waluigi_000_displaylist_004_mesh_layer_1),
                                                                        GEO_CLOSE_NODE(),
                                                                        GEO_HELD_OBJECT(0, -104, -6, -21, geo_switch_mario_hand_grab_pos),
                                                                    GEO_CLOSE_NODE(),
                                                                GEO_CLOSE_NODE(),
                                                                GEO_BRANCH(1, waluigi_left_hand_open_armature),
                                                                GEO_BRANCH(1, waluigi_left_hand_peace_armature),
                                                                GEO_BRANCH(1, waluigi_left_hand_cap_armature),
                                                                GEO_BRANCH(1, waluigi_left_hand_wing_cap_armature),
                                                            GEO_CLOSE_NODE(),
                                                        GEO_CLOSE_NODE(),
                                                    GEO_CLOSE_NODE(),
                                                GEO_CLOSE_NODE(),
                                            GEO_CLOSE_NODE(),
                                        GEO_CLOSE_NODE(),
                                        GEO_ANIMATED_PART(LAYER_OPAQUE, 24, -10, 50, NULL),
                                        GEO_OPEN_NODE(),
                                            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, waluigi_000_offset_009_mesh_layer_1),
                                            GEO_OPEN_NODE(),
                                                GEO_ANIMATED_PART(LAYER_OPAQUE, 165, 0, 0, waluigi_000_offset_010_LEFT_KNEE_mesh_layer_1),
                                                GEO_OPEN_NODE(),
                                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 134, 0, 0, waluigi_000_offset_011_BOTTOM_LEG_mesh_layer_1),
                                                GEO_CLOSE_NODE(),
                                            GEO_CLOSE_NODE(),
                                        GEO_CLOSE_NODE(),
                                        GEO_ANIMATED_PART(LAYER_OPAQUE, 24, -10, -50, NULL),
                                        GEO_OPEN_NODE(),
                                            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, waluigi_000_offset_012_mesh_layer_1),
                                            GEO_OPEN_NODE(),
                                                GEO_ANIMATED_PART(LAYER_OPAQUE, 165, 0, 0, waluigi_000_offset_013_RIGHT_KNEE_mesh_layer_1),
                                                GEO_OPEN_NODE(),
                                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 134, 0, 0, NULL),
                                                    GEO_OPEN_NODE(),
                                                        GEO_ASM(2, geo_mario_hand_foot_scaler),
                                                        GEO_SCALE(LAYER_FORCE, 65536),
                                                        GEO_OPEN_NODE(),
                                                            GEO_DISPLAY_LIST(LAYER_OPAQUE, waluigi_000_displaylist_005_mesh_layer_1),
                                                        GEO_CLOSE_NODE(),
                                                    GEO_CLOSE_NODE(),
                                                GEO_CLOSE_NODE(),
                                            GEO_CLOSE_NODE(),
                                        GEO_CLOSE_NODE(),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                            GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt1),
                            GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt2),
                            GEO_BRANCH(1, waluigi_002_switch_opt0_001_switch_opt3),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
                GEO_ASM(1, geo_mirror_mario_backface_culling),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_DISPLAY_LIST(LAYER_OPAQUE, waluigi_material_revert_render_settings),
        GEO_DISPLAY_LIST(LAYER_ALPHA, waluigi_material_revert_render_settings),
        GEO_DISPLAY_LIST(LAYER_TRANSPARENT, waluigi_material_revert_render_settings),
    GEO_CLOSE_NODE(),
    GEO_END(),
};
