extern const GeoLayout arena_flag_blue_geo[];
extern Lights1 arena_flag_blue_wood_lights;
extern Lights1 arena_flag_blue_cloth_lights;
extern u8 arena_flag_blue_wood_ci8[];
extern u8 arena_flag_blue_wood_ci8_pal_rgba16[];
extern u8 arena_flag_blue_cloth_2_i8[];
extern Vtx arena_flag_blue_flag_mesh_layer_1_vtx_0[81];
extern Gfx arena_flag_blue_flag_mesh_layer_1_tri_0[];
extern Vtx arena_flag_blue_flag_mesh_layer_1_vtx_1[6];
extern Gfx arena_flag_blue_flag_mesh_layer_1_tri_1[];
extern Gfx mat_arena_flag_blue_wood[];
extern Gfx mat_revert_arena_flag_blue_wood[];
extern Gfx mat_arena_flag_blue_cloth[];
extern Gfx mat_revert_arena_flag_blue_cloth[];
extern Gfx arena_flag_blue_flag_mesh_layer_1[];
extern Gfx arena_flag_blue_material_revert_render_settings[];
