name: Build coop

on:
    workflow_dispatch:
    push:
        branches: [ dev ]
    pull_request:
        branches: [ dev ]

jobs:
    build:
        if: ${{ (github.event_name != 'push' || contains(github.event.head_commit.message, '[build]')) && github.event.pull_request.draft == false }}
        strategy:
          fail-fast: false
          matrix:
            platform:
              - name: Windows
                os: windows-latest
                make: make -j$(nproc)
                exe: .exe
                zip: dynos lang mods palettes coop.map discord_game_sdk.dll sm64coopdx.exe coopdx_updater.exe

              - name: Linux
                os: ubuntu-22.04
                deps: |
                  sudo apt update
                  sudo apt install -y build-essential git python3 libglew-dev libz-dev libcurl4-openssl-dev zip
                make: make -j$(nproc)
                zip: dynos lang mods palettes libdiscord_game_sdk.so sm64coopdx coopdx_updater

              - name: SteamOS
                os: ubuntu-22.04
                deps: |
                  sudo apt update
                  sudo apt install -y build-essential git python3 libglew-dev libz-dev libcurl4-openssl-dev zip
                make: make -j$(nproc)
                zip: dynos lang mods palettes libdiscord_game_sdk.so sm64coopdx coopdx_updater

              - name: macOS_ARM
                os: macos-15
                deps: brew install make mingw-w64 pkg-config glfw3 coreutils glew sdl3
                make: gmake OSX_BUILD=1 -j$(sysctl -n hw.ncpu)
                internal: .app/Contents/MacOS/sm64coopdx
                zip: sm64coopdx.app

              - name: macOS_Intel
                os: macos-15-intel
                deps: brew install make mingw-w64 pkg-config glfw3 coreutils glew sdl3
                make: gmake OSX_BUILD=1 -j$(sysctl -n hw.ncpu)
                internal: .app/Contents/MacOS/sm64coopdx
                zip: sm64coopdx.app

        name: ${{ matrix.platform.name }}
        runs-on: ${{ matrix.platform.os }}
        defaults:
            run:
                shell: ${{ case(matrix.platform.name == 'Windows', 'msys2 {0}', 'sh') }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v7
              with:
                persist-credentials: false

            - name: Install MSYS2 (Windows)
              if: ${{ matrix.platform.name == 'Windows' }}
              uses: msys2/setup-msys2@v2
              with:
                msystem: ucrt64
                update: true
                install: >
                    unzip
                    make
                    git
                    mingw-w64-ucrt-x86_64-gcc
                    mingw-w64-ucrt-x86_64-glew
                    mingw-w64-ucrt-x86_64-sdl3
                    mingw-w64-ucrt-x86_64-python
                    mingw-w64-ucrt-x86_64-pkg-config
                    zip

            - name: Install dependencies
              if: ${{ matrix.platform.name != 'Windows' }}
              run: ${{ matrix.platform.deps }}

            - name: Build the game
              run: ${{ matrix.platform.make }} ${{ case(matrix.platform.name == 'SteamOS', 'HANDHELD=1', '') }}

            - name: Codesign Ad-Hoc (macOS)
              if: ${{ contains(matrix.platform.name, 'macOS') }}
              run: |
                codesign --force --deep --sign - ./build/us_pc/sm64coopdx.app

            - name: Generate hash
              run: |
                cd tools
                g++ -std=c++17 -o hash_file${{ matrix.platform.exe }} hash_file.cpp
                echo "::notice ::$(./hash_file${{ matrix.platform.exe }} ../build/us_pc/sm64coopdx${{ matrix.platform.exe }}${{ matrix.platform.internal }})"

            - name: Zip the game
              run: |
                cd ./build/us_pc
                zip -r sm64coopdx_${{ matrix.platform.name }}.zip ${{ matrix.platform.zip }}

            - name: Upload artifact
              uses: actions/upload-artifact@v7
              with:
                path: ./build/us_pc/sm64coopdx_${{ matrix.platform.name }}.zip
                archive: false
